(function(){
'use strict';
const P=window.ProtoLab;
function d(offset){ const x=new Date(); x.setDate(x.getDate()+offset); return x.toISOString().slice(0,10); }
function dt(offset,hour=9){ const x=new Date(); x.setDate(x.getDate()+offset); x.setHours(hour,0,0,0); return x.toISOString(); }
function demoEvidenceImage(title,serial,accent='#0c6670'){const safe=String(title||'Evidence').replace(/[<>&]/g,' '),sid=String(serial||'Sample').replace(/[<>&]/g,' '),svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 560"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#17272c"/><stop offset="1" stop-color="#41555a"/></linearGradient><radialGradient id="m"><stop stop-color="#d7e4e6"/><stop offset="1" stop-color="#71858a"/></radialGradient></defs><rect width="900" height="560" fill="url(#g)"/><ellipse cx="450" cy="305" rx="255" ry="125" fill="#0a1417" opacity=".55"/><rect x="280" y="205" width="340" height="180" rx="60" fill="url(#m)" stroke="#eaf3f4" stroke-width="6"/><circle cx="325" cy="295" r="54" fill="#2a3a3e" stroke="${accent}" stroke-width="12"/><rect x="560" y="250" width="135" height="90" rx="18" fill="#d7e0e1"/><rect x="587" y="271" width="80" height="48" rx="7" fill="#26383c"/><line x1="360" y1="260" x2="545" y2="260" stroke="${accent}" stroke-width="10"/><line x1="360" y1="330" x2="545" y2="330" stroke="#94a9ad" stroke-width="7"/><text x="42" y="62" fill="#fff" font-family="Arial,sans-serif" font-size="30" font-weight="700">DEMO EVIDENCE IMAGE</text><text x="42" y="104" fill="#b7cbcf" font-family="Arial,sans-serif" font-size="22">${safe}</text><text x="42" y="520" fill="#d8e6e8" font-family="Arial,sans-serif" font-size="22">${sid}</text></svg>`;return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`}
const users=[
 {id:'U01',name:'Eva de Vries',role:'engineering_requester',team:'ADAS Sensors'},{id:'U02',name:'Jonas Meijer',role:'engineering_lead',team:'Powertrain Electronics'},{id:'U03',name:'Mila Jansen',role:'lab_planner',team:'Prototype Lab'},{id:'U04',name:'Noah Visser',role:'process_engineer',team:'Process Engineering'},{id:'U05',name:'Liam Smit',role:'technician',team:'Prototype Lab'},{id:'U06',name:'Sofia Bakker',role:'quality',team:'Quality'},{id:'U07',name:'Daan Mulder',role:'metrology',team:'Metrology'},{id:'U08',name:'Emma Bos',role:'product_safety',team:'Product Safety'},{id:'U09',name:'Lucas Vos',role:'lab_manager',team:'Prototype Lab'},{id:'U10',name:'Nora Dekker',role:'approver',team:'Engineering Excellence'},{id:'U11',name:'Omar Peters',role:'auditor',team:'Internal Audit'},{id:'U12',name:'Amina Kuiper',role:'administrator',team:'Systems'}
];
const teams=['ADAS Sensors','Powertrain Electronics','Thermal Systems','Chassis Controls','Electrification','Advanced Engineering'];
const products=[
 {id:'PRD-001',family:'Brake Pressure Sensor',partNumber:'BPS-3200',revision:'D',hw:'HW4',sw:'3.8.1',safety:true},
 {id:'PRD-002',family:'Battery Current Sensor',partNumber:'BCS-810',revision:'B',hw:'HW2',sw:'2.4.0',safety:true},
 {id:'PRD-003',family:'Coolant Pressure Sensor',partNumber:'CPS-220',revision:'C',hw:'HW3',sw:'—',safety:false},
 {id:'PRD-004',family:'Pedal Position Module',partNumber:'PPM-700',revision:'A',hw:'HW1',sw:'1.2.5',safety:true},
 {id:'PRD-005',family:'Hydrogen Leak Sensor',partNumber:'HLS-900',revision:'B',hw:'HW2',sw:'4.0.2',safety:true},
 {id:'PRD-006',family:'Thermal Valve Controller',partNumber:'TVC-410',revision:'E',hw:'HW5',sw:'5.1.0',safety:false},
 {id:'PRD-007',family:'Steering Torque Sensor',partNumber:'STS-1140',revision:'C',hw:'HW3',sw:'2.9.3',safety:true},
 {id:'PRD-008',family:'Prototype Signal Conditioner',partNumber:'PSC-X2',revision:'P3',hw:'HW-P3',sw:'0.9.8',safety:false}
];
const processNames=['Material Receipt','Incoming Inspection','Cleaning','Surface Preparation','Adhesive Dispense','Laser Welding','Resistance Welding','Soldering','Wire Bonding','Mechanical Assembly','Fastening / Torque','Potting','Cure','Programming / Flashing','Calibration','Leak Testing','Electrical Test','Dimensional Inspection','Optical Inspection','Functional Verification','Final Inspection','Packaging','Connector Crimp','Ultrasonic Cleaning','Pressure Cycling','Thermal Soak','Conformal Coat','X-ray Inspection'];
function processParamsForName(name,i){
 const mk=(name,target='',unit='',captureLevel='batch',dataClass='setup',required=true)=>({name,target,unit,captureLevel,dataClass,required});
 const key=String(name).toLowerCase();
 if(key==='material receipt')return [mk('Delivery / lot reference','','','batch','observation'),mk('Material status','Accepted','','batch','observation')];
 if(key==='incoming inspection')return [mk('Inspection plan / drawing revision','','','batch','recipe'),mk('Incoming inspection result','Pass','','sample','observation')];
 if(key==='cleaning'||key==='ultrasonic cleaning')return [mk('Cleaning recipe / program','','','batch','recipe'),mk('Bath temperature',45,'°C','batch','machine'),mk('Cleaning time',8,'min','batch','machine')];
 if(key==='surface preparation')return [mk('Surface preparation method','','','batch','recipe'),mk('Surface condition','Accept','','sample','observation')];
 if(key.includes('adhesive dispense'))return [mk('Dispense recipe','','','batch','recipe'),mk('Dispense pressure',2.4,'bar','batch','machine'),mk('Dispense mass',1.8,'g','sample','measurement')];
 if(key.includes('laser welding'))return [mk('Weld recipe','','','batch','recipe'),mk('Laser power',500,'W','batch','machine'),mk('Travel speed',10,'mm/s','batch','machine')];
 if(key.includes('resistance welding'))return [mk('Weld program','','','batch','recipe'),mk('Weld current',8.5,'kA','batch','machine'),mk('Weld time',120,'ms','batch','machine')];
 if(key==='soldering')return [mk('Solder profile / recipe','','','batch','recipe'),mk('Peak temperature',245,'°C','batch','machine')];
 if(key==='wire bonding')return [mk('Bond program','','','batch','recipe'),mk('Bond force',35,'cN','batch','machine')];
 if(key==='mechanical assembly')return [mk('Assembly instruction revision','','','batch','recipe'),mk('Assembly completed','Yes','','sample','observation')];
 if(key.includes('fastening')||key.includes('torque'))return [mk('Torque program','','','batch','recipe'),mk('Applied torque',6.0,'N·m','sample','measurement')];
 if(key==='potting')return [mk('Potting recipe','','','batch','recipe'),mk('Mix ratio','100:12','','batch','machine'),mk('Dispensed mass',12,'g','sample','measurement')];
 if(key==='cure')return [mk('Cure recipe','','','batch','recipe'),mk('Cure temperature',85,'°C','batch','machine'),mk('Cure duration',120,'min','batch','machine')];
 if(key.includes('programming')||key.includes('flashing'))return [mk('Software / flash package','','','batch','recipe'),mk('Programming result','Pass','','sample','observation')];
 if(key==='calibration')return [mk('Calibration procedure / version','','','batch','recipe'),mk('Calibration offset',0,'mV','sample','measurement')];
 if(key==='leak testing')return [mk('Leak-test recipe','','','batch','recipe'),mk('Test pressure',4.0,'bar','batch','machine'),mk('Leak rate',0.3,'sccm','sample','measurement')];
 if(key==='electrical test')return [mk('Test program / version','','','batch','recipe'),mk('Measured output',5.0,'V','sample','measurement')];
 if(key==='dimensional inspection')return [mk('CMM / inspection program','','','batch','recipe')];
 if(key==='optical inspection'||key==='final inspection'||key==='x-ray inspection')return [mk('Inspection method / program','','','batch','recipe'),mk('Inspection result','Pass','','sample','observation')];
 if(key==='functional verification')return [mk('Functional test program','','','batch','recipe'),mk('Functional result','Pass','','sample','observation')];
 if(key==='packaging')return [mk('Packaging specification revision','','','batch','recipe'),mk('Label / pack verification','Pass','','sample','observation')];
 if(key.includes('crimp'))return [mk('Crimp program / tooling setup','','','batch','recipe'),mk('Crimp height',1.4,'mm','sample','measurement')];
 if(key.includes('pressure cycling'))return [mk('Pressure-cycle recipe','','','batch','recipe'),mk('Peak pressure',10,'bar','batch','machine'),mk('Cycles',1000,'cycles','batch','machine')];
 if(key.includes('thermal soak'))return [mk('Thermal profile','','','batch','recipe'),mk('Set temperature',125,'°C','batch','machine'),mk('Soak duration',120,'min','batch','machine')];
 if(key.includes('conformal coat'))return [mk('Coating recipe','','','batch','recipe'),mk('Coating thickness',50,'µm','sample','measurement')];
 return [mk('Process program / setup','','','batch','recipe')];
}
const processes=processNames.map((name,i)=>({
 id:`PROC-${String(i+1).padStart(3,'0')}`,name,family:['Preparation','Assembly','Joining','Programming','Measurement','Inspection'][i%6],revision:String.fromCharCode(65+(i%4)),status:i<25?'Released':i===25?'Under development':i===26?'Under review':'Draft',owner:users[3].name,
 description:`Controlled ${name.toLowerCase()} method for automotive prototype builds.`,setupTime:15+(i%5)*10,cycleTime:5+(i%7)*6,basis:i%3===0?'Batch':'Unit',equipmentCapability:i%4===0?'Precision bench':i%4===1?'Joining cell':i%4===2?'Measurement station':'Assembly station',competency:`COMP-${String((i%8)+1).padStart(2,'0')}`,specialCharacteristics:i%5===0?['pressure','torque','temperature','voltage','force'][i%5]:null,
 params:processParamsForName(name,i),requiredEvidence:['Operator record','Equipment ID',i%4===0?'Measurement result':'Completion confirmation'],workInstruction:{id:`WI-PROC-${String(i+1).padStart(3,'0')}`,revision:'A',title:`Work instruction · ${name}`,status:i<25?'Released':'Draft',steps:[`Verify inputs for ${name}`,`Perform ${name} using controlled parameters`,`Record evidence in the build record`]},revisionHistory:[{rev:'A',status:'Released',date:d(-220+i),note:'Initial release'}],approvals:[{role:'Process Engineer',person:'Noah Visser',date:d(-210+i)}]
}));
processes[5].compatibility={materials:['Stainless 304','Stainless 316'],thickness:[0.5,1.0],geometry:['flat','cylindrical'],leakRequirement:true};
const equipment=[
 ['EQ-001','Laser Welder 1','Joining cell','Valid',d(55)],['EQ-002','Laser Welder 2','Joining cell','Valid',d(19)],['EQ-003','Helium Leak Station','Measurement station','Valid',d(42)],['EQ-004','Pressure Calibrator','Measurement station','Valid',d(8)],['EQ-005','Torque Driver Cell','Assembly station','Valid',d(88)],['EQ-006','CMM 1','Precision bench','Valid',d(63)],['EQ-007','Electrical Bench A','Measurement station','Valid',d(31)],['EQ-008','Electrical Bench B','Measurement station','Expired',d(-2)],['EQ-009','Thermal Chamber 1','Precision bench','Valid',d(76)],['EQ-010','Programming Rig','Assembly station','Valid',d(120)],['EQ-011','Microscope Station','Precision bench','Valid',d(34)],['EQ-012','Potting Cell','Assembly station','Valid',d(101)]
].map(([id,name,capability,calibrationStatus,calibrationDue],i)=>({id,name,capability,status:i===1?'Busy':'Available',calibrationRequired:true,calibrationStatus,calibrationDue,location:'Proto Lab',hourlyCost:45+i*6}));
const staff=users.filter(u=>['lab_planner','process_engineer','technician','quality','metrology','product_safety','lab_manager','approver'].includes(u.role)).map((u,i)=>({id:u.id,name:u.name,role:u.role,available:i!==4,competencies:Array.from({length:5},(_,j)=>`COMP-${String(((i+j)%8)+1).padStart(2,'0')}`),qualification:i%3===0?'Trainer':'Independent'}));
const competencies=[
 {id:'COMP-01',name:'Controlled assembly',owner:'Lucas Vos',description:'Mechanical assembly, fastening and traveller evidence.'},
 {id:'COMP-02',name:'Joining processes',owner:'Noah Visser',description:'Laser/resistance joining setup and controlled parameters.'},
 {id:'COMP-03',name:'Electrical test',owner:'Daan Mulder',description:'Electrical bench setup, measurement and result interpretation.'},
 {id:'COMP-04',name:'Leak & pressure test',owner:'Daan Mulder',description:'Helium leak and pressure measurement methods.'},
 {id:'COMP-05',name:'Dimensional metrology',owner:'Daan Mulder',description:'CMM/dimensional inspection and traceable records.'},
 {id:'COMP-06',name:'Programming / flashing',owner:'Noah Visser',description:'Programming rigs, controlled software revisions and verification.'},
 {id:'COMP-07',name:'Calibration',owner:'Daan Mulder',description:'Calibration benches, reference equipment and traceability.'},
 {id:'COMP-08',name:'Environmental test',owner:'Daan Mulder',description:'Thermal/pressure cycling and environmental characterisation.'}
];
const standardTests=[
 {id:'TST-001',name:'Electrical baseline',aliases:['electrical test','electrical baseline'],revision:'B',status:'Released',owner:'Daan Mulder',setupTime:20,cycleTime:18,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-03',output:'Voltage/current/resistance baseline'},
 {id:'TST-002',name:'Dimensional check',aliases:['dimensional inspection','critical dimension'],revision:'C',status:'Released',owner:'Daan Mulder',setupTime:30,cycleTime:12,basis:'Unit',equipmentCapability:'Precision bench',competency:'COMP-05',output:'Dimensional result set'},
 {id:'TST-003',name:'Leak rate',aliases:['leak test','helium leak'],revision:'D',status:'Released',owner:'Daan Mulder',setupTime:25,cycleTime:15,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-04',output:'Leak rate'},
 {id:'TST-004',name:'Functional verification',aliases:['functional check','functional verification'],revision:'C',status:'Released',owner:'Liam Smit',setupTime:15,cycleTime:20,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-03',output:'Functional pass/fail + signals'},
 {id:'TST-005',name:'Sensitivity',aliases:['sensitivity check','signal sensitivity'],revision:'A',status:'Released',owner:'Daan Mulder',setupTime:25,cycleTime:25,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-07',output:'Sensitivity / linearity'},
 {id:'TST-006',name:'Calibration correlation',aliases:['correlation','calibration correlation'],revision:'B',status:'Released',owner:'Daan Mulder',setupTime:35,cycleTime:25,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-07',output:'Reference correlation'},
 {id:'TST-007',name:'Pressure cycling',aliases:['pressure cycle','pressure cycling'],revision:'A',status:'Released',owner:'Daan Mulder',setupTime:40,cycleTime:35,basis:'Batch',equipmentCapability:'Precision bench',competency:'COMP-08',output:'Cycle response / drift'},
 {id:'TST-008',name:'Thermal soak',aliases:['thermal test','thermal soak'],revision:'B',status:'Released',owner:'Daan Mulder',setupTime:30,cycleTime:60,basis:'Batch',equipmentCapability:'Precision bench',competency:'COMP-08',output:'Temperature response'}
];
const customers=[
 {id:'CUST-INTERNAL',name:'Internal Development',requiredApprovals:['Quality'],specialCharacteristicScheme:['SC','PS'],retention:'R3',safeLaunch:false,productSafetyGate:false,reportPreset:'Internal'},
 {id:'CUST-OEMA',name:'OEM A (Demo)',requiredApprovals:['Quality','Engineering'],specialCharacteristicScheme:['KC','SC'],retention:'R4',safeLaunch:true,productSafetyGate:true,reportPreset:'Customer'},
 {id:'CUST-OEMB',name:'OEM B (Demo)',requiredApprovals:['Quality','Lab Manager'],specialCharacteristicScheme:['CC','PC'],retention:'R5',safeLaunch:false,productSafetyGate:true,reportPreset:'Customer'}
];
const requestScenarios=[
 ['Calibration mule build','PRD-001','CUST-INTERNAL',6,8,'High','READY TO BUILD','Straightforward released-process build'],
 ['Laser weld geometry trial','PRD-005','CUST-OEMA',8,16,'Critical','PROCESS DEFINITION','New process required'],
 ['Adhesive variant B evaluation','PRD-003','CUST-OEMA',4,12,'High','BUILD READINESS REVIEW','Adaptation / Control Plan revision'],
 ['EMC sample set','PRD-006','CUST-OEMB',5,5,'Normal','LAB TRIAGE','Material missing'],
 ['Sensor carrier validation','PRD-007','CUST-OEMA',6,14,'High','READY TO BUILD','Equipment conflict auto-replanned'],
 ['Cold-start characterization','PRD-002','CUST-INTERNAL',3,9,'Normal','BUILD IN PROGRESS','Technician substitution'],
 ['Pressure accuracy correlation','PRD-001','CUST-OEMB',5,6,'High','BUILD READINESS REVIEW','Calibration conflict'],
 ['Safety characteristic prototype','PRD-004','CUST-OEMA',4,11,'Critical','BUILD READINESS REVIEW','Special characteristic missing control'],
 ['Leak margin study','PRD-005','CUST-OEMA',5,4,'High','QUALITY REVIEW','Characterisation failure / quality hold'],
 ['Housing material concession','PRD-003','CUST-INTERNAL',4,7,'Normal','RELEASE APPROVAL','Controlled deviation accepted'],
 ['Connector crimp recovery','PRD-007','CUST-OEMB',4,10,'High','CHARACTERISATION','Rework then reinspection'],
 ['Safety sensor DV sample','PRD-002','CUST-OEMA',6,18,'Critical','ENGINEERING REVIEW','Product safety approval required'],
 ['Late configuration update','PRD-006','CUST-INTERNAL',3,15,'High','FEASIBILITY','Engineering change after submission'],
 ['Delivered traceability demo','PRD-001','CUST-OEMA',5,-3,'Normal','DELIVERED','Delivered fully traceable build'],
 ['Pilot signal conditioner lot','PRD-008','CUST-INTERNAL',8,22,'Normal','SUBMITTED','New product configuration'],
 ['Archived pressure DV batch','PRD-001','CUST-OEMA',8,-52,'Normal','CLOSED','Completed archived validation build with approved report'],
 ['Archived current sensor correlation','PRD-002','CUST-INTERNAL',6,-36,'Normal','CLOSED','Completed correlation build with one reworked unit'],
 ['Archived coolant sensor pilot','PRD-003','CUST-OEMB',10,-24,'High','CLOSED','Completed pilot build with one scrapped unit and documented yield loss']
];
const requests=requestScenarios.map((s,i)=>{
 const [title,productId,customerId,qty,dueOffset,priority,status,scenario]=s; const product=products.find(p=>p.id===productId); const gateIndex=Math.max(0,P.GATES.indexOf(status));
 return {id:`P26-${String(42+i).padStart(4,'0')}`,title,requester:users[i%2].name,engineeringTeam:teams[i%teams.length],customerId,programme:`VP-${String(240+i).padStart(3,'0')}`,vehicleProgramme:i%3===0?'EV Platform X':'Vehicle Programme '+String.fromCharCode(65+i%4),productId,productFamily:product.family,productRevision:product.revision,hardwareRevision:product.hw,softwareRevision:product.sw,maturity:['Concept','A-sample','B-sample','C-sample'][i%4],purpose:['Design validation','Correlation','Customer sample','Process learning'][i%4],quantity:qty,requiredDate:d(dueOffset),forecastDate:d(dueOffset+(i%4===0?2:0)),priority,deliveryLocation:i%2?'Enschede Engineering':'Customer Lab',objective:scenario,configuration:`${product.partNumber}-${product.revision} / Config ${String.fromCharCode(65+i%3)}`,bomRef:`BOM-${product.partNumber}-${product.revision}`,materialOwnership:i%2?'Lab supplied':'Engineering supplied',specialHandling:i%5===0?'ESD + dry storage':'Standard ESD',specialCharacteristics:product.safety?['SC-PRESS-01']:i%3===0?['SC-DIM-02']:[],productSafety:product.safety && i%2===0,characterisation:['Electrical baseline','Dimensional check',i%3===0?'Leak rate':'Functional verification'],status,currentGate:status,risk:i===3||i===7||i===8?'High':i%4===0?'Medium':'Low',owner:i<2?'Mila Jansen':i%3===0?'Noah Visser':'Mila Jansen',submittedAt:gateIndex>0?dt(-20+i):null,createdAt:dt(-28+i),notes:scenario,routeId:`ROUTE-${i+1}`,controlPlanId:`CP-${String((i%8)+1).padStart(3,'0')}`,costEstimate:1100+qty*210+i*75,costActual:i>12?1300+qty*220:null,changeHistory:i===12?[{id:'CHG-013-01',date:dt(-4),type:'Product configuration',from:'Config A',to:'Config B',impact:['External risk review','Control Plan review','Re-characterisation'],status:'Open'}]:[],
 archived:status==='CLOSED',closedAt:status==='CLOSED'?dt(dueOffset+2):null,actualDeliveryDate:['CLOSED','DELIVERED'].includes(status)?d(dueOffset+1):null,
 originalCommitmentDate:['CLOSED','DELIVERED'].includes(status)?d(dueOffset-2):null,currentCommitmentDate:['CLOSED','DELIVERED'].includes(status)?d(dueOffset):null,
 commitmentHistory:['CLOSED','DELIVERED'].includes(status)?[{id:`COM-${i+1}-0`,type:'Original commitment',from:null,to:d(dueOffset-2),daysMoved:0,reasonCategory:'Initial commitment',reason:'Initial lab commitment',timestamp:dt(dueOffset-18),actor:'Mila Jansen'},{id:`COM-${i+1}-1`,type:'Replan',from:d(dueOffset-2),to:d(dueOffset),daysMoved:2,reasonCategory:i===16?'Equipment outage':i===17?'Material delay':'Capacity / congestion',reason:i===16?'Correlation bench outage required a two-day move.':i===17?'Incoming material arrived later than planned.':'Portfolio load required a controlled two-day move.',timestamp:dt(dueOffset-10),actor:'Mila Jansen'}]:[]};
});

requests.forEach((r,i)=>{
  r.batchDataRequirements=[
    {id:'BATCH-SETUP-ID',label:'Fixture / setup ID',unit:'',required:true,includeInBuildReport:true},
    {id:'BATCH-BUILD-OBS',label:'Batch build observation',unit:'',required:false,includeInBuildReport:true}
  ];
  r.sampleDataRequirements=[
    {id:'SAMPLE-FINAL-MASS',label:'Final mass',unit:'g',required:false,includeInBuildReport:true},
    {id:'SAMPLE-VISUAL',label:'Visual condition',unit:'',required:true,includeInBuildReport:true}
  ];
  r.photoEvidenceRequirements=[
    {id:'PHOTO-OVERALL',label:'Overall sample',unit:'',required:true,includeInBuildReport:true},
    {id:'PHOTO-LABEL',label:'Label / serial identification',unit:'',required:false,includeInBuildReport:true}
  ];
  if(r.productSafety)r.photoEvidenceRequirements.push({id:'PHOTO-SAFETY',label:'Special-characteristic evidence',unit:'',required:true,includeInBuildReport:true});
});
const routeTemplates=[0,1,2,5,9,13,14,16,19,20,21];
const routes=requests.map((r,i)=>({id:r.routeId,requestId:r.id,revision:'A',steps:routeTemplates.map((idx,j)=>({id:`${r.id}-S${j+1}`,order:j+1,processId:processes[idx].id,name:processes[idx].name,processRevision:processes[idx].revision,type:j===3&&i===1?'new':j===4&&i===2?'modified':'standard',owner:j%3===0?'Liam Smit':j%3===1?'Noah Visser':'Daan Mulder',planned:dt(-1+j,8+(j%8)),status:['CLOSED','DELIVERED'].includes(r.status)?'Complete':j<Math.max(0,P.GATES.indexOf(r.status)-5)?'Complete':j===Math.max(0,P.GATES.indexOf(r.status)-5)?'In progress':'Planned',readiness:(i===6&&j===6)?'blocked':(i===7&&j===7)?'blocked':j<2?'ready':'pending',parallelGroup:(j===6||j===7)&&i%4===0?'P1':null,optional:j===10&&i%2===0})),reworkLoops:i===10?[{fromStep:9,toStep:6,reason:'Crimp pull-force failure',status:'Completed'}]:[]}));
// Force development candidates for scenario 2
routes[1].steps[3].processId='DEV-001'; routes[1].steps[3].name='Laser Weld — New Geometry'; routes[1].steps[3].type='new'; routes[1].steps[3].readiness='blocked';
routes[2].steps[4].name='Adhesive Dispense — Variant B'; routes[2].steps[4].type='modified';
const processDevelopments=[
 {id:'DEV-001',requestId:requests[1].id,name:'Laser Weld — New Geometry',status:'TRIAL',owner:'Noah Visser',libraryCandidate:'PROC-006',fitAssessment:[['Equipment capability','pass'],['Material','pass'],['Thickness','pass'],['Geometry','warn'],['Leak requirement','pass']],conclusion:'ADAPTATION REQUIRED',trials:[{id:'TR-001',date:d(-4),material:'Stainless 304',equipment:'EQ-001',operator:'Noah Visser',parameters:{power:'480 W',speed:'11 mm/s',focus:'0.1 mm'},result:'Leak marginal',observations:'Minor pore at overlap'},{id:'TR-002',date:d(-2),material:'Stainless 304',equipment:'EQ-001',operator:'Noah Visser',parameters:{power:'510 W',speed:'10 mm/s',focus:'0.0 mm'},result:'Pass',observations:'Stable bead; repeatability trial required'}],gates:{need:true,plan:true,trial:true,parameters:true,risk:false,measurement:false,capability:false,controlPlan:false,workInstruction:false,approval:false,release:false}},
 {id:'DEV-002',requestId:requests[14].id,name:'Signal conditioner calibration',status:'DEVELOPMENT PLAN',owner:'Noah Visser',libraryCandidate:'PROC-015',fitAssessment:[['Equipment capability','pass'],['Voltage range','warn'],['Firmware interface','warn']],conclusion:'NEW PROCESS REQUIRED',trials:[],gates:{need:true,plan:true,trial:false,parameters:false,risk:false,measurement:false,capability:false,controlPlan:false,workInstruction:false,approval:false,release:false}},
 {id:'DEV-003',requestId:requests[2].id,name:'Adhesive dispense variant B',status:'RISK REVIEW',owner:'Noah Visser',libraryCandidate:'PROC-005',fitAssessment:[['Equipment capability','pass'],['Material','warn'],['Geometry','pass'],['Cure profile','warn']],conclusion:'MODIFIED PROCESS REQUIRED',trials:[{id:'TR-003',date:d(-8),material:'Adhesive B',equipment:'EQ-012',operator:'Liam Smit',parameters:{mass:'1.8 g',speed:'12 mm/s'},result:'Pass',observations:'Need 2h cure verification'}],gates:{need:true,plan:true,trial:true,parameters:true,risk:true,measurement:true,capability:true,controlPlan:false,workInstruction:false,approval:false,release:false}}
];
processDevelopments.forEach((x,i)=>x.planningEstimateHours=[14,18,10][i]||12);
const controlPlans=Array.from({length:8},(_,i)=>({id:`CP-${String(i+1).padStart(3,'0')}`,name:`${products[i%products.length].family} Prototype Control Plan`,revision:i===2?'B':'A',phase:i%3===0?'Prototype':i%3===1?'Pre-launch / Safe Launch':'Prototype',status:i===7?'Draft':i===2?'Review requested':'Approved',owner:'Sofia Bakker',approvedBy:i===7?null:'Nora Dekker',approvedAt:i===7?null:dt(-14+i),requestIds:requests.filter((r,j)=>j%8===i).map(r=>r.id),characteristics:Array.from({length:5},(_,j)=>{const processIds=['PROC-006','PROC-015','PROC-017','PROC-020','PROC-021'],processNamesByCp=['Laser Welding','Calibration','Electrical Test','Functional Verification','Final Inspection'],sampling=['100%','5 samples/batch','100%','20%','First + last'],freq=['Each unit','Per batch','Each unit','Per batch','Per batch'];return {id:`CHAR-${i+1}-${j+1}`,processId:processIds[j],processStep:Number(processIds[j].split('-')[1]),processStepName:processNamesByCp[j],characteristic:['Weld integrity','Calibration offset','Electrical output','Functional result','Final appearance'][j],classification:j===0?'SC':j===1&&i%2===0?'PS':'',target:[0,0,5,'Pass','Class A'][j],lsl:[null,-0.2,4.8,null,null][j],usl:[0.6,0.2,5.2,null,null][j],unit:['mm','mV','V','',''][j],method:['Optical + leak','Calibration bench','Electrical test','Functional test','Visual'][j],equipment:['EQ-011','EQ-004','EQ-007','EQ-007','EQ-011'][j],sampleSize:sampling[j],frequency:freq[j],controlMethod:'Recorded result with limit evaluation',role:j===1?'Metrology':'Technician',reactionPlan:'Hold affected serial or lot; notify Quality; open deviation; disposition before release',evidence:'Guided build result'}})}));
const pfmea=[]; routes.slice(0,8).forEach((route,i)=>route.steps.slice(2,6).forEach((s,j)=>pfmea.push({id:`RISK-${i+1}-${j+1}`,requestId:route.requestId,stepId:s.id,function:`Perform ${s.name.toLowerCase()}`,failureMode:['Incorrect parameter','Contamination','Incomplete joint','Wrong component'][j],effect:['Performance drift','Leak / contamination','Mechanical failure','Incorrect function'][j],cause:['Setup error','Handling','Parameter variation','Material mix-up'][j],preventionControl:'Released work instruction + competency',detectionControl:'Control Plan characteristic / inspection',severity:6+j,occurrence:2+(i%3),detection:2+j,specialCharacteristic:j===2,status:(i===7&&j===2)?'Open high risk':'Controlled',recommendedAction:(i===7&&j===2)?'Define direct detection control before readiness':'Monitor',owner:'Noah Visser',evidence:(i===7&&j===2)?'':'CP linkage'})));
const materials=Array.from({length:18},(_,i)=>({id:`MAT-${String(i+1).padStart(3,'0')}`,partNumber:`MAT-${7000+i}`,description:['304 SS housing','Connector insert','ASIC die','PCB assembly','Adhesive cartridge','Potting compound'][i%6],revision:String.fromCharCode(65+i%3),supplier:['Supplier Alpha','Supplier Beta','Internal Stores'][i%3],lot:`LOT-${26}${String(180+i)}`,quantity:20+i*3,received:d(-30+i),status:i===3?'Missing':'Available',certificate:`COC-${100+i}`,specialHandling:i%5===0?'Dry storage':'Standard',expiry:i%5===0?d(40+i):null}));
const allocations=[]; requests.forEach((r,i)=>{ allocations.push({id:`ALLOC-${i+1}-A`,requestId:r.id,materialId:materials[(i+1)%materials.length].id,lot:materials[(i+1)%materials.length].lot,qty:r.quantity,status:i===3?'Pending':'Issued'}); allocations.push({id:`ALLOC-${i+1}-B`,requestId:r.id,materialId:materials[(i+5)%materials.length].id,lot:materials[(i+5)%materials.length].lot,qty:r.quantity,status:'Issued'}); });
const serials=[]; requests.forEach((r,i)=>{ const count=Math.min(r.quantity, i>12?r.quantity:Math.max(2,Math.min(r.quantity,4))); for(let j=1;j<=count;j++) serials.push({id:`SER-${i+1}-${j}`,serial:`${r.id}-${String(j).padStart(3,'0')}`,requestId:r.id,productId:r.productId,configuration:r.configuration,status:r.status==='CLOSED'?(i===16&&j===1?'Reworked':i===17&&j===1?'Scrapped':'Delivered'):i===13?'Delivered':i===8&&j===2?'Hold':i===10&&j===1?'Reworked':'Active',materials:allocations.filter(a=>a.requestId===r.id).map(a=>a.lot),processHistory:routes[i].steps.filter(s=>s.status==='Complete').map(s=>({stepId:s.id,processId:s.processId,revision:s.processRevision,operator:s.owner,equipment:equipment[(j+s.order)%equipment.length].id,date:dt(-5+s.order)})),releaseState:r.status==='CLOSED'?(i===17&&j===1?'Scrapped':'Released'):i===13?'Released':i===8&&j===2?'Hold':'Not released',delivery:['CLOSED','DELIVERED'].includes(r.status)&&!(i===17&&j===1)?{date:r.actualDeliveryDate||d(-3),recipient:r.deliveryLocation||'Vehicle Integration Lab',reference:`DEL-${i+1}-${j}`} : null}); });
const measurements=[]; serials.forEach((s,i)=>{ const req=requests.find(r=>r.id===s.requestId); const cp=controlPlans.find(c=>c.id===req.controlPlanId); (cp?.characteristics||[]).slice(0,3).forEach((c,j)=>{ let value= typeof c.target==='number'?Number(c.target)+( (i+j)%5-2)*0.06 : null; if(req.id===requests[8].id && i%3===1 && j===0) value=0.82; if(req.id===requests[17]?.id && s===serials.find(x=>x.requestId===requests[17].id) && j===2) value=5.45; const pass=value===null?true:(c.lsl===null||value>=c.lsl)&&(c.usl===null||value<=c.usl); measurements.push({id:`MEAS-${i+1}-${j+1}`,requestId:req.id,serial:s.serial,characteristicId:c.id,characteristic:c.characteristic,value,unit:c.unit,lsl:c.lsl,usl:c.usl,target:c.target,method:c.method,equipment:c.equipment,equipmentCalibrationStatus:c.equipment==='EQ-008'?'Invalid':'Valid',calibrationRequired:true,operator:'Liam Smit',timestamp:dt(-2+j,10+j),pass,compliant:c.equipment==='EQ-008'?false:pass,evidence:`REC-${i+1}-${j+1}`}); }); });
const deviations=[
 {id:'DEVN-001',requestId:requests[8].id,serial:serials.find(s=>s.requestId===requests[8].id)?.serial,step:'Leak Testing',measurement:'Leak rate 0.82 > 0.60',type:'Nonconformance',status:'INVESTIGATE',releaseHold:true,containment:'Hold affected serial and sister units',investigation:'Check weld overlap / porosity',disposition:'Pending',approver:'',justification:'',actions:[{text:'Metallographic section',mandatory:true,closed:false}]},
 {id:'DEVN-002',requestId:requests[9].id,serial:serials.find(s=>s.requestId===requests[9].id)?.serial,step:'Material Receipt',measurement:'Housing alloy substitution',type:'Deviation',status:'CLOSED',releaseHold:false,containment:'Segregate substitute material',investigation:'Engineering confirmed equivalent prototype intent',disposition:'Use-as-is',approver:'Sofia Bakker',justification:'Prototype-only concession; no production inference',actions:[{text:'Engineering confirmation',mandatory:true,closed:true}]},
 {id:'DEVN-003',requestId:requests[10].id,serial:serials.find(s=>s.requestId===requests[10].id)?.serial,step:'Connector Crimp',measurement:'Pull force below minimum',type:'Nonconformance',status:'CLOSED',releaseHold:false,containment:'Hold serial',investigation:'Incorrect crimp height',disposition:'Rework',approver:'Sofia Bakker',justification:'Recrimp with new terminal and repeat inspection',actions:[{text:'Reinspection',mandatory:true,closed:true}]},
 {id:'DEVN-004',requestId:requests[17].id,serial:serials.find(s=>s.requestId===requests[17].id)?.serial,step:'Electrical output',measurement:'Electrical output above upper specification',type:'Nonconformance',status:'CLOSED',releaseHold:false,containment:'Segregated affected unit',investigation:'Component variation confirmed on one pilot unit',disposition:'Scrap',approver:'Sofia Bakker',justification:'Unit scrapped; remaining units met specification and were released',actions:[{text:'Verify remaining pilot units',mandatory:true,closed:true}]}
];
const approvals=[]; requests.forEach((r,i)=>{ if(P.GATES.indexOf(r.status)>=5) approvals.push({id:`APR-${i+1}-Q`,requestId:r.id,type:'Build Readiness',role:'Quality Engineer',person:'Sofia Bakker',status:i===7?'Pending':'Approved',timestamp:i===7?null:dt(-6+i%3),comment:i===7?'Special characteristic control unresolved':'Readiness evidence acceptable'}); if(r.productSafety && P.GATES.indexOf(r.status)>=9) approvals.push({id:`APR-${i+1}-PS`,requestId:r.id,type:'Product Safety',role:'Product Safety Representative',person:'Emma Bos',status:i===11?'Pending':'Approved',timestamp:i===11?null:dt(-2),comment:i===11?'Awaiting safety characteristic evidence':'Reviewed'}); });
const bookings=[];
const actions=[
 {id:'ACT-001',requestId:requests[3].id,category:'Needs material',title:'Required connector insert lot is not available',why:'The planned build consumes a material currently marked Missing.',impact:'Forecast slips 2 days unless substitute or expedited material is approved.',owner:'Mila Jansen',due:d(1),severity:'bad',resolve:'materials'},
 {id:'ACT-002',requestId:requests[1].id,category:'Needs process development',title:'Laser weld geometry is outside released process envelope',why:'Library process PROC-006 matches equipment/material but geometry fit is unresolved.',impact:'Build cannot pass Process Definition until development evidence is complete.',owner:'Noah Visser',due:d(2),severity:'warn',resolve:'process'},
 {id:'ACT-003',requestId:requests[7].id,category:'Needs Control Plan review',title:'Safety characteristic has no suitable detection control',why:'External risk analysis identifies a high-risk special characteristic without a linked Control Plan detection method.',impact:'Build Readiness Review is blocked.',owner:'Sofia Bakker',due:d(1),severity:'bad',resolve:'controlplan'},
 {id:'ACT-004',requestId:requests[8].id,category:'Needs quality decision',title:'Leak characterisation failed specification',why:'One serial measured 0.82 mm equivalent against 0.60 upper limit.',impact:'Serial and release are on hold until disposition and verification.',owner:'Sofia Bakker',due:d(0),severity:'bad',resolve:'quality'},
 {id:'ACT-005',requestId:requests[11].id,category:'Needs approval',title:'Product safety review is pending',why:'This build is configured as product-safety relevant.',impact:'Release approval cannot complete until product-safety sign-off.',owner:'Emma Bos',due:d(3),severity:'warn',resolve:'approvals'},
 {id:'ACT-006',requestId:requests[6].id,category:'Needs lab action',title:'Pressure calibrator calibration expires before planned measurement',why:'Calibration due date is before the booked calibration step.',impact:'Planner must use a valid alternative or reschedule after calibration.',owner:'Daan Mulder',due:d(1),severity:'warn',resolve:'equipment'},
 {id:'ACT-007',requestId:requests[14].id,category:'Needs clarification',title:'New product configuration requires interface definition',why:'Prototype signal conditioner has no released programming/calibration interface.',impact:'Feasibility and process development estimate are provisional.',owner:'Eva de Vries',due:d(4),severity:'warn',resolve:'overview'}
];
const auditTrail=[]; requests.forEach((r,i)=>{ auditTrail.push({id:`AUD-${i}-1`,timestamp:r.createdAt,user:r.requester,role:'engineering_requester',action:'Request created',objectType:'Request',objectId:r.id,previousState:'—',newState:'DRAFT REQUEST',reason:r.purpose}); if(r.submittedAt) auditTrail.push({id:`AUD-${i}-2`,timestamp:r.submittedAt,user:r.requester,role:'engineering_requester',action:'Request submitted',objectType:'Request',objectId:r.id,previousState:'DRAFT REQUEST',newState:'SUBMITTED',reason:''}); });
auditTrail.unshift({id:'AUD-CP-1',timestamp:dt(-2),user:'Sofia Bakker',role:'quality',action:'Control Plan approved',objectType:'Control Plan',objectId:'CP-001',previousState:'Review requested',newState:'Approved',reason:'Review complete'});
const lessons=[{id:'LL-001',requestId:requests[13].id,title:'Confirm programming fixture at triage',category:'Planning',observation:'Late fixture confirmation caused avoidable handoff delay.',recommendation:'Add fixture availability check to feasibility gate.',owner:'Mila Jansen',status:'Accepted'}];

const buildHistory=[];
products.forEach((product,pi)=>{
 for(let h=0;h<4;h++){
  const qty=4+h*2, route=P.getDefaultRoute(product.id), factor=.88+((pi+h)%5)*.045;
  const stepActuals=route.map(pid=>{const proc=processes.find(p=>p.id===pid);const std=(Number(proc?.setupTime||15)+Number(proc?.cycleTime||10)*(proc?.basis==='Batch'?1:qty))/60;return {processId:pid,durationHours:Number((std*factor).toFixed(2))};});
  const testActuals=standardTests.slice(0,4).map(test=>{const std=(Number(test.setupTime)+Number(test.cycleTime)*(test.basis==='Batch'?1:qty))/60;return {testId:test.id,durationHours:Number((std*(.9+((pi+h)%4)*.04)).toFixed(2))};});
  buildHistory.push({id:`HIST-${product.id}-${h+1}`,productId:product.id,quantity:qty,completedAt:d(-60-h*35-pi*3),firstPassYield:Number((.91+((pi+h)%4)*.018).toFixed(3)),scrapRate:Number((.01+((pi+h)%3)*.007).toFixed(3)),reworkHours:Number((.8+((pi+h)%4)*.45).toFixed(1)),issues:[['Material delay','Fixture setup','Leak retry','Programming mismatch'][(pi+h)%4]],lessons:[['Reserve exact BOM lots before schedule commit','Use historical median for setup','Confirm test fixture during process definition','Do not plan unreleased process without development allowance'][(pi+h)%4]],stepActuals,testActuals});
 }
});
P.createDemoState=function(){
 const state=P.deepClone({schemaVersion:P.SCHEMA_VERSION,dataVersion:'2026.09-demo-27',identity:{userId:'U03',name:'Mila Jansen',role:'lab_planner'},users,teams,products,processes,equipment,staff,competencies,standardTests,buildHistory,customers,requests,routes,processDevelopments,controlPlans,pfmea,materials,allocations:[],serials,measurements,deviations,approvals,bookings,actions,auditTrail,lessons,documents:[{id:'DOC-001',requestId:requests[13].id,type:'Prototype Build Report',revision:'A',status:'Approved',owner:'Sofia Bakker',effectiveDate:d(-3),approval:'Nora Dekker',supersedes:null}],settings:{separationOfDuties:true,serialPattern:'{REQUEST}-{NNN}',retentionDefault:'R3',safeLaunchDefault:false,demoDataset:true}});
 P.ensureMaterialModel(state);
 // REV 1.0.43: illustrative scope metadata so the Audit Readiness / lab-scope feature is demonstrable.
 const demoScope={
  'EQ-001':['Laser joining / welding','100–1000 W','1 W','See current calibration / validation record','WI-PROC-006'],
  'EQ-002':['Laser joining / welding','100–1000 W','1 W','See current calibration / validation record','WI-PROC-006'],
  'EQ-003':['Helium leak measurement','1e-9–1e-3 mbar·L/s','1e-10 mbar·L/s','See current calibration certificate','Released leak-test method'],
  'EQ-004':['Pressure calibration / measurement','-1 to 20 bar','0.001 bar','See current calibration certificate','Released pressure-calibration method'],
  'EQ-005':['Torque application / verification','0.1–20 N·m','0.01 N·m','See current calibration certificate','Controlled torque work instruction'],
  'EQ-006':['Dimensional measurement','0–500 mm','0.001 mm','See current calibration certificate','CMM dimensional method'],
  'EQ-007':['Electrical measurement','0–30 V / 0–5 A','0.001 V','See current calibration certificate','Released electrical-test method'],
  'EQ-008':['Electrical measurement','0–30 V / 0–5 A','0.001 V','See current calibration certificate','Released electrical-test method'],
  'EQ-009':['Environmental temperature exposure','-40 to 180 °C','0.1 °C','See current calibration certificate','Environmental chamber method'],
  'EQ-010':['Programming / flashing','Controlled interface / software revision','N/A','N/A – functional process resource','Released programming work instruction'],
  'EQ-011':['Optical inspection','Up to 50× magnification','1×','See current verification record','Visual / optical inspection method'],
  'EQ-012':['Potting / dispense process','0.1–100 g dispense','0.1 g','See current verification / calibration record','Released potting work instruction']
 };
 (state.equipment||[]).forEach(e=>{const x=demoScope[e.id];if(x&&!e.scopeSpecification){e.scopeSpecification={activity:x[0],range:x[1],resolution:x[2],uncertainty:x[3],method:x[4],note:'Illustrative demo scope — replace with the organisation-approved equipment specification and uncertainty statement.'};}});
 const demoConsumables={
  'PRD-001':[{id:'BOM-PRD-001-C1',partNumber:'CONS-IPA',description:'Cleaning solvent allocation',revision:'A',qtyPerUnit:5,unit:'mL',kind:'consumable',unitCost:.02,wastePct:10,basis:'unit'}],
  'PRD-003':[{id:'BOM-PRD-003-C1',partNumber:'CONS-ADH-01',description:'Engineering adhesive',revision:'A',qtyPerUnit:3.5,unit:'g',kind:'consumable',unitCost:.18,wastePct:12,basis:'unit'}],
  'PRD-005':[{id:'BOM-PRD-005-C1',partNumber:'CONS-POT-02',description:'Potting compound',revision:'B',qtyPerUnit:18,unit:'g',kind:'consumable',unitCost:.07,wastePct:8,basis:'unit'}]
 };
 Object.entries(demoConsumables).forEach(([pid,items])=>{const p=state.products.find(x=>x.id===pid);if(p&&!p.bom.some(x=>String(x.kind||'').toLowerCase()==='consumable'))p.bom.push(...items);});
 P.ensurePlanningModel(state);P.ensureEnterpriseModel(state);state.requests.forEach(r=>P.syncRequestFlowdown(state,r));
 const demoCostReq=state.requests.find(r=>r.productId==='PRD-005');if(demoCostReq){demoCostReq.consumablesEnabled=true;demoCostReq.buildConsumables=[{id:'BC-DEMO-01',description:'One-off masking / protection',qty:1,basis:'build',unit:'build',unitCost:9.5,wastePct:0}];}
 state.requests.forEach((r,i)=>{
   r.materialOwnership=P.normaliseMaterialSource(r.materialOwnership);
   if(r.materialOwnership==='Engineering supplied')r.materialSupply=r.materialSupply||{owner:r.requester,expectedDate:d(Math.min(5,Math.max(0,P.daysBetween(P.todayISO(),r.requiredDate)-3))),reference:`ENG-SUP-${i+1}`};
   const route=state.routes.find(x=>x.requestId===r.id);if(route){route.confirmed=P.GATES.indexOf(r.status)>=P.GATES.indexOf('PROCESS DEFINITION');route.proposed=!route.confirmed;}
   P.ensureTestRequirements(state,r);
   P.ensureApprovalRecords(state,r);
   (r.materialRequirements||[]).forEach((req,j)=>{
     if(i===3&&j===2)return; // dedicated missing-material scenario
     const mat=state.materials.find(m=>m.partNumber===req.partNumber&&m.revision===req.revision&&m.status==='Available');
     if(mat)state.allocations.push({id:`ALLOC-${i+1}-${j+1}`,requestId:r.id,requirementId:req.id,materialId:mat.id,lot:mat.lot,qty:req.requiredQty,status:'Issued'});
   });
 });
 // Closed demo builds remain searchable in the archive and carry a finalized, approved build report.
 state.requests.filter(r=>r.status==='CLOSED').forEach((r,k)=>{
   r.archived=true;r.closedAt=r.closedAt||r.actualDeliveryDate||P.now();
   const a=P.ensureBuildReportApproval(state,r);a.status='Approved';a.timestamp=r.closedAt;a.approvedAt=r.closedAt;a.comment='Final build report reviewed and approved for archive.';
   if(!state.documents.some(d=>d.requestId===r.id&&d.type==='Prototype Build Report'))state.documents.push({id:`DOC-ARCH-${k+1}`,requestId:r.id,type:'Prototype Build Report',revision:'A',status:'Approved',owner:r.owner||'Mila Jansen',effectiveDate:String(r.closedAt).slice(0,10),approval:a.person,supersedes:null});
 });
 const sampleGroups={};state.serials.forEach(ser=>(sampleGroups[ser.requestId]||(sampleGroups[ser.requestId]=[])).push(ser));for(const [rid,list] of Object.entries(sampleGroups)){const req=state.requests.find(r=>r.id===rid),profile=P.ensureAssuranceProfile(req);list.forEach((ser,i)=>{ser.materials=state.allocations.filter(a=>a.requestId===ser.requestId&&a.status==='Issued').map(a=>a.lot);ser.sampleId=ser.sampleId||ser.serial;ser.sampleNumber=ser.sampleNumber||String(i+1).padStart(2,'0');ser.serialNumber=ser.serialNumber??(profile.requires.serialisation?ser.serial:'');ser.processHistory=ser.processHistory||[];P.ensureSampleEvidence(ser);});}
 state.routes.forEach(route=>(route.steps||[]).forEach(step=>{step.executionRuns=step.executionRuns||[]}));
 state.planningEvents=state.planningEvents||[];
 if(!state.planningEvents.length){state.planningEvents.push({id:'SIT-DEMO-VAC',type:'Vacation',scope:'staff',staffId:state.staff.find(x=>x.role==='technician')?.id||state.staff[0]?.id,equipmentId:null,start:dt(8,8),end:dt(12,17),reason:'Planned annual leave entered as a capacity constraint.',owner:'Mila Jansen',reference:'Demo vacation',active:true,createdAt:P.now()},{id:'SIT-DEMO-EQ',type:'Equipment outage',scope:'equipment',staffId:null,equipmentId:'EQ-003',start:dt(15,8),end:dt(17,17),reason:'Planned diagnostic outage for helium leak station.',owner:'Daan Mulder',reference:'Demo outage',active:true,createdAt:P.now()});}

 // Archived report demonstrator: process / Control Plan / critical-characteristic evidence chain. Legacy risk records remain data-only for migration compatibility.
 const exemplar=state.requests.find(r=>r.title==='Archived pressure DV batch');
 if(exemplar){
   exemplar.assuranceProfile='validation';exemplar.productSafety=true;exemplar.reportExample='Comprehensive build dossier example';exemplar.purpose='Design validation (DV)';exemplar.maturity='C-sample';exemplar.specialCharacteristics=['Weld integrity','Calibration offset','Electrical output','Critical dimension'];exemplar.characterisation=['Leak rate','Electrical baseline','Dimensional check','Functional verification'];exemplar.controlPlanId='CP-ARCH-001';exemplar.buildReportRevision='B';P.ensureTestRequirements(state,exemplar);const exSpecs={'Leak rate':{unit:'mbar·L/s',lsl:0,usl:.60,target:.25},'Electrical baseline':{unit:'V',lsl:4.8,usl:5.2,target:5.0},'Dimensional check':{unit:'mm',lsl:11.8,usl:12.2,target:12.0},'Functional verification':{unit:'',lsl:null,usl:null,target:null}};(exemplar.testRequirements||[]).forEach(t=>{const sp=exSpecs[t.name];if(sp){t.spec=P.deepClone(sp);t.unit=sp.unit;t.lsl=sp.lsl;t.usl=sp.usl;t.target=sp.target;}});exemplar.batchEvidence={dataFields:[{id:'BATCH-EX-FIX',definitionId:'BATCH-SETUP-ID',definitionActive:true,label:'Fixture / setup ID',value:'FIX-PRES-07',unit:'',description:'Dedicated DV pressure fixture; setup verification completed.',includeInBuildReport:true},{id:'BATCH-EX-OBS',definitionId:'BATCH-BUILD-OBS',definitionActive:true,label:'Batch build observation',value:'Stable build after controlled rework on sample 07',unit:'',description:'No further recurrence after connector reseat and repeat calibration.',includeInBuildReport:true}]};exemplar.lessons=['Connector seating check added before calibration to reduce avoidable offset excursions.','Critical-characteristic review confirmed final data within specification; sample 07 remains flagged as an anomaly for engineering learning.'];
   state.controlPlans=state.controlPlans.filter(x=>x.id!=='CP-ARCH-001');
   state.controlPlans.push({id:'CP-ARCH-001',name:'Brake Pressure Sensor DV Build Control Plan',revision:'C',phase:'Prototype DV / customer evidence',status:'Approved',owner:'Sofia Bakker',approvedBy:'Nora Dekker',approvedAt:dt(-58),requestIds:[exemplar.id],characteristics:[
     {id:'ARCH-CHAR-WELD',processStepId:`${exemplar.id}-S4`,processStepName:'Laser Welding',processStep:6,characteristic:'Weld integrity',classification:'PS',target:.30,lsl:.10,usl:.60,unit:'mm',method:'Optical bead assessment + correlated leak equivalent',equipment:'EQ-011',sampleSize:'100%',frequency:'Each unit',controlMethod:'Recorded numeric result + visual evidence',role:'Technician',reactionPlan:'Hold serial; Quality review; rework or scrap before release',evidence:'Measurement + required safety photo'},
     {id:'ARCH-CHAR-OFFSET',processStepId:`${exemplar.id}-S7`,processStepName:'Calibration',processStep:15,characteristic:'Calibration offset',classification:'SC',target:0,lsl:-.20,usl:.20,unit:'mV',method:'Traceable pressure calibration bench',equipment:'EQ-004',sampleSize:'100%',frequency:'Each unit',controlMethod:'Automatic limit evaluation and retained value',role:'Metrology',reactionPlan:'Hold serial; verify connector seating; repeat calibration after approved rework',evidence:'Calibration result record'},
     {id:'ARCH-CHAR-OUTPUT',processStepId:`${exemplar.id}-S8`,processStepName:'Electrical Test',processStep:17,characteristic:'Electrical output',classification:'KC',target:5.0,lsl:4.8,usl:5.2,unit:'V',method:'Electrical bench verification',equipment:'EQ-007',sampleSize:'100%',frequency:'Each unit',controlMethod:'Recorded result with specification evaluation',role:'Technician',reactionPlan:'Hold serial; investigate electrical path before release',evidence:'Electrical test record'},
     {id:'ARCH-CHAR-DIM',processStepId:`${exemplar.id}-S9`,processStepName:'Dimensional Inspection',processStep:18,characteristic:'Critical dimension',classification:'SC',target:12.0,lsl:11.8,usl:12.2,unit:'mm',method:'CMM measurement',equipment:'EQ-006',sampleSize:'100%',frequency:'Each unit',controlMethod:'Recorded traceable dimensional result',role:'Metrology',reactionPlan:'Hold serial; dimensional review and disposition',evidence:'CMM result'}
   ]});
   const eroute=state.routes.find(x=>x.requestId===exemplar.id);if(eroute){const routeIds=['PROC-001','PROC-002','PROC-003','PROC-006','PROC-010','PROC-014','PROC-015','PROC-017','PROC-018','PROC-020','PROC-021','PROC-022'];eroute.revision='C';eroute.confirmed=true;eroute.proposed=false;eroute.steps=routeIds.map((pid,j)=>{const proc=state.processes.find(p=>p.id===pid);return {id:`${exemplar.id}-S${j+1}`,order:j+1,processId:pid,name:proc?.name||pid,processRevision:proc?.revision||'A',type:'standard',owner:j%3===0?'Liam Smit':j%3===1?'Noah Visser':'Daan Mulder',planned:dt(-57+j,8+(j%7)),status:'Complete',readiness:'ready',parallelGroup:null,optional:false,actualDurationHours:Number((.28+(j%5)*.13).toFixed(2)),evidence:`EXEC-${exemplar.id}-S${String(j+1).padStart(2,'0')}`,executionRuns:[{id:`RUN-${exemplar.id}-${j+1}`,startedAt:dt(-56+j,8+(j%7)),completedAt:dt(-56+j,9+(j%7)),operator:j%3===0?'Liam Smit':j%3===1?'Noah Visser':'Daan Mulder',equipmentId:equipment[(j+2)%equipment.length].id,status:'Complete',evidence:`EXEC-${exemplar.id}-S${String(j+1).padStart(2,'0')}`,sampleIds:state.serials.filter(s=>s.requestId===exemplar.id).map(s=>s.serial)}]}})}
   state.pfmea=state.pfmea.filter(x=>x.requestId!==exemplar.id);const pfsteps=eroute?.steps||[];state.pfmea.push(
     {id:'ARCH-RISK-01',requestId:exemplar.id,stepId:pfsteps[3]?.id,function:'Create pressure boundary weld',failureMode:'Incomplete / porous weld',effect:'Pressure leakage or loss of brake pressure signal integrity',cause:'Energy / focus variation or contamination',preventionControl:'Released weld recipe, cleaned components, qualified operator',detectionControl:'100% weld-integrity result plus final leak/functional evidence',severity:9,occurrence:2,detection:2,specialCharacteristic:true,status:'Controlled',recommendedAction:'Trend weld-integrity distribution and investigate flyers',owner:'Noah Visser',evidence:'CP-ARCH-001 · ARCH-CHAR-WELD'},
     {id:'ARCH-RISK-02',requestId:exemplar.id,stepId:pfsteps[6]?.id,function:'Calibrate pressure signal',failureMode:'Offset outside calibration window',effect:'Incorrect pressure indication',cause:'Connector seating / reference setup variation',preventionControl:'Fixture verification and connector seating check',detectionControl:'100% calibration offset against ±0.20 mV specification',severity:9,occurrence:3,detection:2,specialCharacteristic:true,status:'Controlled',recommendedAction:'Retain sample 07 event as lesson and monitor future recurrence',owner:'Daan Mulder',evidence:'CP-ARCH-001 · ARCH-CHAR-OFFSET'},
     {id:'ARCH-RISK-03',requestId:exemplar.id,stepId:pfsteps[7]?.id,function:'Verify electrical output',failureMode:'Output gain / signal outside window',effect:'Invalid sensor output to vehicle controller',cause:'Electronic component or interconnect variation',preventionControl:'Controlled assembly and programming revision',detectionControl:'100% electrical output verification 4.8–5.2 V',severity:8,occurrence:2,detection:2,specialCharacteristic:true,status:'Controlled',recommendedAction:'Continue 100% prototype DV verification',owner:'Noah Visser',evidence:'CP-ARCH-001 · ARCH-CHAR-OUTPUT'},
     {id:'ARCH-RISK-04',requestId:exemplar.id,stepId:pfsteps[8]?.id,function:'Verify critical interface dimension',failureMode:'Interface dimension outside tolerance',effect:'Incorrect mechanical fit / sealing load',cause:'Stack-up or assembly variation',preventionControl:'Released fixtures and dimensional process control',detectionControl:'100% CMM verification 11.8–12.2 mm',severity:7,occurrence:2,detection:2,specialCharacteristic:true,status:'Controlled',recommendedAction:'Maintain CMM verification for DV builds',owner:'Daan Mulder',evidence:'CP-ARCH-001 · ARCH-CHAR-DIM'}
   );
   const esamples=state.serials.filter(s=>s.requestId===exemplar.id).sort((a,b)=>String(a.sampleNumber||a.serial).localeCompare(String(b.sampleNumber||b.serial)));const mass=[42.58,42.61,42.55,42.60,42.57,42.59,42.66,42.60];esamples.forEach((sm,i)=>{P.ensureSampleEvidence(sm);sm.description=`DV pressure-sensor sample ${String(i+1).padStart(2,'0')}. Final visual inspection complete; ${i===6?'connector reseated after first-pass calibration offset excursion; repeat calibration accepted.':'no abnormal workmanship observed.'}`;sm.status=i===6?'Reworked':'Delivered';sm.releaseState='Released';sm.dataFields=[{id:`DF-${sm.serial}-M`,definitionId:'SAMPLE-FINAL-MASS',definitionActive:true,label:'Final mass',value:mass[i].toFixed(2),unit:'g',description:'Final assembled mass',includeInBuildReport:true},{id:`DF-${sm.serial}-V`,definitionId:'SAMPLE-VISUAL',definitionActive:true,label:'Visual condition',value:i===6?'Accept after controlled rework':'Accept',unit:'',description:'Final inspection disposition',includeInBuildReport:true}];sm.evidencePhotos=[{id:`PHOTO-${sm.serial}-1`,slotId:'PHOTO-OVERALL',caption:'Overall sample after final inspection',description:'Demo evidence image illustrating controlled photo placement in the report.',fileName:`${sm.serial}-overall.svg`,fileType:'image/svg+xml',dataUrl:demoEvidenceImage('Overall sample · final inspection',sm.serial,'#0c6670'),capturedAt:dt(-50+i,14),capturedBy:'Liam Smit',includeInBuildReport:true},{id:`PHOTO-${sm.serial}-2`,slotId:'PHOTO-LABEL',caption:'Serial / identification evidence',description:'Demo evidence image for sample identity traceability.',fileName:`${sm.serial}-label.svg`,fileType:'image/svg+xml',dataUrl:demoEvidenceImage('Serial identification',sm.serial,'#3c7fa1'),capturedAt:dt(-50+i,14),capturedBy:'Liam Smit',includeInBuildReport:true},{id:`PHOTO-${sm.serial}-3`,slotId:'PHOTO-SAFETY',caption:'Safety-characteristic weld evidence',description:'Demo evidence image associated with the pressure-boundary weld characteristic.',fileName:`${sm.serial}-safety.svg`,fileType:'image/svg+xml',dataUrl:demoEvidenceImage('Pressure-boundary weld evidence',sm.serial,'#8d3241'),capturedAt:dt(-50+i,15),capturedBy:'Sofia Bakker',includeInBuildReport:true}]});
   state.measurements=state.measurements.filter(m=>m.requestId!==exemplar.id);const vals={
     'ARCH-CHAR-WELD':[.27,.29,.31,.30,.28,.32,.54,.30],
     'ARCH-CHAR-OFFSET':[-.03,.01,.00,.02,-.02,.01,.18,.03],
     'ARCH-CHAR-OUTPUT':[5.01,4.99,5.00,5.02,5.01,4.98,5.03,5.00],
     'ARCH-CHAR-DIM':[12.01,11.99,12.00,12.02,12.01,11.98,12.03,12.00]
   };const cpx=state.controlPlans.find(x=>x.id==='CP-ARCH-001');for(const c of cpx.characteristics){esamples.forEach((sm,i)=>{const value=vals[c.id][i],pass=value>=c.lsl&&value<=c.usl;state.measurements.push({id:`EX-${c.id}-${i+1}`,requestId:exemplar.id,serial:sm.serial,measurementType:'control-plan',routeStepId:c.processStepId,characteristicId:c.id,characteristic:c.characteristic,value,unit:c.unit,lsl:c.lsl,usl:c.usl,target:c.target,method:c.method,equipment:c.equipment,equipmentCalibrationStatus:'Valid',calibrationCertificateId:`CAL-${c.equipment}-DEMO`,calibrationRequired:true,operator:c.role==='Metrology'?'Daan Mulder':'Liam Smit',timestamp:dt(-48+i,10+(i%5)),phase:'Final release',pass,compliant:pass,evidence:`REC-${exemplar.id}-${c.id}-${i+1}`})})}
   const endVals={
     'Leak rate':[.23,.25,.22,.24,.21,.26,.29,.23],
     'Electrical baseline':[5.00,4.99,5.01,5.02,4.98,5.00,5.03,5.01],
     'Dimensional check':[12.00,11.99,12.01,12.02,11.98,12.00,12.03,12.01],
     'Functional verification':['Pass','Pass','Pass','Pass','Pass','Pass','Pass','Pass']
   };const endEq={'Leak rate':'EQ-011','Electrical baseline':'EQ-007','Dimensional check':'EQ-006','Functional verification':'EQ-007'};
   for(const t of (exemplar.testRequirements||[])){const sp=t.spec||{},values=endVals[t.name]||[];esamples.forEach((sm,i)=>{if(i>=values.length)return;const value=values[i],numeric=Number(value),isNum=Number.isFinite(numeric),pass=!isNum?/^pass/i.test(String(value)):(sp.lsl==null||numeric>=sp.lsl)&&(sp.usl==null||numeric<=sp.usl),eq=endEq[t.name]||'EQ-007';state.measurements.push({id:`EX-END-${t.id}-${i+1}`,requestId:exemplar.id,serial:sm.serial,measurementType:'end-characterisation',testRequirementId:t.id,characteristicId:t.id,characteristic:t.name,value,unit:sp.unit||'',lsl:sp.lsl??null,usl:sp.usl??null,target:sp.target??null,method:`${t.name} · released ${t.standardTestId||'engineering method'}`,equipment:eq,equipmentCalibrationStatus:'Valid',calibrationCertificateId:`CAL-${eq}-DEMO`,calibrationRequired:true,operator:t.owner||'Daan Mulder',timestamp:dt(-38+i,9+(i%5)),phase:'End characterisation',pass,compliant:pass,evidence:`END-${exemplar.id}-${t.id}-${i+1}`})})}
   const sm7=esamples[6];state.measurements.push({id:'EX-OFFSET-S07-FIRSTPASS',requestId:exemplar.id,serial:sm7.serial,measurementType:'control-plan',routeStepId:'ARCH-CHAR-OFFSET',characteristicId:'ARCH-CHAR-OFFSET',characteristic:'Calibration offset',value:.27,unit:'mV',lsl:-.20,usl:.20,target:0,method:'Traceable pressure calibration bench',equipment:'EQ-004',equipmentCalibrationStatus:'Valid',calibrationCertificateId:'CAL-EQ-004-DEMO',calibrationRequired:true,operator:'Daan Mulder',timestamp:dt(-49,11),phase:'First pass',pass:false,compliant:false,evidence:'NCR-ARCH-001 · connector seating excursion'});
   state.deviations=state.deviations.filter(d=>d.requestId!==exemplar.id);state.deviations.push({id:'NCR-ARCH-001',requestId:exemplar.id,serial:sm7.serial,step:'Calibration',measurement:'Calibration offset +0.27 mV > +0.20 mV USL on first pass',type:'Nonconformance',status:'CLOSED',releaseHold:false,containment:'Sample 07 held; remaining samples retained under normal build control',investigation:'Connector not fully seated in calibration fixture; no product damage identified',disposition:'Rework',approver:'Sofia Bakker',justification:'Connector reseated, calibration repeated, final result +0.18 mV within specification. Sample retained as statistical flyer for learning.',actions:[{text:'Reseat connector and repeat calibration',mandatory:true,closed:true},{text:'Add connector seating verification to pre-calibration check',mandatory:true,closed:true}]});
   P.ensureApprovalRecords(state,exemplar);(state.approvals||[]).filter(x=>x.requestId===exemplar.id&&x.type!=='Build Report Approval').forEach(x=>{x.status='Approved';x.timestamp=x.timestamp||exemplar.closedAt||dt(-45);x.comment=x.comment||'Archived DV build approval completed.'});const ba=P.ensureBuildReportApproval(state,exemplar);ba.status='Approved';ba.person='Sofia Bakker';ba.role='Quality Engineer';ba.roleId='quality';ba.timestamp=exemplar.closedAt||dt(-45);ba.comment='Comprehensive DV build dossier reviewed: Control Plan, critical-characteristic capability, rework closure, genealogy and photographic evidence accepted.';exemplar.buildReportApprovedAt=ba.timestamp;exemplar.buildReportApprovedBy=ba.person;let bdoc=(state.documents||[]).find(d=>d.requestId===exemplar.id&&d.type==='Prototype Build Report');if(!bdoc){bdoc={id:'DOC-ARCH-COMPREHENSIVE',requestId:exemplar.id,type:'Prototype Build Report',revision:'B',status:'Approved',owner:'Sofia Bakker',effectiveDate:String(exemplar.closedAt||P.todayISO()).slice(0,10),approval:'Sofia Bakker',supersedes:null};state.documents.push(bdoc)}else Object.assign(bdoc,{revision:'B',status:'Approved',owner:'Sofia Bakker',approval:'Sofia Bakker',effectiveDate:String(exemplar.closedAt||P.todayISO()).slice(0,10)});P.syncRequestFlowdown(state,exemplar,{incrementRevision:true});
 }
 // Snapshot the exact measurement evidence approved by each current FINAL Build Report.
 (state.requests||[]).forEach(r=>{const a=P.ensureBuildReportApproval(state,r);r.buildReportEvidenceVersion=Number(r.buildReportEvidenceVersion||1);if(a.status==='Approved'){r.buildReportApprovedEvidenceVersion=r.buildReportEvidenceVersion;r.buildReportApprovedMeasurementFingerprint=P.measurementEvidenceFingerprint(state,r.id);const doc=(state.documents||[]).find(d=>d.requestId===r.id&&d.type==='Prototype Build Report'&&d.status==='Approved'&&String(d.revision||'A')===String(r.buildReportRevision||'A'));if(doc){doc.evidenceVersion=r.buildReportApprovedEvidenceVersion;doc.measurementFingerprint=r.buildReportApprovedMeasurementFingerprint;doc.approvedAt=a.timestamp||doc.approvedAt||r.closedAt||P.now();}}});
 (state.deviations||[]).forEach(d=>P.ensureQualityCase(d));
 return state;
};
})();
