(function(){
'use strict';
const P=window.ProtoLab;
function d(offset){ const x=new Date(); x.setDate(x.getDate()+offset); return x.toISOString().slice(0,10); }
function dt(offset,hour=9){ const x=new Date(); x.setDate(x.getDate()+offset); x.setHours(hour,0,0,0); return x.toISOString(); }
const users=[
 {id:'U01',name:'Eva de Vries',role:'engineering_requester',team:'ADAS Sensors'},{id:'U02',name:'Jonas Meijer',role:'engineering_lead',team:'Powertrain Electronics'},{id:'U03',name:'Mila Jansen',role:'lab_planner',team:'Prototype Lab'},{id:'U04',name:'Noah Visser',role:'process_engineer',team:'Process Engineering'},{id:'U05',name:'Liam Smit',role:'technician',team:'Prototype Lab'},{id:'U06',name:'Sofia Bakker',role:'quality',team:'Quality'},{id:'U07',name:'Daan Mulder',role:'metrology',team:'Metrology'},{id:'U08',name:'Emma Bos',role:'product_safety',team:'Product Safety'},{id:'U09',name:'Lucas Vos',role:'lab_manager',team:'Prototype Lab'},{id:'U10',name:'Nora Dekker',role:'approver',team:'Engineering Excellence'},{id:'U11',name:'Omar Peters',role:'auditor',team:'Internal Audit'},{id:'U12',name:'Amina Kuiper',role:'administrator',team:'Systems'}
];
const teams=['ADAS Sensors','Powertrain Electronics','Thermal Systems','Chassis Controls','Electrification','Advanced Engineering'];
const products=[
 {id:'PRD-001',family:'Brake Pressure Sensor',partNumber:'BPS-3200',revision:'D',hw:'HW4',sw:'3.8.1',safety:true},
 {id:'PRD-002',family:'Battery Current Sensor',partNumber:'BCS-810',revision:'B',hw:'HW2',sw:'2.4.0',safety:true},
 {id:'PRD-003',family:'Coolant Pressure Sensor',partNumber:'CPS-220',revision:'C',hw:'HW3',sw:'—',safety:false},
 {id:'PRD-004',family:'Pedal Position Module',partNumber:'PPM-700',revision:'A',hw:'HW1',sw:'1.2.5',safety:true},
 {id:'PRD-005',family:'Hydrogen Leak Sensor',partNumber:'HLS-900',revision:'B',hw:'HW2',sw:'4.0.2',safety:true},
 {id:'PRD-006',family:'Thermal Valve Controller',partNumber:'TVC-410',revision:'E',hw:'HW5',sw:'5.1.0',safety:false},
 {id:'PRD-007',family:'Steering Torque Sensor',partNumber:'STS-1140',revision:'C',hw:'HW3',sw:'2.9.3',safety:true},
 {id:'PRD-008',family:'Prototype Signal Conditioner',partNumber:'PSC-X2',revision:'P3',hw:'HW-P3',sw:'0.9.8',safety:false}
];
const processNames=['Material Receipt','Incoming Inspection','Cleaning','Surface Preparation','Adhesive Dispense','Laser Welding','Resistance Welding','Soldering','Wire Bonding','Mechanical Assembly','Fastening / Torque','Potting','Cure','Programming / Flashing','Calibration','Leak Testing','Electrical Test','Dimensional Inspection','Optical Inspection','Functional Verification','Final Inspection','Packaging','Connector Crimp','Ultrasonic Cleaning','Pressure Cycling','Thermal Soak','Conformal Coat','X-ray Inspection'];
const processes=processNames.map((name,i)=>({
 id:`PROC-${String(i+1).padStart(3,'0')}`,name,family:['Preparation','Assembly','Joining','Programming','Measurement','Inspection'][i%6],revision:String.fromCharCode(65+(i%4)),status:i<25?'Released':i===25?'Under development':i===26?'Under review':'Draft',owner:users[3].name,
 description:`Controlled ${name.toLowerCase()} method for automotive prototype builds.`,setupTime:15+(i%5)*10,cycleTime:5+(i%7)*6,basis:i%3===0?'Batch':'Unit',equipmentCapability:i%4===0?'Precision bench':i%4===1?'Joining cell':i%4===2?'Measurement station':'Assembly station',competency:`COMP-${String((i%8)+1).padStart(2,'0')}`,specialCharacteristics:i%5===0?['pressure','torque','temperature','voltage','force'][i%5]:null,
 params:[{name:'Primary setpoint',target:10+i,unit:i%2?'N':'bar'},{name:'Tolerance',target:'±5%',unit:''}],requiredEvidence:['Operator record','Equipment ID',i%4===0?'Measurement result':'Completion confirmation'],workInstruction:{id:`WI-PROC-${String(i+1).padStart(3,'0')}`,revision:'A',title:`Work instruction · ${name}`,status:i<25?'Released':'Draft',steps:[`Verify inputs for ${name}`,`Perform ${name} using controlled parameters`,`Record evidence in the build record`]},revisionHistory:[{rev:'A',status:'Released',date:d(-220+i),note:'Initial release'}],approvals:[{role:'Process Engineer',person:'Noah Visser',date:d(-210+i)}]
}));
processes[5].compatibility={materials:['Stainless 304','Stainless 316'],thickness:[0.5,1.0],geometry:['flat','cylindrical'],leakRequirement:true};
const equipment=[
 ['EQ-001','Laser Welder 1','Joining cell','Valid',d(55)],['EQ-002','Laser Welder 2','Joining cell','Valid',d(19)],['EQ-003','Helium Leak Station','Measurement station','Valid',d(42)],['EQ-004','Pressure Calibrator','Measurement station','Valid',d(8)],['EQ-005','Torque Driver Cell','Assembly station','Valid',d(88)],['EQ-006','CMM 1','Precision bench','Valid',d(63)],['EQ-007','Electrical Bench A','Measurement station','Valid',d(31)],['EQ-008','Electrical Bench B','Measurement station','Expired',d(-2)],['EQ-009','Thermal Chamber 1','Precision bench','Valid',d(76)],['EQ-010','Programming Rig','Assembly station','Valid',d(120)],['EQ-011','Microscope Station','Precision bench','Valid',d(34)],['EQ-012','Potting Cell','Assembly station','Valid',d(101)]
].map(([id,name,capability,calibrationStatus,calibrationDue],i)=>({id,name,capability,status:i===1?'Busy':'Available',calibrationRequired:true,calibrationStatus,calibrationDue,location:'Proto Lab',hourlyCost:45+i*6}));
const staff=users.filter(u=>['lab_planner','process_engineer','technician','quality','metrology','product_safety','lab_manager','approver'].includes(u.role)).map((u,i)=>({id:u.id,name:u.name,role:u.role,available:i!==4,competencies:Array.from({length:5},(_,j)=>`COMP-${String(((i+j)%8)+1).padStart(2,'0')}`),qualification:i%3===0?'Trainer':'Independent'}));
const competencies=[
 {id:'COMP-01',name:'Controlled assembly',owner:'Lucas Vos',description:'Mechanical assembly, fastening and traveller evidence.'},
 {id:'COMP-02',name:'Joining processes',owner:'Noah Visser',description:'Laser/resistance joining setup and controlled parameters.'},
 {id:'COMP-03',name:'Electrical test',owner:'Daan Mulder',description:'Electrical bench setup, measurement and result interpretation.'},
 {id:'COMP-04',name:'Leak & pressure test',owner:'Daan Mulder',description:'Helium leak and pressure measurement methods.'},
 {id:'COMP-05',name:'Dimensional metrology',owner:'Daan Mulder',description:'CMM/dimensional inspection and traceable records.'},
 {id:'COMP-06',name:'Programming / flashing',owner:'Noah Visser',description:'Programming rigs, controlled software revisions and verification.'},
 {id:'COMP-07',name:'Calibration',owner:'Daan Mulder',description:'Calibration benches, reference equipment and traceability.'},
 {id:'COMP-08',name:'Environmental test',owner:'Daan Mulder',description:'Thermal/pressure cycling and environmental characterisation.'}
];
const standardTests=[
 {id:'TST-001',name:'Electrical baseline',aliases:['electrical test','electrical baseline'],revision:'B',status:'Released',owner:'Daan Mulder',setupTime:20,cycleTime:18,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-03',output:'Voltage/current/resistance baseline'},
 {id:'TST-002',name:'Dimensional check',aliases:['dimensional inspection','critical dimension'],revision:'C',status:'Released',owner:'Daan Mulder',setupTime:30,cycleTime:12,basis:'Unit',equipmentCapability:'Precision bench',competency:'COMP-05',output:'Dimensional result set'},
 {id:'TST-003',name:'Leak rate',aliases:['leak test','helium leak'],revision:'D',status:'Released',owner:'Daan Mulder',setupTime:25,cycleTime:15,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-04',output:'Leak rate'},
 {id:'TST-004',name:'Functional verification',aliases:['functional check','functional verification'],revision:'C',status:'Released',owner:'Liam Smit',setupTime:15,cycleTime:20,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-03',output:'Functional pass/fail + signals'},
 {id:'TST-005',name:'Sensitivity',aliases:['sensitivity check','signal sensitivity'],revision:'A',status:'Released',owner:'Daan Mulder',setupTime:25,cycleTime:25,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-07',output:'Sensitivity / linearity'},
 {id:'TST-006',name:'Calibration correlation',aliases:['correlation','calibration correlation'],revision:'B',status:'Released',owner:'Daan Mulder',setupTime:35,cycleTime:25,basis:'Unit',equipmentCapability:'Measurement station',competency:'COMP-07',output:'Reference correlation'},
 {id:'TST-007',name:'Pressure cycling',aliases:['pressure cycle','pressure cycling'],revision:'A',status:'Released',owner:'Daan Mulder',setupTime:40,cycleTime:35,basis:'Batch',equipmentCapability:'Precision bench',competency:'COMP-08',output:'Cycle response / drift'},
 {id:'TST-008',name:'Thermal soak',aliases:['thermal test','thermal soak'],revision:'B',status:'Released',owner:'Daan Mulder',setupTime:30,cycleTime:60,basis:'Batch',equipmentCapability:'Precision bench',competency:'COMP-08',output:'Temperature response'}
];
const customers=[
 {id:'CUST-INTERNAL',name:'Internal Development',requiredApprovals:['Quality'],specialCharacteristicScheme:['SC','PS'],retention:'R3',safeLaunch:false,productSafetyGate:false,reportPreset:'Internal'},
 {id:'CUST-OEMA',name:'OEM A (Demo)',requiredApprovals:['Quality','Engineering'],specialCharacteristicScheme:['KC','SC'],retention:'R4',safeLaunch:true,productSafetyGate:true,reportPreset:'Customer'},
 {id:'CUST-OEMB',name:'OEM B (Demo)',requiredApprovals:['Quality','Lab Manager'],specialCharacteristicScheme:['CC','PC'],retention:'R5',safeLaunch:false,productSafetyGate:true,reportPreset:'Customer'}
];
const requestScenarios=[
 ['Calibration mule build','PRD-001','CUST-INTERNAL',6,8,'High','READY TO BUILD','Straightforward released-process build'],
 ['Laser weld geometry trial','PRD-005','CUST-OEMA',8,16,'Critical','PROCESS DEFINITION','New process required'],
 ['Adhesive variant B evaluation','PRD-003','CUST-OEMA',4,12,'High','BUILD READINESS REVIEW','Adaptation / Control Plan revision'],
 ['EMC sample set','PRD-006','CUST-OEMB',5,5,'Normal','LAB TRIAGE','Material missing'],
 ['Sensor carrier validation','PRD-007','CUST-OEMA',6,14,'High','READY TO BUILD','Equipment conflict auto-replanned'],
 ['Cold-start characterization','PRD-002','CUST-INTERNAL',3,9,'Normal','BUILD IN PROGRESS','Technician substitution'],
 ['Pressure accuracy correlation','PRD-001','CUST-OEMB',5,6,'High','BUILD READINESS REVIEW','Calibration conflict'],
 ['Safety characteristic prototype','PRD-004','CUST-OEMA',4,11,'Critical','BUILD READINESS REVIEW','Special characteristic missing control'],
 ['Leak margin study','PRD-005','CUST-OEMA',5,4,'High','QUALITY REVIEW','Characterisation failure / quality hold'],
 ['Housing material concession','PRD-003','CUST-INTERNAL',4,7,'Normal','RELEASE APPROVAL','Controlled deviation accepted'],
 ['Connector crimp recovery','PRD-007','CUST-OEMB',4,10,'High','CHARACTERISATION','Rework then reinspection'],
 ['Safety sensor DV sample','PRD-002','CUST-OEMA',6,18,'Critical','ENGINEERING REVIEW','Product safety approval required'],
 ['Late configuration update','PRD-006','CUST-INTERNAL',3,15,'High','FEASIBILITY','Engineering change after submission'],
 ['Delivered traceability demo','PRD-001','CUST-OEMA',5,-3,'Normal','DELIVERED','Delivered fully traceable build'],
 ['Pilot signal conditioner lot','PRD-008','CUST-INTERNAL',8,22,'Normal','SUBMITTED','New product configuration'],
 ['Archived pressure DV batch','PRD-001','CUST-OEMA',8,-52,'Normal','CLOSED','Completed archived validation build with approved report'],
 ['Archived current sensor correlation','PRD-002','CUST-INTERNAL',6,-36,'Normal','CLOSED','Completed correlation build with one reworked unit'],
 ['Archived coolant sensor pilot','PRD-003','CUST-OEMB',10,-24,'High','CLOSED','Completed pilot build with one scrapped unit and documented yield loss']
];
const requests=requestScenarios.map((s,i)=>{
 const [title,productId,customerId,qty,dueOffset,priority,status,scenario]=s; const product=products.find(p=>p.id===productId); const gateIndex=Math.max(0,P.GATES.indexOf(status));
 return {id:`P26-${String(42+i).padStart(4,'0')}`,title,requester:users[i%2].name,engineeringTeam:teams[i%teams.length],customerId,programme:`VP-${String(240+i).padStart(3,'0')}`,vehicleProgramme:i%3===0?'EV Platform X':'Vehicle Programme '+String.fromCharCode(65+i%4),productId,productFamily:product.family,productRevision:product.revision,hardwareRevision:product.hw,softwareRevision:product.sw,maturity:['Concept','A-sample','B-sample','C-sample'][i%4],purpose:['Design validation','Correlation','Customer sample','Process learning'][i%4],quantity:qty,requiredDate:d(dueOffset),forecastDate:d(dueOffset+(i%4===0?2:0)),priority,deliveryLocation:i%2?'Enschede Engineering':'Customer Lab',objective:scenario,configuration:`${product.partNumber}-${product.revision} / Config ${String.fromCharCode(65+i%3)}`,bomRef:`BOM-${product.partNumber}-${product.revision}`,materialOwnership:i%2?'Lab supplied':'Engineering supplied',specialHandling:i%5===0?'ESD + dry storage':'Standard ESD',specialCharacteristics:product.safety?['SC-PRESS-01']:i%3===0?['SC-DIM-02']:[],productSafety:product.safety && i%2===0,characterisation:['Electrical baseline','Dimensional check',i%3===0?'Leak rate':'Functional verification'],status,currentGate:status,risk:i===3||i===7||i===8?'High':i%4===0?'Medium':'Low',owner:i<2?'Mila Jansen':i%3===0?'Noah Visser':'Mila Jansen',submittedAt:gateIndex>0?dt(-20+i):null,createdAt:dt(-28+i),notes:scenario,routeId:`ROUTE-${i+1}`,controlPlanId:`CP-${String((i%8)+1).padStart(3,'0')}`,costEstimate:1100+qty*210+i*75,costActual:i>12?1300+qty*220:null,changeHistory:i===12?[{id:'CHG-013-01',date:dt(-4),type:'Product configuration',from:'Config A',to:'Config B',impact:['PFMEA review','Control Plan review','Re-characterisation'],status:'Open'}]:[],
 archived:status==='CLOSED',closedAt:status==='CLOSED'?dt(dueOffset+2):null,actualDeliveryDate:['CLOSED','DELIVERED'].includes(status)?d(dueOffset+1):null,
 originalCommitmentDate:['CLOSED','DELIVERED'].includes(status)?d(dueOffset-2):null,currentCommitmentDate:['CLOSED','DELIVERED'].includes(status)?d(dueOffset):null,
 commitmentHistory:['CLOSED','DELIVERED'].includes(status)?[{id:`COM-${i+1}-0`,type:'Original commitment',from:null,to:d(dueOffset-2),daysMoved:0,reasonCategory:'Initial commitment',reason:'Initial lab commitment',timestamp:dt(dueOffset-18),actor:'Mila Jansen'},{id:`COM-${i+1}-1`,type:'Replan',from:d(dueOffset-2),to:d(dueOffset),daysMoved:2,reasonCategory:i===16?'Equipment outage':i===17?'Material delay':'Capacity / congestion',reason:i===16?'Correlation bench outage required a two-day move.':i===17?'Incoming material arrived later than planned.':'Portfolio load required a controlled two-day move.',timestamp:dt(dueOffset-10),actor:'Mila Jansen'}]:[]};
});
const routeTemplates=[0,1,2,5,9,13,14,16,19,20,21];
const routes=requests.map((r,i)=>({id:r.routeId,requestId:r.id,revision:'A',steps:routeTemplates.map((idx,j)=>({id:`${r.id}-S${j+1}`,order:j+1,processId:processes[idx].id,name:processes[idx].name,processRevision:processes[idx].revision,type:j===3&&i===1?'new':j===4&&i===2?'modified':'standard',owner:j%3===0?'Liam Smit':j%3===1?'Noah Visser':'Daan Mulder',planned:dt(-1+j,8+(j%8)),status:['CLOSED','DELIVERED'].includes(r.status)?'Complete':j<Math.max(0,P.GATES.indexOf(r.status)-5)?'Complete':j===Math.max(0,P.GATES.indexOf(r.status)-5)?'In progress':'Planned',readiness:(i===6&&j===6)?'blocked':(i===7&&j===7)?'blocked':j<2?'ready':'pending',parallelGroup:(j===6||j===7)&&i%4===0?'P1':null,optional:j===10&&i%2===0})),reworkLoops:i===10?[{fromStep:9,toStep:6,reason:'Crimp pull-force failure',status:'Completed'}]:[]}));
// Force development candidates for scenario 2
routes[1].steps[3].processId='DEV-001'; routes[1].steps[3].name='Laser Weld — New Geometry'; routes[1].steps[3].type='new'; routes[1].steps[3].readiness='blocked';
routes[2].steps[4].name='Adhesive Dispense — Variant B'; routes[2].steps[4].type='modified';
const processDevelopments=[
 {id:'DEV-001',requestId:requests[1].id,name:'Laser Weld — New Geometry',status:'TRIAL',owner:'Noah Visser',libraryCandidate:'PROC-006',fitAssessment:[['Equipment capability','pass'],['Material','pass'],['Thickness','pass'],['Geometry','warn'],['Leak requirement','pass']],conclusion:'ADAPTATION REQUIRED',trials:[{id:'TR-001',date:d(-4),material:'Stainless 304',equipment:'EQ-001',operator:'Noah Visser',parameters:{power:'480 W',speed:'11 mm/s',focus:'0.1 mm'},result:'Leak marginal',observations:'Minor pore at overlap'},{id:'TR-002',date:d(-2),material:'Stainless 304',equipment:'EQ-001',operator:'Noah Visser',parameters:{power:'510 W',speed:'10 mm/s',focus:'0.0 mm'},result:'Pass',observations:'Stable bead; repeatability trial required'}],gates:{need:true,plan:true,trial:true,parameters:true,risk:false,measurement:false,capability:false,controlPlan:false,workInstruction:false,approval:false,release:false}},
 {id:'DEV-002',requestId:requests[14].id,name:'Signal conditioner calibration',status:'DEVELOPMENT PLAN',owner:'Noah Visser',libraryCandidate:'PROC-015',fitAssessment:[['Equipment capability','pass'],['Voltage range','warn'],['Firmware interface','warn']],conclusion:'NEW PROCESS REQUIRED',trials:[],gates:{need:true,plan:true,trial:false,parameters:false,risk:false,measurement:false,capability:false,controlPlan:false,workInstruction:false,approval:false,release:false}},
 {id:'DEV-003',requestId:requests[2].id,name:'Adhesive dispense variant B',status:'RISK REVIEW',owner:'Noah Visser',libraryCandidate:'PROC-005',fitAssessment:[['Equipment capability','pass'],['Material','warn'],['Geometry','pass'],['Cure profile','warn']],conclusion:'MODIFIED PROCESS REQUIRED',trials:[{id:'TR-003',date:d(-8),material:'Adhesive B',equipment:'EQ-012',operator:'Liam Smit',parameters:{mass:'1.8 g',speed:'12 mm/s'},result:'Pass',observations:'Need 2h cure verification'}],gates:{need:true,plan:true,trial:true,parameters:true,risk:true,measurement:true,capability:true,controlPlan:false,workInstruction:false,approval:false,release:false}}
];
processDevelopments.forEach((x,i)=>x.planningEstimateHours=[14,18,10][i]||12);
const controlPlans=Array.from({length:8},(_,i)=>({id:`CP-${String(i+1).padStart(3,'0')}`,name:`${products[i%products.length].family} Prototype Control Plan`,revision:i===2?'B':'A',phase:i%3===0?'Prototype':i%3===1?'Pre-launch / Safe Launch':'Prototype',status:i===7?'Draft':i===2?'Review requested':'Approved',owner:'Sofia Bakker',approvedBy:i===7?null:'Nora Dekker',approvedAt:i===7?null:dt(-14+i),requestIds:requests.filter((r,j)=>j%8===i).map(r=>r.id),characteristics:Array.from({length:5},(_,j)=>({id:`CHAR-${i+1}-${j+1}`,processStep:[5,14,16,17,20][j],characteristic:['Weld integrity','Calibration offset','Electrical output','Critical dimension','Final appearance'][j],classification:j===0?'SC':j===1&&i%2===0?'PS':'',target:[0,0,5,12,'Class A'][j],lsl:[null,-0.2,4.8,11.8,null][j],usl:[0.6,0.2,5.2,12.2,null][j],unit:['mm','mV','V','mm',''][j],method:['Optical + leak','Calibration bench','Electrical test','CMM','Visual'][j],equipment:['EQ-011','EQ-004','EQ-007','EQ-006','EQ-011'][j],sampleSize:j===0?'100%':'1/unit',frequency:'Each unit',controlMethod:'Recorded result with limit evaluation',role:j===3?'Metrology':'Technician',reactionPlan:'Hold serial; notify Quality; open deviation; disposition before release',evidence:'Guided build result'}))}));
const pfmea=[]; routes.slice(0,8).forEach((route,i)=>route.steps.slice(2,6).forEach((s,j)=>pfmea.push({id:`RISK-${i+1}-${j+1}`,requestId:route.requestId,stepId:s.id,function:`Perform ${s.name.toLowerCase()}`,failureMode:['Incorrect parameter','Contamination','Incomplete joint','Wrong component'][j],effect:['Performance drift','Leak / contamination','Mechanical failure','Incorrect function'][j],cause:['Setup error','Handling','Parameter variation','Material mix-up'][j],preventionControl:'Released work instruction + competency',detectionControl:'Control Plan characteristic / inspection',severity:6+j,occurrence:2+(i%3),detection:2+j,specialCharacteristic:j===2,status:(i===7&&j===2)?'Open high risk':'Controlled',recommendedAction:(i===7&&j===2)?'Define direct detection control before readiness':'Monitor',owner:'Noah Visser',evidence:(i===7&&j===2)?'':'CP linkage'})));
const materials=Array.from({length:18},(_,i)=>({id:`MAT-${String(i+1).padStart(3,'0')}`,partNumber:`MAT-${7000+i}`,description:['304 SS housing','Connector insert','ASIC die','PCB assembly','Adhesive cartridge','Potting compound'][i%6],revision:String.fromCharCode(65+i%3),supplier:['Supplier Alpha','Supplier Beta','Internal Stores'][i%3],lot:`LOT-${26}${String(180+i)}`,quantity:20+i*3,received:d(-30+i),status:i===3?'Missing':'Available',certificate:`COC-${100+i}`,specialHandling:i%5===0?'Dry storage':'Standard',expiry:i%5===0?d(40+i):null}));
const allocations=[]; requests.forEach((r,i)=>{ allocations.push({id:`ALLOC-${i+1}-A`,requestId:r.id,materialId:materials[(i+1)%materials.length].id,lot:materials[(i+1)%materials.length].lot,qty:r.quantity,status:i===3?'Pending':'Issued'}); allocations.push({id:`ALLOC-${i+1}-B`,requestId:r.id,materialId:materials[(i+5)%materials.length].id,lot:materials[(i+5)%materials.length].lot,qty:r.quantity,status:'Issued'}); });
const serials=[]; requests.forEach((r,i)=>{ const count=Math.min(r.quantity, i>12?r.quantity:Math.max(2,Math.min(r.quantity,4))); for(let j=1;j<=count;j++) serials.push({id:`SER-${i+1}-${j}`,serial:`${r.id}-${String(j).padStart(3,'0')}`,requestId:r.id,productId:r.productId,configuration:r.configuration,status:r.status==='CLOSED'?(i===16&&j===1?'Reworked':i===17&&j===1?'Scrapped':'Delivered'):i===13?'Delivered':i===8&&j===2?'Hold':i===10&&j===1?'Reworked':'Active',materials:allocations.filter(a=>a.requestId===r.id).map(a=>a.lot),processHistory:routes[i].steps.filter(s=>s.status==='Complete').map(s=>({stepId:s.id,processId:s.processId,revision:s.processRevision,operator:s.owner,equipment:equipment[(j+s.order)%equipment.length].id,date:dt(-5+s.order)})),releaseState:r.status==='CLOSED'?(i===17&&j===1?'Scrapped':'Released'):i===13?'Released':i===8&&j===2?'Hold':'Not released',delivery:['CLOSED','DELIVERED'].includes(r.status)&&!(i===17&&j===1)?{date:r.actualDeliveryDate||d(-3),recipient:r.deliveryLocation||'Vehicle Integration Lab',reference:`DEL-${i+1}-${j}`} : null}); });
const measurements=[]; serials.forEach((s,i)=>{ const req=requests.find(r=>r.id===s.requestId); const cp=controlPlans.find(c=>c.id===req.controlPlanId); (cp?.characteristics||[]).slice(0,3).forEach((c,j)=>{ let value= typeof c.target==='number'?Number(c.target)+( (i+j)%5-2)*0.06 : null; if(req.id===requests[8].id && i%3===1 && j===0) value=0.82; if(req.id===requests[17]?.id && s===serials.find(x=>x.requestId===requests[17].id) && j===2) value=5.45; const pass=value===null?true:(c.lsl===null||value>=c.lsl)&&(c.usl===null||value<=c.usl); measurements.push({id:`MEAS-${i+1}-${j+1}`,requestId:req.id,serial:s.serial,characteristicId:c.id,characteristic:c.characteristic,value,unit:c.unit,lsl:c.lsl,usl:c.usl,target:c.target,method:c.method,equipment:c.equipment,equipmentCalibrationStatus:c.equipment==='EQ-008'?'Invalid':'Valid',calibrationRequired:true,operator:'Liam Smit',timestamp:dt(-2+j,10+j),pass,compliant:c.equipment==='EQ-008'?false:pass,evidence:`REC-${i+1}-${j+1}`}); }); });
const deviations=[
 {id:'DEVN-001',requestId:requests[8].id,serial:serials.find(s=>s.requestId===requests[8].id)?.serial,step:'Leak Testing',measurement:'Leak rate 0.82 > 0.60',type:'Nonconformance',status:'INVESTIGATE',releaseHold:true,containment:'Hold affected serial and sister units',investigation:'Check weld overlap / porosity',disposition:'Pending',approver:'',justification:'',actions:[{text:'Metallographic section',mandatory:true,closed:false}]},
 {id:'DEVN-002',requestId:requests[9].id,serial:serials.find(s=>s.requestId===requests[9].id)?.serial,step:'Material Receipt',measurement:'Housing alloy substitution',type:'Deviation',status:'CLOSED',releaseHold:false,containment:'Segregate substitute material',investigation:'Engineering confirmed equivalent prototype intent',disposition:'Use-as-is',approver:'Sofia Bakker',justification:'Prototype-only concession; no production inference',actions:[{text:'Engineering confirmation',mandatory:true,closed:true}]},
 {id:'DEVN-003',requestId:requests[10].id,serial:serials.find(s=>s.requestId===requests[10].id)?.serial,step:'Connector Crimp',measurement:'Pull force below minimum',type:'Nonconformance',status:'CLOSED',releaseHold:false,containment:'Hold serial',investigation:'Incorrect crimp height',disposition:'Rework',approver:'Sofia Bakker',justification:'Recrimp with new terminal and repeat inspection',actions:[{text:'Reinspection',mandatory:true,closed:true}]},
 {id:'DEVN-004',requestId:requests[17].id,serial:serials.find(s=>s.requestId===requests[17].id)?.serial,step:'Electrical output',measurement:'Electrical output above upper specification',type:'Nonconformance',status:'CLOSED',releaseHold:false,containment:'Segregated affected unit',investigation:'Component variation confirmed on one pilot unit',disposition:'Scrap',approver:'Sofia Bakker',justification:'Unit scrapped; remaining units met specification and were released',actions:[{text:'Verify remaining pilot units',mandatory:true,closed:true}]}
];
const approvals=[]; requests.forEach((r,i)=>{ if(P.GATES.indexOf(r.status)>=5) approvals.push({id:`APR-${i+1}-Q`,requestId:r.id,type:'Build Readiness',role:'Quality Engineer',person:'Sofia Bakker',status:i===7?'Pending':'Approved',timestamp:i===7?null:dt(-6+i%3),comment:i===7?'Special characteristic control unresolved':'Readiness evidence acceptable'}); if(r.productSafety && P.GATES.indexOf(r.status)>=9) approvals.push({id:`APR-${i+1}-PS`,requestId:r.id,type:'Product Safety',role:'Product Safety Representative',person:'Emma Bos',status:i===11?'Pending':'Approved',timestamp:i===11?null:dt(-2),comment:i===11?'Awaiting safety characteristic evidence':'Reviewed'}); });
const bookings=[];
const actions=[
 {id:'ACT-001',requestId:requests[3].id,category:'Needs material',title:'Required connector insert lot is not available',why:'The planned build consumes a material currently marked Missing.',impact:'Forecast slips 2 days unless substitute or expedited material is approved.',owner:'Mila Jansen',due:d(1),severity:'bad',resolve:'materials'},
 {id:'ACT-002',requestId:requests[1].id,category:'Needs process development',title:'Laser weld geometry is outside released process envelope',why:'Library process PROC-006 matches equipment/material but geometry fit is unresolved.',impact:'Build cannot pass Process Definition until development evidence is complete.',owner:'Noah Visser',due:d(2),severity:'warn',resolve:'process'},
 {id:'ACT-003',requestId:requests[7].id,category:'Needs Control Plan review',title:'Safety characteristic has no suitable detection control',why:'PFMEA marks a high-risk special characteristic without a linked Control Plan detection method.',impact:'Build Readiness Review is blocked.',owner:'Sofia Bakker',due:d(1),severity:'bad',resolve:'controlplan'},
 {id:'ACT-004',requestId:requests[8].id,category:'Needs quality decision',title:'Leak characterisation failed specification',why:'One serial measured 0.82 mm equivalent against 0.60 upper limit.',impact:'Serial and release are on hold until disposition and verification.',owner:'Sofia Bakker',due:d(0),severity:'bad',resolve:'quality'},
 {id:'ACT-005',requestId:requests[11].id,category:'Needs approval',title:'Product safety review is pending',why:'This build is configured as product-safety relevant.',impact:'Release approval cannot complete until product-safety sign-off.',owner:'Emma Bos',due:d(3),severity:'warn',resolve:'approvals'},
 {id:'ACT-006',requestId:requests[6].id,category:'Needs lab action',title:'Pressure calibrator calibration expires before planned measurement',why:'Calibration due date is before the booked calibration step.',impact:'Planner must use a valid alternative or reschedule after calibration.',owner:'Daan Mulder',due:d(1),severity:'warn',resolve:'equipment'},
 {id:'ACT-007',requestId:requests[14].id,category:'Needs clarification',title:'New product configuration requires interface definition',why:'Prototype signal conditioner has no released programming/calibration interface.',impact:'Feasibility and process development estimate are provisional.',owner:'Eva de Vries',due:d(4),severity:'warn',resolve:'overview'}
];
const auditTrail=[]; requests.forEach((r,i)=>{ auditTrail.push({id:`AUD-${i}-1`,timestamp:r.createdAt,user:r.requester,role:'engineering_requester',action:'Request created',objectType:'Request',objectId:r.id,previousState:'—',newState:'DRAFT REQUEST',reason:r.purpose}); if(r.submittedAt) auditTrail.push({id:`AUD-${i}-2`,timestamp:r.submittedAt,user:r.requester,role:'engineering_requester',action:'Request submitted',objectType:'Request',objectId:r.id,previousState:'DRAFT REQUEST',newState:'SUBMITTED',reason:''}); });
auditTrail.unshift({id:'AUD-CP-1',timestamp:dt(-2),user:'Sofia Bakker',role:'quality',action:'Control Plan approved',objectType:'Control Plan',objectId:'CP-001',previousState:'Review requested',newState:'Approved',reason:'Review complete'});
const lessons=[{id:'LL-001',requestId:requests[13].id,title:'Confirm programming fixture at triage',category:'Planning',observation:'Late fixture confirmation caused avoidable handoff delay.',recommendation:'Add fixture availability check to feasibility gate.',owner:'Mila Jansen',status:'Accepted'}];

const buildHistory=[];
products.forEach((product,pi)=>{
 for(let h=0;h<4;h++){
  const qty=4+h*2, route=P.getDefaultRoute(product.id), factor=.88+((pi+h)%5)*.045;
  const stepActuals=route.map(pid=>{const proc=processes.find(p=>p.id===pid);const std=(Number(proc?.setupTime||15)+Number(proc?.cycleTime||10)*(proc?.basis==='Batch'?1:qty))/60;return {processId:pid,durationHours:Number((std*factor).toFixed(2))};});
  const testActuals=standardTests.slice(0,4).map(test=>{const std=(Number(test.setupTime)+Number(test.cycleTime)*(test.basis==='Batch'?1:qty))/60;return {testId:test.id,durationHours:Number((std*(.9+((pi+h)%4)*.04)).toFixed(2))};});
  buildHistory.push({id:`HIST-${product.id}-${h+1}`,productId:product.id,quantity:qty,completedAt:d(-60-h*35-pi*3),firstPassYield:Number((.91+((pi+h)%4)*.018).toFixed(3)),scrapRate:Number((.01+((pi+h)%3)*.007).toFixed(3)),reworkHours:Number((.8+((pi+h)%4)*.45).toFixed(1)),issues:[['Material delay','Fixture setup','Leak retry','Programming mismatch'][(pi+h)%4]],lessons:[['Reserve exact BOM lots before schedule commit','Use historical median for setup','Confirm test fixture during process definition','Do not plan unreleased process without development allowance'][(pi+h)%4]],stepActuals,testActuals});
 }
});
P.createDemoState=function(){
 const state=P.deepClone({schemaVersion:P.SCHEMA_VERSION,dataVersion:'2026.09-demo-16',identity:{userId:'U03',name:'Mila Jansen',role:'lab_planner'},users,teams,products,processes,equipment,staff,competencies,standardTests,buildHistory,customers,requests,routes,processDevelopments,controlPlans,pfmea,materials,allocations:[],serials,measurements,deviations,approvals,bookings,actions,auditTrail,lessons,documents:[{id:'DOC-001',requestId:requests[13].id,type:'Prototype Build Report',revision:'A',status:'Approved',owner:'Sofia Bakker',effectiveDate:d(-3),approval:'Nora Dekker',supersedes:null}],settings:{separationOfDuties:true,serialPattern:'{REQUEST}-{NNN}',retentionDefault:'R3',safeLaunchDefault:false,demoDataset:true}});
 P.ensureMaterialModel(state);
 const demoConsumables={
  'PRD-001':[{id:'BOM-PRD-001-C1',partNumber:'CONS-IPA',description:'Cleaning solvent allocation',revision:'A',qtyPerUnit:5,unit:'mL',kind:'consumable',unitCost:.02,wastePct:10,basis:'unit'}],
  'PRD-003':[{id:'BOM-PRD-003-C1',partNumber:'CONS-ADH-01',description:'Engineering adhesive',revision:'A',qtyPerUnit:3.5,unit:'g',kind:'consumable',unitCost:.18,wastePct:12,basis:'unit'}],
  'PRD-005':[{id:'BOM-PRD-005-C1',partNumber:'CONS-POT-02',description:'Potting compound',revision:'B',qtyPerUnit:18,unit:'g',kind:'consumable',unitCost:.07,wastePct:8,basis:'unit'}]
 };
 Object.entries(demoConsumables).forEach(([pid,items])=>{const p=state.products.find(x=>x.id===pid);if(p&&!p.bom.some(x=>String(x.kind||'').toLowerCase()==='consumable'))p.bom.push(...items);});
 P.ensurePlanningModel(state);P.ensureEnterpriseModel(state);
 const demoCostReq=state.requests.find(r=>r.productId==='PRD-005');if(demoCostReq){demoCostReq.consumablesEnabled=true;demoCostReq.buildConsumables=[{id:'BC-DEMO-01',description:'One-off masking / protection',qty:1,basis:'build',unit:'build',unitCost:9.5,wastePct:0}];}
 state.requests.forEach((r,i)=>{
   r.materialOwnership=P.normaliseMaterialSource(r.materialOwnership);
   if(r.materialOwnership==='Engineering supplied')r.materialSupply=r.materialSupply||{owner:r.requester,expectedDate:d(Math.min(5,Math.max(0,P.daysBetween(P.todayISO(),r.requiredDate)-3))),reference:`ENG-SUP-${i+1}`};
   const route=state.routes.find(x=>x.requestId===r.id);if(route){route.confirmed=P.GATES.indexOf(r.status)>=P.GATES.indexOf('PROCESS DEFINITION');route.proposed=!route.confirmed;}
   P.ensureTestRequirements(state,r);
   P.ensureApprovalRecords(state,r);
   (r.materialRequirements||[]).forEach((req,j)=>{
     if(i===3&&j===2)return; // dedicated missing-material scenario
     const mat=state.materials.find(m=>m.partNumber===req.partNumber&&m.revision===req.revision&&m.status==='Available');
     if(mat)state.allocations.push({id:`ALLOC-${i+1}-${j+1}`,requestId:r.id,requirementId:req.id,materialId:mat.id,lot:mat.lot,qty:req.requiredQty,status:'Issued'});
   });
 });
 // Closed demo builds remain searchable in the archive and carry a finalized, approved build report.
 state.requests.filter(r=>r.status==='CLOSED').forEach((r,k)=>{
   r.archived=true;r.closedAt=r.closedAt||r.actualDeliveryDate||P.now();
   const a=P.ensureBuildReportApproval(state,r);a.status='Approved';a.timestamp=r.closedAt;a.approvedAt=r.closedAt;a.comment='Final build report reviewed and approved for archive.';
   if(!state.documents.some(d=>d.requestId===r.id&&d.type==='Prototype Build Report'))state.documents.push({id:`DOC-ARCH-${k+1}`,requestId:r.id,type:'Prototype Build Report',revision:'A',status:'Approved',owner:r.owner||'Mila Jansen',effectiveDate:String(r.closedAt).slice(0,10),approval:a.person,supersedes:null});
 });
 const sampleGroups={};state.serials.forEach(ser=>(sampleGroups[ser.requestId]||(sampleGroups[ser.requestId]=[])).push(ser));for(const [rid,list] of Object.entries(sampleGroups)){const req=state.requests.find(r=>r.id===rid),profile=P.ensureAssuranceProfile(req);list.forEach((ser,i)=>{ser.materials=state.allocations.filter(a=>a.requestId===ser.requestId&&a.status==='Issued').map(a=>a.lot);ser.sampleId=ser.sampleId||ser.serial;ser.sampleNumber=ser.sampleNumber||String(i+1).padStart(2,'0');ser.serialNumber=ser.serialNumber??(profile.requires.serialisation?ser.serial:'');ser.processHistory=ser.processHistory||[];P.ensureSampleEvidence(ser);});}
 state.routes.forEach(route=>(route.steps||[]).forEach(step=>{step.executionRuns=step.executionRuns||[]}));
 state.planningEvents=state.planningEvents||[];
 if(!state.planningEvents.length){state.planningEvents.push({id:'SIT-DEMO-VAC',type:'Vacation',scope:'staff',staffId:state.staff.find(x=>x.role==='technician')?.id||state.staff[0]?.id,equipmentId:null,start:dt(8,8),end:dt(12,17),reason:'Planned annual leave entered as a capacity constraint.',owner:'Mila Jansen',reference:'Demo vacation',active:true,createdAt:P.now()},{id:'SIT-DEMO-EQ',type:'Equipment outage',scope:'equipment',staffId:null,equipmentId:'EQ-003',start:dt(15,8),end:dt(17,17),reason:'Planned diagnostic outage for helium leak station.',owner:'Daan Mulder',reference:'Demo outage',active:true,createdAt:P.now()});}
 return state;
};
})();
