/* LabOS REV 1.0.185 — Stage 3 canonical Network / Sister-Lab capability */
(function(P){
'use strict';
if(!P||!P.PlanningEngine||!P.StateTransactionService||!P.PlanCommitService)throw new Error('Stage 3 network requires protected Stage 1 + Stage 2 architecture.');
const clone=v=>P.deepClone?P.deepClone(v):JSON.parse(JSON.stringify(v));
const now=()=>P.now?P.now():new Date().toISOString();
const uid=p=>P.uid?P.uid(p):`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const hist=b=>P.isHistoricalPlanningBooking?.(b)||/complete|completed|actual|done|closed|cancel/i.test(String(b?.status||''));
const roleNorm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'_');
const isAdmin=ctx=>/admin/.test(roleNorm(ctx?.role));
const isPlanner=ctx=>isAdmin(ctx)||/(lab_?manager|lab_?planner|planner|manager)/.test(roleNorm(ctx?.role));
const isoDay=v=>String(v||'').slice(0,10)||null;
const overlap=(a,b,c,d)=>new Date(a)<new Date(d)&&new Date(c)<new Date(b);
function stable(value){
  if(Array.isArray(value))return value.map(stable);
  if(value&&typeof value==='object'){const out={};for(const k of Object.keys(value).sort())out[k]=stable(value[k]);return out}
  return value;
}
function hash(value){const s=JSON.stringify(stable(value));let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return `N3-${(h>>>0).toString(16).padStart(8,'0')}`}
function contextOf(state,ctx=null){return ctx instanceof P.SessionContext?ctx:new P.SessionContext(ctx||P.SessionContext.fromLegacyState(state));}
function registry(state){return new P.ProgrammeRegistry(state)}
function programme(state,id){return registry(state).entity(id)}
function domain(state,id){return registry(state).domain(id)}
function currentSite(state,id){const e=programme(state,id);return e?.executionSiteId||e?.homeSiteId||state.settings?.primaryLabId||null}
function internalLab(state,id){return (state.labs||[]).find(x=>x.id===id&&x.type==='internal'&&x.active!==false)||null}
function statusRow(status,ctx,reason=''){return {status,at:now(),actor:{userId:ctx?.userId||null,displayName:ctx?.displayName||'System',role:ctx?.role||'system',labId:ctx?.labId||null},reason:String(reason||'')}}

class TransferScope{
  constructor({type='programme',programmeId,domain:dom=null,taskIds=[],subflowId=null}={}){if(!programmeId)throw new Error('TransferScope.programmeId is required.');this.type=type==='activity'?'task':type;this.programmeId=programmeId;this.domain=dom||null;this.taskIds=[...new Set((taskIds||[]).filter(Boolean))];this.subflowId=subflowId||null;Object.freeze(this.taskIds);Object.freeze(this)}
  static programme(programmeId,dom=null){return new TransferScope({type:'programme',programmeId,domain:dom})}
  static task(programmeId,taskId,dom=null){return new TransferScope({type:'task',programmeId,domain:dom,taskIds:[taskId]})}
  static subflow(programmeId,subflowId,dom=null){return new TransferScope({type:'subflow',programmeId,domain:dom,subflowId})}
}
function resolveTransferScopeV3(state,input){
  const raw=input instanceof TransferScope?input:new TransferScope(input||{}),dom=raw.domain||domain(state,raw.programmeId);if(!dom)throw new Error(`Programme ${raw.programmeId} was not found.`);
  let taskIds=[...raw.taskIds];
  if(raw.type==='subflow'){
    if(dom==='validation')taskIds=(state.validationActivities||[]).filter(a=>a.programmeId===raw.programmeId&&a.legId===raw.subflowId).map(a=>a.id);
    else{const route=(state.routes||[]).find(r=>r.requestId===raw.programmeId);taskIds=(route?.steps||[]).filter(s=>s.parallelGroup===raw.subflowId||s.id===raw.subflowId).map(s=>s.id)}
    if(!taskIds.length)throw new Error(`Transfer subflow ${raw.subflowId} does not resolve to any planning activity.`);
  }
  if(raw.type==='task'&&!taskIds.length)throw new Error('Task/activity transfer requires at least one stable task id.');
  if(raw.type==='programme')taskIds=[];
  const valid=new Set(dom==='validation'?P.compileValidationPlanningTasksV2(state,raw.programmeId).map(t=>t.id):P.compilePlanningTasksV2(state,raw.programmeId).map(t=>t.id));
  for(const id of taskIds)if(!valid.has(id))throw new Error(`Transfer task ${id} is not part of the canonical planning graph.`);
  return new TransferScope({type:raw.type,programmeId:raw.programmeId,domain:dom,taskIds,subflowId:raw.subflowId});
}

const ACTIVE_ASSIGNMENT=new Set(['Active','Accepted','Committed']);
class SiteAssignmentResolver{
  static records(state){return Array.isArray(state.siteAssignmentsV3)?state.siteAssignmentsV3:[]}
  static active(state,programmeId){return this.records(state).filter(x=>x.programmeId===programmeId&&ACTIVE_ASSIGNMENT.has(x.status||'Active'))}
  static siteForTask(state,programmeId,taskId,{defaultSite=null}={}){const rows=this.active(state,programmeId).filter(x=>x.taskId===taskId).sort((a,b)=>String(b.effectiveAt||b.acceptedAt||'').localeCompare(String(a.effectiveAt||a.acceptedAt||'')));if(rows[0]?.siteId)return rows[0].siteId;const r=(state.requests||[]).find(x=>x.id===programmeId);return r?.taskSiteOverridesV1170?.[taskId]||defaultSite||currentSite(state,programmeId)}
  static legacyOverrides(state,programmeId,{fallback={}}={}){const out={...(fallback||{})};for(const a of this.active(state,programmeId))out[a.taskId]=a.siteId;return out}
  static ensureCollections(state){if(!Array.isArray(state.siteAssignmentsV3))state.siteAssignmentsV3=[];return state.siteAssignmentsV3}
  static assign(state,{programmeId,taskId,siteId,transferRequestId=null,reason='',context=null}={}){if(!programmeId||!taskId||!siteId)throw new Error('SiteAssignment requires programmeId, taskId and siteId.');const ctx=contextOf(state,context),rows=this.ensureCollections(state);for(const x of rows)if(x.programmeId===programmeId&&x.taskId===taskId&&ACTIVE_ASSIGNMENT.has(x.status||'Active'))x.status='Superseded';const rec={id:uid('SITEASSIGN'),programmeId,taskId,siteId,status:'Active',sourceTransferRequestId:transferRequestId,effectiveAt:now(),acceptedBy:ctx.displayName,acceptedByUserId:ctx.userId||null,reason:String(reason||'')};rows.push(rec);const req=(state.requests||[]).find(x=>x.id===programmeId);if(req){req.taskSiteOverridesV1170=req.taskSiteOverridesV1170||{};req.taskSiteOverridesV1170[taskId]=siteId}return rec}
  static release(state,programmeId,taskId,{reason='',context=null}={}){const ctx=contextOf(state,context);let changed=0;for(const x of this.records(state))if(x.programmeId===programmeId&&x.taskId===taskId&&ACTIVE_ASSIGNMENT.has(x.status||'Active')){x.status='Released';x.releasedAt=now();x.releasedBy=ctx.displayName;x.releaseReason=reason;changed++}const req=(state.requests||[]).find(x=>x.id===programmeId);if(req?.taskSiteOverridesV1170)delete req.taskSiteOverridesV1170[taskId];return changed}
  static projectLegacy(state,programmeId){const req=(state.requests||[]).find(x=>x.id===programmeId);if(req)req.taskSiteOverridesV1170=this.legacyOverrides(state,programmeId,{fallback:{}});return req?.taskSiteOverridesV1170||{}}
}

class NetworkLogisticsService{
  static routes(state){return Array.isArray(state.networkRoutesV3)?state.networkRoutesV3:[]}
  static leadDays(state,fromSiteId,toSiteId){if(!fromSiteId||!toSiteId||fromSiteId===toSiteId)return 0;const row=this.routes(state).find(x=>x.active!==false&&x.fromSiteId===fromSiteId&&x.toSiteId===toSiteId);if(row)return Math.max(0,Number(row.leadDays||0));const a=(state.labs||[]).find(x=>x.id===fromSiteId),b=(state.labs||[]).find(x=>x.id===toSiteId);return Math.max(1,Number(a?.transferLeadDays||0),Number(b?.transferLeadDays||0))}
  static cost(state,fromSiteId,toSiteId){const row=this.routes(state).find(x=>x.active!==false&&x.fromSiteId===fromSiteId&&x.toSiteId===toSiteId);return Number(row?.cost||0)}
}

class NetworkReadinessGateway{
  static siteSummary(state,siteId){const eq=(state.equipment||[]).filter(x=>x.siteId===siteId),staff=(state.staff||[]).filter(x=>x.siteId===siteId);return {siteId,equipment:eq.length,operationalEquipment:eq.filter(x=>!P.equipmentOperationalForPlanning||P.equipmentOperationalForPlanning(x)).length,staff:staff.length,availableStaff:staff.filter(x=>x.available!==false).length,closures:(state.planningEvents||[]).filter(e=>e.active!==false&&e.scope==='lab'&&e.siteId===siteId).length}}
  static fingerprint(state,siteId){const eq=(state.equipment||[]).filter(x=>x.siteId===siteId).map(x=>[x.id,x.status,x.capability,x.planningCapability,x.calibrationStatus,x.calibrationDue,x.maintenanceStatus,x.maintenanceDue,x.active!==false]),staff=(state.staff||[]).filter(x=>x.siteId===siteId).map(x=>[x.id,x.role,x.available!==false]),train=(state.trainingCertificates||[]).filter(x=>x.siteId===siteId||staff.some(s=>s[0]===x.staffId)).map(x=>[x.id,x.staffId,x.skillId,x.status,x.validUntil]),cal=(state.calibrationCertificates||[]).filter(x=>x.siteId===siteId||eq.some(e=>e[0]===x.equipmentId)).map(x=>[x.id,x.equipmentId,x.status,x.validUntil]),maint=(state.maintenanceRecords||[]).filter(x=>x.siteId===siteId||eq.some(e=>e[0]===x.equipmentId)).map(x=>[x.id,x.equipmentId,x.status,x.completedAt,x.nextDue]),events=(state.planningEvents||[]).filter(x=>x.active!==false&&(!x.siteId||x.siteId===siteId)).map(x=>[x.id,x.scope,x.siteId,x.equipmentId,x.staffId,x.start,x.end]),bookings=(state.bookings||[]).filter(b=>b.siteId===siteId&&!hist(b)).map(b=>[b.id,b.requestId,b.stepId,b.start,b.end,b.equipmentId,b.staffId,b.locked]);return hash({siteId,eq,staff,train,cal,maint,events,bookings})}
}

class NetworkAuthorizationService{
  static can(state,action,{context=null,fromSiteId=null,toSiteId=null}={}){const ctx=contextOf(state,context);if(isAdmin(ctx))return true;if(!isPlanner(ctx))return false;if(action==='request'||action==='cancel'||action==='close')return !!ctx.labId&&ctx.labId===fromSiteId;if(['review','accept','reject','hold','reserve','release','start','complete','fail'].includes(action))return !!ctx.labId&&ctx.labId===toSiteId;return false}
  static assert(state,action,opts={}){if(!this.can(state,action,opts)){const e=new Error(`Not authorized to ${action} this network transfer from the current laboratory/role.`);e.code='NETWORK_NOT_AUTHORIZED';throw e}return true}
}

function programmeFingerprint(state,scope){const e=programme(state,scope.programmeId);const tasks=scope.domain==='validation'?P.compileValidationPlanningTasksV2(state,scope.programmeId):P.compilePlanningTasksV2(state,scope.programmeId);return hash({programme:{id:e?.id,status:e?.status,requiredDate:e?.requiredDate,homeSiteId:e?.homeSiteId,executionSiteId:e?.executionSiteId,currentCommitmentDate:e?.currentCommitmentDate,originalCommitmentDate:e?.originalCommitmentDate,archived:e?.archived===true},tasks:tasks.map(t=>[t.id,t.kind,t.order,t.predecessorIds,t.sourceStep?.parallelGroup||null]),assignments:SiteAssignmentResolver.active(state,scope.programmeId).map(x=>[x.taskId,x.siteId,x.status])})}
function planningFingerprint(state,siteId){return NetworkReadinessGateway.fingerprint(state,siteId)}
function taskIdsForScope(state,scope){return resolveTransferScopeV3(state,scope).taskIds}
function scopedBookings(state,scope,siteId=null){const ids=new Set(taskIdsForScope(state,scope));return (state.bookings||[]).filter(b=>b.requestId===scope.programmeId&&!hist(b)&&(scope.type==='programme'||ids.has(b.stepId))&&(!siteId||b.siteId===siteId))}
const ACTIVE_RESERVATION=new Set(['SoftHeld','Reserved','Committed']);
function activeNetworkReservationConstraints(state,siteId,{ignoreRequestId=null}={}){
  const rows=[];for(const r of state.networkReservationsV3||[]){if(!ACTIVE_RESERVATION.has(r.status)||r.siteId!==siteId||r.transferRequestId===ignoreRequestId)continue;if(r.expiresAt&&new Date(r.expiresAt)<=new Date())continue;for(const w of r.windows||[]){const base={active:true,start:w.start,end:w.end,siteId,source:'stage3-network-reservation',networkReservationId:r.id,networkTransferRequestId:r.transferRequestId};if(w.equipmentId)rows.push({...base,id:`NRES-EQ-${r.id}-${w.bookingId||w.taskId||rows.length}`,scope:'equipment',equipmentId:w.equipmentId});if(w.staffId)rows.push({...base,id:`NRES-ST-${r.id}-${w.bookingId||w.taskId||rows.length}`,scope:'staff',staffId:w.staffId});if(!w.equipmentId&&!w.staffId)rows.push({...base,id:`NRES-LAB-${r.id}-${w.bookingId||w.taskId||rows.length}`,scope:'lab'});}}
  return rows;
}
function injectNetworkReservationConstraints(state,siteId,opts={}){const rows=activeNetworkReservationConstraints(state,siteId,opts);if(rows.length)state.planningEvents=[...(state.planningEvents||[]),...rows];return rows}

class NetworkProposalService{
  constructor(state,{context=null}={}){this.state=state;this.context=context instanceof P.PlanningContext?context:new P.PlanningContext(context||{})}
  propose(scopeInput,toSiteId,{reason='',expiresHours=24,ignoreReservationRequestId=null}={}){
    const scope=resolveTransferScopeV3(this.state,scopeInput),entity=programme(this.state,scope.programmeId);if(!entity)throw new Error('Programme was not found.');if(!internalLab(this.state,toSiteId))throw new Error('Receiving site must be an active internal laboratory.');const fromSiteId=currentSite(this.state,scope.programmeId);if(toSiteId===fromSiteId&&scope.type==='programme')throw new Error('Choose a different internal laboratory.');
    const candidateState=clone(this.state),reservationConstraints=injectNetworkReservationConstraints(candidateState,toSiteId,{ignoreRequestId:ignoreReservationRequestId});if(scope.type!=='programme')for(const taskId of scope.taskIds)SiteAssignmentResolver.assign(candidateState,{programmeId:scope.programmeId,taskId,siteId:toSiteId,reason:'Network proposal only'});
    let plan;try{const e=new P.PlanningEngine(candidateState);plan=e.plan(scope.programmeId,{siteId:scope.type==='programme'?toSiteId:currentSite(candidateState,scope.programmeId),notBefore:entity.dutAvailableDate||entity.planningNotBefore||null,context:this.context})}catch(error){if(reservationConstraints.length){const e=new Error(`Receiving-lab planning is blocked by active network reservation capacity: ${error.message||error}`);e.code='NETWORK_RESERVATION_CONFLICT';e.cause=error;e.conflicts=reservationConstraints.map(x=>({transferRequestId:x.networkTransferRequestId,reservationId:x.networkReservationId,scope:x.scope,equipmentId:x.equipmentId||null,staffId:x.staffId||null,start:x.start,end:x.end}));throw e}throw error}
    const baseForecast=P.DateSemantics.forecastDate(this.state,scope.programmeId),proposalForecast=P.DateSemantics.forecastDate(plan.state,scope.programmeId)||plan.forecastDate||null,daysRecovered=baseForecast&&proposalForecast?P.daysBetween(proposalForecast,baseForecast):0,commit=P.DateSemantics.commitment(this.state,scope.programmeId),moved=(plan.state.bookings||[]).filter(b=>b.requestId===scope.programmeId&&!hist(b)&&b.siteId===toSiteId&&(scope.type==='programme'||scope.taskIds.includes(b.stepId))).map(b=>({taskId:b.stepId,name:b.stepName,siteId:b.siteId,start:b.start,end:b.end,equipmentId:b.equipmentId||null,staffId:b.staffId||null})),leadDays=scope.type==='programme'?NetworkLogisticsService.leadDays(this.state,fromSiteId,toSiteId):Math.max(0,...scope.taskIds.map(id=>{const t=(scope.domain==='validation'?P.compileValidationPlanningTasksV2(this.state,scope.programmeId):P.compilePlanningTasksV2(this.state,scope.programmeId)).find(x=>x.id===id);const predSites=(t?.predecessorIds||[]).map(pid=>SiteAssignmentResolver.siteForTask(this.state,scope.programmeId,pid,{defaultSite:fromSiteId}));if(!predSites.length)predSites.push(fromSiteId);return Math.max(...predSites.map(ps=>NetworkLogisticsService.leadDays(this.state,ps,toSiteId))) }));
    const createdAt=this.context.asOf||now(),expiresAt=new Date(new Date(createdAt).getTime()+Math.max(1,Number(expiresHours))*3600000).toISOString();return {id:uid('NETPROP'),proposalId:null,scope,programmeId:scope.programmeId,domain:scope.domain,fromSiteId,toSiteId,asOf:this.context.asOf,createdAt,expiresAt,reason:String(reason||''),sourceFingerprint:programmeFingerprint(this.state,scope),planningFingerprint:planningFingerprint(this.state,toSiteId),baselineForecast:baseForecast,proposedForecast:proposalForecast,daysRecovered,baselineCommitment:commit.current||null,commitmentImpact:commit.current&&proposalForecast?P.daysBetween(commit.current,proposalForecast):null,movedTasks:moved,otherProgrammeImpacts:[],transferLeadDays:leadDays,readiness:NetworkReadinessGateway.siteSummary(this.state,toSiteId),capacity:{bookingCount:moved.length,plannedHours:moved.reduce((n,b)=>n+Math.max(.25,(new Date(b.end)-new Date(b.start))/3600000),0)},blockers:[],estimatedInternalCost:NetworkLogisticsService.cost(this.state,fromSiteId,toSiteId),candidate:plan};}
  compare(scopeInput){const scope=resolveTransferScopeV3(this.state,scopeInput),from=currentSite(this.state,scope.programmeId);return {scope,fromSiteId:from,rows:(this.state.labs||[]).filter(l=>l.type==='internal'&&l.active!==false).map(l=>{try{const p=this.propose(scope,l.id);return {...p,ok:true,current:l.id===from,name:l.name||l.id}}catch(e){return {ok:false,siteId:l.id,toSiteId:l.id,name:l.name||l.id,current:l.id===from,code:e.code||'NETWORK_BLOCKED',reason:e.message}}})}}
}

class NetworkDelta{
  constructor({programmeId,scope,toSiteId,transferRequestId,status='Accepted',reason='',context=null}={}){Object.assign(this,{programmeId,scope,toSiteId,transferRequestId,status,reason,context})}
  static apply(state,delta){const e=programme(state,delta.programmeId);if(!e)throw new Error('Programme was not found while applying NetworkDelta.');if(delta.scope.type==='programme')e.executionSiteId=delta.toSiteId;else for(const taskId of delta.scope.taskIds)SiteAssignmentResolver.assign(state,{programmeId:delta.programmeId,taskId,siteId:delta.toSiteId,transferRequestId:delta.transferRequestId,reason:delta.reason,context:delta.context});SiteAssignmentResolver.projectLegacy(state,delta.programmeId);return state}
}

class NetworkRecordAdapter{
  static normalize(x){if(!x)return null;return {id:x.id||null,programmeId:x.programmeId||x.requestId||null,requestId:x.requestId||x.programmeId||null,scope:x.scope||x.transferType||'programme',taskIds:[...(x.taskIds||(x.stepId?[x.stepId]:[]))].filter(Boolean),fromSiteId:x.fromSiteId||x.sourceSiteId||null,toSiteId:x.toSiteId||x.targetSiteId||null,status:x.status||'Unknown',requestedAt:x.requestedAt||x.createdAt||null,acceptedAt:x.acceptedAt||x.appliedAt||null,reason:x.reason||x.rationale||x.receiverDecisionReason||'',plannedHours:Number(x.plannedHours||x.requestedPlannedHours||x.capacity?.plannedHours||0),avoidedExternalCost:Number(x.avoidedExternalCost||0),externalCost:Number(x.externalCost||0),raw:x}}
  static all(state){return (state.networkTransfers||[]).map(x=>this.normalize(x))}
}

class NetworkTransferService{
  constructor(state,{context=null}={}){this.state=state;this.context=contextOf(state,context)}
  _collections(){if(!Array.isArray(this.state.networkTransfers))this.state.networkTransfers=[];if(!Array.isArray(this.state.networkReservationsV3))this.state.networkReservationsV3=[];if(!Array.isArray(this.state.siteAssignmentsV3))this.state.siteAssignmentsV3=[];return this}
  record(id){return (this.state.networkTransfers||[]).find(x=>x.id===id)||null}
  reservations(){return Array.isArray(this.state.networkReservationsV3)?this.state.networkReservationsV3:[]}
  request(scopeInput,toSiteId,{reason='Sister-lab execution requested',proposal=null,expiresHours=24,audit=true}={}){this._collections();const scope=resolveTransferScopeV3(this.state,scopeInput),fromSiteId=currentSite(this.state,scope.programmeId);NetworkAuthorizationService.assert(this.state,'request',{context:this.context,fromSiteId,toSiteId});if((this.state.networkTransfers||[]).some(x=>['Requested','UnderReview'].includes(x.status)&&x.programmeId===scope.programmeId&&x.toSiteId===toSiteId&&JSON.stringify((x.transferScope||{}).taskIds||x.taskIds||[])===JSON.stringify(scope.taskIds)))throw new Error('An equivalent network request is already awaiting a decision.');const p=proposal||new NetworkProposalService(this.state,{context:{asOf:now()}}).propose(scope,toSiteId,{reason,expiresHours}),rec={id:uid('NETREQ'),governanceModel:'stage3-network',programmeId:scope.programmeId,requestId:scope.programmeId,domain:scope.domain,scope:scope.type,transferScope:clone(scope),taskIds:[...scope.taskIds],stepId:scope.taskIds.length===1?scope.taskIds[0]:null,fromSiteId,toSiteId,status:'Requested',reservationStatus:'None',requestedAt:now(),expiresAt:p.expiresAt,requestedBy:this.context.displayName,requestedByUserId:this.context.userId,requestedByRole:this.context.role,reason:String(reason||''),proposalId:p.id,sourceFingerprint:p.sourceFingerprint,planningFingerprint:p.planningFingerprint,baselineForecast:p.baselineForecast,proposedForecast:p.proposedForecast,daysRecovered:p.daysRecovered,baselineCommitment:p.baselineCommitment,commitmentImpact:p.commitmentImpact,transferLeadDays:p.transferLeadDays,movedTasks:clone(p.movedTasks),capacity:clone(p.capacity),statusHistory:[statusRow('Requested',this.context,reason)]};rec.proposedReservationWindows=clone(this._reservationWindows(rec,p));this.state.networkTransfers.push(rec);if(audit)P.AuditService.append(this.state,{entity:{type:'NetworkTransfer',id:rec.id},action:'Network transfer requested',previous:null,next:{status:'Requested',programmeId:rec.programmeId,scope:rec.scope,fromSiteId,toSiteId},reason,context:this.context,correlationId:uid('NETTX'),source:'network'});return rec}
  review(id,{reason='Receiving laboratory opened the request',audit=true}={}){const rec=this.record(id);if(!rec||rec.status!=='Requested')throw new Error('Transfer request is not awaiting review.');NetworkAuthorizationService.assert(this.state,'review',{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});rec.status='UnderReview';rec.statusHistory.push(statusRow('UnderReview',this.context,reason));if(audit)P.AuditService.append(this.state,{entity:{type:'NetworkTransfer',id},action:'Network transfer under review',previous:{status:'Requested'},next:{status:'UnderReview'},reason,context:this.context,source:'network'});return rec}
  _assertPending(rec,{allowExpired=false}={}){if(!rec||!['Requested','UnderReview'].includes(rec.status))throw new Error('This network request is no longer awaiting a decision.');if(!allowExpired&&rec.expiresAt&&new Date(rec.expiresAt)<=new Date()){const e=new Error('Network transfer proposal validity has elapsed; refresh current receiving-lab feasibility before deciding.');e.code='NETWORK_REVALIDATION_REQUIRED';e.expiredProposal=true;e.requestId=rec.id;e.expiresAt=rec.expiresAt;throw e}return rec}
  _assertFresh(rec){const scope=resolveTransferScopeV3(this.state,rec.transferScope||{type:rec.scope,programmeId:rec.programmeId,domain:rec.domain,taskIds:rec.taskIds||[],subflowId:rec.subflowId||null}),source=programmeFingerprint(this.state,scope),plan=planningFingerprint(this.state,rec.toSiteId);if(source!==rec.sourceFingerprint||plan!==rec.planningFingerprint){const e=new Error('Network transfer assumptions changed; revalidation and a fresh receiver decision are required.');e.code='NETWORK_REVALIDATION_REQUIRED';e.current={sourceFingerprint:source,planningFingerprint:plan};e.previous={sourceFingerprint:rec.sourceFingerprint,planningFingerprint:rec.planningFingerprint};throw e}return scope}
  revalidationPreview(id,{reason='Receiver revalidation preview'}={}){const rec=this.record(id);this._assertPending(rec,{allowExpired:true});NetworkAuthorizationService.assert(this.state,'accept',{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});const scope=resolveTransferScopeV3(this.state,rec.transferScope||{type:rec.scope,programmeId:rec.programmeId,domain:rec.domain,taskIds:rec.taskIds||[],subflowId:rec.subflowId||null}),current={sourceFingerprint:programmeFingerprint(this.state,scope),planningFingerprint:planningFingerprint(this.state,rec.toSiteId)};try{const proposal=new NetworkProposalService(this.state,{context:{asOf:now()}}).propose(scope,rec.toSiteId,{reason,ignoreReservationRequestId:id}),windows=this._reservationWindows(rec,proposal),previous={sourceFingerprint:rec.sourceFingerprint,planningFingerprint:rec.planningFingerprint,proposedForecast:rec.proposedForecast||null,transferLeadDays:Number(rec.transferLeadDays||0),plannedHours:Number(rec.capacity?.plannedHours||0),reservationWindows:clone(rec.proposedReservationWindows||[])},next={sourceFingerprint:proposal.sourceFingerprint,planningFingerprint:proposal.planningFingerprint,proposedForecast:proposal.proposedForecast||null,transferLeadDays:Number(proposal.transferLeadDays||0),plannedHours:Number(proposal.capacity?.plannedHours||0),reservationWindows:clone(windows)},changed={source:previous.sourceFingerprint!==current.sourceFingerprint,capacity:previous.planningFingerprint!==current.planningFingerprint,forecast:previous.proposedForecast!==next.proposedForecast,leadDays:previous.transferLeadDays!==next.transferLeadDays,plannedHours:previous.plannedHours!==next.plannedHours,reservationWindows:JSON.stringify(previous.reservationWindows)!==JSON.stringify(next.reservationWindows)};return {ok:true,id,programmeId:rec.programmeId,scope,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId,proposal,windows,previous,next,changed}}catch(error){return {ok:false,id,programmeId:rec.programmeId,scope,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId,code:error.code||'NETWORK_REVALIDATION_BLOCKED',reason:error.message||String(error),error}}}
  refresh(id,{reason='Receiver refreshed stale network proposal for a fresh decision',audit=true}={}){const rec=this.record(id);this._assertPending(rec,{allowExpired:true});NetworkAuthorizationService.assert(this.state,'accept',{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});const preview=this.revalidationPreview(id,{reason});if(!preview.ok){const e=new Error(preview.reason||'The network request is no longer feasible.');e.code=preview.code||'NETWORK_REVALIDATION_BLOCKED';e.preview=preview;throw e}this._assertReservationCollision(rec,preview.windows,id);const p=preview.proposal,prevStatus=rec.status;Object.assign(rec,{status:'UnderReview',proposalId:p.id,expiresAt:p.expiresAt,sourceFingerprint:p.sourceFingerprint,planningFingerprint:p.planningFingerprint,baselineForecast:p.baselineForecast,proposedForecast:p.proposedForecast,daysRecovered:p.daysRecovered,baselineCommitment:p.baselineCommitment,commitmentImpact:p.commitmentImpact,transferLeadDays:p.transferLeadDays,movedTasks:clone(p.movedTasks),capacity:clone(p.capacity),proposedReservationWindows:clone(preview.windows),refreshedAt:now(),refreshedBy:this.context.displayName,refreshedByUserId:this.context.userId});rec.statusHistory=rec.statusHistory||[];rec.statusHistory.push(statusRow('UnderReview',this.context,reason));for(const row of this.reservations())if(row.transferRequestId===id&&['SoftHeld','Reserved'].includes(row.status)){row.windows=clone(preview.windows);row.statusHistory=row.statusHistory||[];row.statusHistory.push(statusRow(row.status,this.context,'Reservation windows refreshed after governed revalidation.'))}if(audit)P.AuditService.append(this.state,{entity:{type:'NetworkTransfer',id},action:'Network transfer proposal revalidated',previous:{status:prevStatus,...preview.previous},next:{status:'UnderReview',...preview.next},reason,context:this.context,correlationId:uid('NETTX'),source:'network'});return rec}
  _reservationWindows(rec,proposal){const scope=resolveTransferScopeV3(this.state,rec.transferScope||{type:rec.scope,programmeId:rec.programmeId,domain:rec.domain,taskIds:rec.taskIds||[],subflowId:rec.subflowId||null}),ids=new Set(scope.taskIds);return (proposal.candidate.state.bookings||[]).filter(b=>b.requestId===scope.programmeId&&!hist(b)&&b.siteId===rec.toSiteId&&(scope.type==='programme'||ids.has(b.stepId))).map(b=>({bookingId:b.id,taskId:b.stepId,start:b.start,end:b.end,equipmentId:b.equipmentId||null,staffId:b.staffId||null}))}
  _assertReservationCollision(rec,windows,ignoreRequestId=null){for(const other of this.reservations().filter(r=>['SoftHeld','Reserved','Committed'].includes(r.status)&&r.transferRequestId!==ignoreRequestId&&(!r.expiresAt||new Date(r.expiresAt)>new Date()))){for(const a of windows)for(const b of other.windows||[])if(overlap(a.start,a.end,b.start,b.end)&&((a.equipmentId&&a.equipmentId===b.equipmentId)||(a.staffId&&a.staffId===b.staffId))){const e=new Error('Receiving-lab capacity is already held/reserved by another network request.');e.code='NETWORK_RESERVATION_COLLISION';e.conflict={transferRequestId:other.transferRequestId,equipmentId:a.equipmentId||null,staffId:a.staffId||null};throw e}}}
  hold(id,{status='SoftHeld',reason='Receiver capacity hold',hours=4,audit=true}={}){const rec=this.record(id);this._assertPending(rec);NetworkAuthorizationService.assert(this.state,'hold',{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});const scope=this._assertFresh(rec),proposal=new NetworkProposalService(this.state,{context:{asOf:now()}}).propose(scope,rec.toSiteId,{reason,ignoreReservationRequestId:id}),freshWindows=this._reservationWindows(rec,proposal),windows=(rec.proposedReservationWindows&&rec.proposedReservationWindows.length)?clone(rec.proposedReservationWindows):freshWindows;this._assertReservationCollision(rec,windows,id);this._collections();let row=this.reservations().find(x=>x.transferRequestId===id&&['SoftHeld','Reserved'].includes(x.status));if(!row){row={id:uid('NETRES'),transferRequestId:id,programmeId:rec.programmeId,siteId:rec.toSiteId,status,createdAt:now(),expiresAt:new Date(Date.now()+Math.max(1,Number(hours))*3600000).toISOString(),windows:clone(windows),statusHistory:[]};this.state.networkReservationsV3.push(row)}else{row.status=status;row.windows=clone(windows);row.expiresAt=new Date(Date.now()+Math.max(1,Number(hours))*3600000).toISOString()}row.statusHistory.push(statusRow(status,this.context,reason));rec.reservationStatus=status;if(audit)P.AuditService.append(this.state,{entity:{type:'NetworkReservation',id:row.id},action:`Network capacity ${status}`,previous:null,next:{transferRequestId:id,status,windows:windows.length},reason,context:this.context,source:'network'});return row}
  reserve(id,opts={}){return this.hold(id,{...opts,status:'Reserved',reason:opts.reason||'Receiver capacity reserved'})}
  releaseReservation(id,{reason='Network capacity released',audit=true}={}){const rec=this.record(id);if(!rec)throw new Error('Network request not found.');NetworkAuthorizationService.assert(this.state,'release',{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});let n=0;for(const row of this.reservations())if(row.transferRequestId===id&&['SoftHeld','Reserved'].includes(row.status)){row.status='Released';row.releasedAt=now();row.statusHistory.push(statusRow('Released',this.context,reason));n++}rec.reservationStatus='Released';if(audit&&n)P.AuditService.append(this.state,{entity:{type:'NetworkTransfer',id},action:'Network capacity released',previous:null,next:{releasedReservations:n},reason,context:this.context,source:'network'});return n}
  accept(id,{reason='Receiving laboratory accepted after live-capacity revalidation',audit=true}={}){const rec=this.record(id);this._assertPending(rec);NetworkAuthorizationService.assert(this.state,'accept',{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});const scope=this._assertFresh(rec);for(const taskId of scope.taskIds){const b=(this.state.bookings||[]).find(x=>x.requestId===scope.programmeId&&x.stepId===taskId&&hist(x));if(b){const e=new Error(`Historically executed activity ${taskId} cannot be transferred.`);e.code='NETWORK_SCOPE_HISTORICAL';throw e}}const proposal=new NetworkProposalService(this.state,{context:{asOf:now()}}).propose(scope,rec.toSiteId,{reason,ignoreReservationRequestId:id}),windows=this._reservationWindows(rec,proposal);this._assertReservationCollision(rec,windows,id);const planningDelta=P.PlanningDelta.fromCandidate(this.state,proposal.candidate,{programmeIds:[scope.programmeId]}),networkDelta=new NetworkDelta({programmeId:scope.programmeId,scope,toSiteId:rec.toSiteId,transferRequestId:id,reason,context:this.context}),simulation=clone(this.state);P.PlanningDelta.apply(simulation,planningDelta);NetworkDelta.apply(simulation,networkDelta);const issues=P.canonicalStateIssues?.(simulation)||P.validateInvariants?.(simulation)||[];if(issues.length){const e=new Error(`Network acceptance rejected: ${issues.slice(0,5).join(' | ')}`);e.code='NETWORK_COMMIT_REJECTED';e.issues=issues;throw e}P.PlanningDelta.apply(this.state,planningDelta);NetworkDelta.apply(this.state,networkDelta);const live=this.record(id);Object.assign(live,{status:'Accepted',acceptedAt:now(),acceptedBy:this.context.displayName,acceptedByUserId:this.context.userId,acceptedByRole:this.context.role,acceptedForecast:P.DateSemantics.forecastDate(this.state,scope.programmeId),reservationStatus:'Committed',sourceFingerprint:programmeFingerprint(this.state,scope),planningFingerprint:planningFingerprint(this.state,rec.toSiteId)});live.statusHistory.push(statusRow('Accepted',this.context,reason));let res=this.reservations().find(x=>x.transferRequestId===id&&['SoftHeld','Reserved'].includes(x.status));if(!res){res={id:uid('NETRES'),transferRequestId:id,programmeId:rec.programmeId,siteId:rec.toSiteId,status:'Committed',createdAt:now(),expiresAt:null,windows:clone(windows),statusHistory:[]};this.state.networkReservationsV3.push(res)}else{res.status='Committed';res.windows=clone(windows);res.expiresAt=null}res.statusHistory.push(statusRow('Committed',this.context,reason));if(audit)P.AuditService.append(this.state,{entity:{type:'NetworkTransfer',id},action:'Network transfer accepted',previous:{status:rec.status},next:{status:'Accepted',programmeId:scope.programmeId,scope,toSiteId:rec.toSiteId,acceptedForecast:live.acceptedForecast},reason,context:this.context,correlationId:uid('NETTX'),source:'network'});return live}
  reject(id,{reason='Receiving laboratory rejected the transfer',audit=true}={}){const rec=this.record(id);this._assertPending(rec,{allowExpired:true});NetworkAuthorizationService.assert(this.state,'reject',{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});const prev=rec.status;rec.status='Rejected';rec.rejectedAt=now();rec.rejectedBy=this.context.displayName;rec.statusHistory.push(statusRow('Rejected',this.context,reason));for(const r of this.reservations())if(r.transferRequestId===id&&['SoftHeld','Reserved'].includes(r.status))r.status='Released';rec.reservationStatus='Released';if(audit)P.AuditService.append(this.state,{entity:{type:'NetworkTransfer',id},action:'Network transfer rejected',previous:{status:prev},next:{status:'Rejected'},reason,context:this.context,source:'network'});return rec}
  cancel(id,{reason='Sending laboratory cancelled the transfer request',audit=true}={}){const rec=this.record(id);this._assertPending(rec,{allowExpired:true});NetworkAuthorizationService.assert(this.state,'cancel',{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});const prev=rec.status;rec.status='Cancelled';rec.cancelledAt=now();rec.cancelledBy=this.context.displayName;rec.statusHistory.push(statusRow('Cancelled',this.context,reason));for(const r of this.reservations())if(r.transferRequestId===id&&['SoftHeld','Reserved'].includes(r.status))r.status='Released';rec.reservationStatus='Released';if(audit)P.AuditService.append(this.state,{entity:{type:'NetworkTransfer',id},action:'Network transfer cancelled',previous:{status:prev},next:{status:'Cancelled'},reason,context:this.context,source:'network'});return rec}
  supersede(id,{reason='Superseded by a newer network request',audit=true}={}){const rec=this.record(id);if(!rec)throw new Error('Network request not found.');NetworkAuthorizationService.assert(this.state,'cancel',{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});const prev=rec.status;rec.status='Superseded';rec.statusHistory=rec.statusHistory||[];rec.statusHistory.push(statusRow('Superseded',this.context,reason));for(const r of this.reservations())if(r.transferRequestId===id&&['SoftHeld','Reserved'].includes(r.status))r.status='Released';if(audit)P.AuditService.append(this.state,{entity:{type:'NetworkTransfer',id},action:'Network transfer superseded',previous:{status:prev},next:{status:'Superseded'},reason,context:this.context,source:'network'});return rec}
  advance(id,status,{reason='',audit=true}={}){const rec=this.record(id);if(!rec)throw new Error('Network request not found.');const allowed={Accepted:['InExecution','Failed'],InExecution:['Completed','Failed'],Completed:['Closed'],Requested:['Expired','Superseded','Cancelled'],UnderReview:['Expired','Superseded','Cancelled']};if(!(allowed[rec.status]||[]).includes(status)){const e=new Error(`Invalid network lifecycle transition ${rec.status} → ${status}.`);e.code='NETWORK_STATUS_INVALID';throw e}const action=status==='InExecution'?'start':status==='Completed'?'complete':status==='Closed'?'close':status==='Failed'?'fail':status==='Cancelled'?'cancel':'review';NetworkAuthorizationService.assert(this.state,action,{context:this.context,fromSiteId:rec.fromSiteId,toSiteId:rec.toSiteId});const prev=rec.status;rec.status=status;rec.statusHistory=rec.statusHistory||[];rec.statusHistory.push(statusRow(status,this.context,reason));rec[`${status.charAt(0).toLowerCase()+status.slice(1)}At`]=now();if(['Closed','Failed','Cancelled','Expired','Superseded'].includes(status)){for(const r of this.reservations())if(r.transferRequestId===id&&r.status!=='Released'){r.status='Released';r.releasedAt=now()}rec.reservationStatus='Released'}if(audit)P.AuditService.append(this.state,{entity:{type:'NetworkTransfer',id},action:`Network transfer ${status}`,previous:{status:prev},next:{status},reason,context:this.context,source:'network'});return rec}
  static async _tx(tx,{action,id=null,reason='',context=null,mutate}){if(!(tx instanceof P.StateTransactionService))throw new Error('Stage-3 network transactions require StateTransactionService.');const ctx=contextOf(tx.state,context||tx.context),correlationId=uid('NETTX');return tx.execute({action,entity:{type:'NetworkTransfer',id:id||'new'},reason,audit:false,context:ctx,source:'network',mutate:async state=>{const svc=new NetworkTransferService(state,{context:ctx}),out=await mutate(svc,state);P.AuditService.append(state,{entity:{type:'NetworkTransfer',id:out?.id||id||'new'},action,previous:null,next:out?{id:out.id,status:out.status,programmeId:out.programmeId||out.requestId}:null,reason,context:ctx,correlationId,source:'network'});return out}})}
  static requestTransaction(tx,scope,toSiteId,opts={}){return this._tx(tx,{action:'Network transfer requested',reason:opts.reason||'',context:opts.context,mutate:svc=>svc.request(scope,toSiteId,{...opts,audit:false})})}
  static reviewTransaction(tx,id,opts={}){return this._tx(tx,{action:'Network transfer under review',id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.review(id,{...opts,audit:false})})}
  static refreshTransaction(tx,id,opts={}){return this._tx(tx,{action:'Network transfer proposal revalidated',id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.refresh(id,{...opts,audit:false})})}
  static acceptTransaction(tx,id,opts={}){return this._tx(tx,{action:'Network transfer accepted',id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.accept(id,{...opts,audit:false})})}
  static rejectTransaction(tx,id,opts={}){return this._tx(tx,{action:'Network transfer rejected',id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.reject(id,{...opts,audit:false})})}
  static cancelTransaction(tx,id,opts={}){return this._tx(tx,{action:'Network transfer cancelled',id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.cancel(id,{...opts,audit:false})})}
  static supersedeTransaction(tx,id,opts={}){return this._tx(tx,{action:'Network transfer superseded',id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.supersede(id,{...opts,audit:false})})}
  static holdTransaction(tx,id,opts={}){return this._tx(tx,{action:'Network capacity soft-held',id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.hold(id,{...opts,audit:false})})}
  static reserveTransaction(tx,id,opts={}){return this._tx(tx,{action:'Network capacity reserved',id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.reserve(id,{...opts,audit:false})})}
  static releaseTransaction(tx,id,opts={}){return this._tx(tx,{action:'Network capacity released',id,reason:opts.reason||'',context:opts.context,mutate:svc=>{svc.releaseReservation(id,{...opts,audit:false});return svc.record(id)}})}
  static advanceTransaction(tx,id,status,opts={}){return this._tx(tx,{action:`Network transfer ${status}`,id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.advance(id,status,{...opts,audit:false})})}
}

class ExternalExecutionRequest{constructor(row={}){Object.assign(this,row)}}
class ExternalOrder{constructor(row={}){Object.assign(this,row)}}
class ExternalExecutionService{
  constructor(state,{context=null}={}){this.state=state;this.context=contextOf(state,context)}
  _ensure(){if(!Array.isArray(this.state.externalExecutionRequestsV3))this.state.externalExecutionRequestsV3=[];if(!Array.isArray(this.state.externalOrdersV3))this.state.externalOrdersV3=[]}
  request(scopeInput,providerId,{quoteReference=null,quoteValidUntil=null,leadDays=null,cost=null,setupCost=0,transportCost=0,reason='',audit=true}={}){this._ensure();const scope=resolveTransferScopeV3(this.state,scopeInput),provider=(this.state.labs||[]).find(x=>x.id===providerId&&x.type==='external'&&x.active!==false);if(!provider)throw new Error('External provider is not configured or active.');const valid=quoteValidUntil?new Date(`${quoteValidUntil}T23:59:59Z`)>new Date():true;if(!valid){const e=new Error('External quote has expired.');e.code='EXTERNAL_QUOTE_EXPIRED';throw e}const rec=new ExternalExecutionRequest({id:uid('EXTREQ'),programmeId:scope.programmeId,scope,providerId,status:'Requested',requestedAt:now(),requestedBy:this.context.displayName,quoteReference,quoteValidUntil,leadDays:Number(leadDays??provider.externalLeadDays??provider.transferLeadDays??10),cost:Number(cost??provider.externalHourlyRate??0),setupCost:Number(setupCost||provider.externalSetupFee||0),transportCost:Number(transportCost||0),reason});this.state.externalExecutionRequestsV3.push(rec);if(audit)P.AuditService.append(this.state,{entity:{type:'ExternalExecutionRequest',id:rec.id},action:'External execution requested',next:rec,reason,context:this.context,source:'external'});return rec}
  approve(id,{poReference=null,reason='Commercial approval',audit=true}={}){this._ensure();const rec=this.state.externalExecutionRequestsV3.find(x=>x.id===id);if(!rec||rec.status!=='Requested')throw new Error('External execution request is not awaiting approval.');if(rec.quoteValidUntil&&new Date(`${rec.quoteValidUntil}T23:59:59Z`)<=new Date()){const e=new Error('External quote has expired.');e.code='EXTERNAL_QUOTE_EXPIRED';throw e}rec.status='Approved';rec.approvedAt=now();rec.approvedBy=this.context.displayName;const order=new ExternalOrder({id:uid('EXTORD'),requestId:id,programmeId:rec.programmeId,providerId:rec.providerId,status:'Ordered',orderedAt:now(),poReference:poReference||null,quoteReference:rec.quoteReference||null,leadDays:rec.leadDays,cost:rec.cost,setupCost:rec.setupCost,transportCost:rec.transportCost,invoiceReference:null,evidence:[]});this.state.externalOrdersV3.push(order);if(audit)P.AuditService.append(this.state,{entity:{type:'ExternalOrder',id:order.id},action:'External execution approved and ordered',previous:{requestStatus:'Requested'},next:{requestStatus:'Approved',orderStatus:'Ordered'},reason,context:this.context,source:'external'});return order}
  static async _tx(tx,{action,id='new',reason='',context=null,mutate}){if(!(tx instanceof P.StateTransactionService))throw new Error('Stage-3 external transactions require StateTransactionService.');const ctx=contextOf(tx.state,context||tx.context),correlationId=uid('EXTTX');return tx.execute({action,entity:{type:'ExternalExecution',id},reason,audit:false,context:ctx,source:'external',mutate:async state=>{const out=await mutate(new ExternalExecutionService(state,{context:ctx}),state);P.AuditService.append(state,{entity:{type:out instanceof ExternalOrder?'ExternalOrder':'ExternalExecutionRequest',id:out?.id||id},action,previous:null,next:out?{id:out.id,status:out.status,programmeId:out.programmeId||null,providerId:out.providerId||null}:null,reason,context:ctx,correlationId,source:'external'});return out}})}
  static async requestTransaction(tx,scope,providerId,opts={}){return this._tx(tx,{action:'External execution requested',reason:opts.reason||'',context:opts.context,mutate:svc=>svc.request(scope,providerId,{...opts,audit:false})})}
  static async approveTransaction(tx,id,opts={}){return this._tx(tx,{action:'External execution approved',id,reason:opts.reason||'',context:opts.context,mutate:svc=>svc.approve(id,{...opts,audit:false})})}
}

class NetworkDecisionService{
  constructor(state,{context=null}={}){this.state=state;this.context=context||{}}
  evaluate(scopeInput){const scope=resolveTransferScopeV3(this.state,scopeInput),entity=programme(this.state,scope.programmeId),current=currentSite(this.state,scope.programmeId),engine=new P.PlanningEngine(this.state);let local=null;try{local=engine.plan(scope.programmeId,{siteId:current,notBefore:entity?.dutAvailableDate||entity?.planningNotBefore||null,context:new P.PlanningContext(this.context)})}catch(e){local={ok:false,error:e.message,code:e.code||'PLANNING_BLOCKED'}}const network=new NetworkProposalService(this.state,{context:this.context}).compare(scope),external=(this.state.labs||[]).filter(x=>x.type==='external'&&x.active!==false).map(x=>({providerId:x.id,name:x.name||x.id,leadDays:Number(x.externalLeadDays||x.transferLeadDays||10),setupCost:Number(x.externalSetupFee||0),hourlyRate:Number(x.externalHourlyRate||0)}));return {scope,localRecovery:local,networkAlternatives:network.rows,externalAlternatives:external,scheduler:'PlanningEngine'}}
}

function networkMetricsStage3(state){
  const rows=NetworkRecordAdapter.all(state),internal=rows.filter(x=>['Accepted','InExecution','Completed','Closed'].includes(x.status)&&x.fromSiteId&&x.toSiteId&&x.fromSiteId!==x.toSiteId),whole=internal.filter(x=>x.scope==='programme'||x.scope==='build'),partial=internal.filter(x=>!whole.includes(x)),ops=partial.reduce((n,x)=>n+Math.max(1,x.taskIds.length),0),historicalExternal=rows.filter(x=>x.status==='External'),orders=(state.externalOrdersV3||[]).filter(x=>['Ordered','InExecution','Completed','Closed'].includes(x.status||'Ordered'));
  return {sisterLabBuilds:whole.length,sisterLabOperations:ops,sisterLabTests:partial.filter(x=>String(x.raw?.taskKind||'').toLowerCase()==='test').reduce((n,x)=>n+Math.max(1,x.taskIds.length),0),sisterLabProcessSteps:partial.filter(x=>String(x.raw?.taskKind||'').toLowerCase()==='process').reduce((n,x)=>n+Math.max(1,x.taskIds.length),0),sisterLabDevelopmentSteps:partial.filter(x=>String(x.raw?.taskKind||'').toLowerCase()==='development').reduce((n,x)=>n+Math.max(1,x.taskIds.length),0),sisterLabCloseoutSteps:partial.filter(x=>String(x.raw?.taskKind||'').toLowerCase()==='closeout').reduce((n,x)=>n+Math.max(1,x.taskIds.length),0),recoveryTransfers:whole.filter(x=>(x.raw?.transferMode||'recovery')==='recovery').length,electiveTransfers:whole.filter(x=>x.raw?.transferMode==='elective').length,internallyRetainedHours:internal.reduce((n,x)=>n+Number(x.plannedHours||0),0),outsourcingAvoided:internal.reduce((n,x)=>n+Number(x.avoidedExternalCost||0),0),externalSpend:historicalExternal.reduce((n,x)=>n+Number(x.externalCost||0),0)+orders.reduce((n,x)=>n+Number(x.cost||0)+Number(x.setupCost||0)+Number(x.transportCost||0),0)}
}

/* Stage-3 legacy API containment. Older exported helpers remain callable by
   historical presentation code, so their effective business behaviour must also be
   governed. They may create/review/decide a request in memory, but they must never
   directly apply an execution-site or task-site transfer. Persistence remains the
   responsibility of the Stage-3 application transaction boundary. */
function legacyContextV3(state,actor=null,labId=null){
  if(actor instanceof P.SessionContext)return actor;
  const base=P.SessionContext.fromLegacyState(state,labId||state?.settings?.activeLabId||state?.settings?.primaryLabId);
  if(!actor)return base;
  return new P.SessionContext({userId:actor.userId||base.userId,displayName:actor.displayName||actor.name||base.displayName,role:actor.role||base.role,labId:actor.labId||labId||base.labId});
}
function governedLegacyRequestV3(state,scope,toSiteId,reason,actor=null){
  try{const context=legacyContextV3(state,actor,currentSite(state,scope.programmeId)),record=new NetworkTransferService(state,{context}).request(scope,toSiteId,{reason:reason||'Governed legacy compatibility request'});return {ok:true,governed:true,pending:true,record,request:record,next:state,error:null}}
  catch(e){return {ok:false,governed:true,pending:false,error:e.message||String(e),code:e.code||'NETWORK_REQUEST_FAILED',next:state}}
}
if(P.MultiLabPlanningV1099){
  const _stage3LegacyCompareSites=P.MultiLabPlanningV1099.compareSites.bind(P.MultiLabPlanningV1099);
  P.MultiLabPlanningV1099.compareSites=function(state,requestId){return _stage3LegacyCompareSites(clone(state),requestId)};
  P.MultiLabPlanningV1099.transferToSite=function(state,requestId,toSiteId,rationale='Network routing'){
    const dom=registry(state).domain(requestId);return governedLegacyRequestV3(state,TransferScope.programme(requestId,dom),toSiteId,rationale);
  };
}
if(P.MultiLabPlanningV1170){
  const _stage3LegacyCompareTaskCandidate=P.MultiLabPlanningV1170.compareTaskSiteCandidate.bind(P.MultiLabPlanningV1170);
  P.MultiLabPlanningV1170.compareTaskSiteCandidate=function(state,requestId,stepId,toSiteId){return _stage3LegacyCompareTaskCandidate(clone(state),requestId,stepId,toSiteId)};
  P.MultiLabPlanningV1170.applyTaskTransfer=function(state,requestId,stepId,toSiteId,rationale='Single-operation sister-lab execution'){
    const dom=registry(state).domain(requestId);return governedLegacyRequestV3(state,TransferScope.task(requestId,stepId,dom),toSiteId,rationale);
  };
  P.MultiLabPlanningV1170.clearTaskTransfer=function(){return {ok:false,governed:true,error:'Returning sister-lab work must use the governed Stage-3 network request flow.'}};
}
if(P.PlanningEngine?.prototype){
  P.PlanningEngine.prototype.requestTransfer=function(programmeId,toSiteId,{reason='Sister-lab execution requested',actor=null}={}){
    const context=legacyContextV3(this.state,actor,this.activeLabId?.());return new NetworkTransferService(this.state,{context}).request(TransferScope.programme(programmeId,this.domainOf?.(programmeId)||domain(this.state,programmeId)),toSiteId,{reason});
  };
  P.PlanningEngine.prototype.acceptTransfer=function(recordId,{reason='Receiving laboratory accepted after live-capacity review',actor=null}={}){
    const rec=(this.state.networkTransfers||[]).find(x=>x.id===recordId),context=legacyContextV3(this.state,actor,rec?.toSiteId||this.activeLabId?.());return new NetworkTransferService(this.state,{context}).accept(recordId,{reason});
  };
  P.PlanningEngine.prototype.rejectTransfer=function(recordId,{reason='Receiving laboratory rejected the transfer',actor=null}={}){
    const rec=(this.state.networkTransfers||[]).find(x=>x.id===recordId),context=legacyContextV3(this.state,actor,rec?.toSiteId||this.activeLabId?.());return new NetworkTransferService(this.state,{context}).reject(recordId,{reason});
  };
  P.PlanningEngine.prototype.cancelTransfer=function(recordId,{reason='Sending laboratory cancelled the transfer request',actor=null}={}){
    const rec=(this.state.networkTransfers||[]).find(x=>x.id===recordId),context=legacyContextV3(this.state,actor,rec?.fromSiteId||this.activeLabId?.());return new NetworkTransferService(this.state,{context}).cancel(recordId,{reason});
  };
}
P.__stage3LegacyCompatibilityV3={governed:true,wholeTransfer:'NetworkTransferService.request',taskTransfer:'NetworkTransferService.request',planningEngineTransfers:'NetworkTransferService'};

/* Stage-3 compatibility adapters: all public transfer helpers now route through the
   governed service. Persistence belongs to application transaction wrappers. */
P.networkMetricsV1099=networkMetricsStage3;P.TransferScope=TransferScope;P.resolveTransferScopeV3=resolveTransferScopeV3;P.SiteAssignmentResolver=SiteAssignmentResolver;P.NetworkLogisticsService=NetworkLogisticsService;P.NetworkReadinessGateway=NetworkReadinessGateway;P.NetworkAuthorizationService=NetworkAuthorizationService;P.NetworkProposalService=NetworkProposalService;P.activeNetworkReservationConstraintsV10=activeNetworkReservationConstraints;P.injectNetworkReservationConstraintsV10=injectNetworkReservationConstraints;P.NetworkTransferService=NetworkTransferService;P.NetworkDelta=NetworkDelta;P.NetworkRecordAdapter=NetworkRecordAdapter;P.NetworkDecisionService=NetworkDecisionService;P.ExternalExecutionRequest=ExternalExecutionRequest;P.ExternalOrder=ExternalOrder;P.ExternalExecutionService=ExternalExecutionService;
P.createNetworkTransferService=(state,options={})=>new NetworkTransferService(state,options);
P.compareNetworkAlternativesV3=(state,scope,options={})=>new NetworkProposalService(state,{context:options.context||{}}).compare(scope);
P.requestNetworkTransferV3=(state,scope,toSiteId,options={})=>new NetworkTransferService(state,{context:options.context}).request(scope,toSiteId,options);
P.acceptNetworkTransferV3=(state,id,options={})=>new NetworkTransferService(state,{context:options.context}).accept(id,options);
P.rejectNetworkTransferV3=(state,id,options={})=>new NetworkTransferService(state,{context:options.context}).reject(id,options);
P.cancelNetworkTransferV3=(state,id,options={})=>new NetworkTransferService(state,{context:options.context}).cancel(id,options);
P.STAGE3_NETWORK_ARCHITECTURE='1.0.185-S3-NETWORK';
})(window.ProtoLab);
