(function(){
'use strict'; const P=window.ProtoLab;
class RequestService{
 constructor(state){this.state=state;}
 create(data){
  const n=42+this.state.requests.length,id=`P26-${String(n).padStart(4,'0')}`,product=this.state.products.find(p=>p.id===data.productId)||this.state.products[0],source=P.normaliseMaterialSource(data.materialOwnership);
  const req={id,title:data.title||'New prototype request',requester:this.state.identity.name,engineeringTeam:data.engineeringTeam||'Advanced Engineering',customerId:data.customerId||'CUST-INTERNAL',programme:data.programme||'Internal',vehicleProgramme:data.vehicleProgramme||'',productId:product.id,productFamily:product.family,productRevision:data.productRevision||product.revision,hardwareRevision:data.hardwareRevision||product.hw,softwareRevision:data.softwareRevision||product.sw,maturity:data.maturity||'A-sample',purpose:data.purpose||'Design learning',quantity:Number(data.quantity||1),requiredDate:data.requiredDate,forecastDate:null,priority:data.priority||'Normal',deliveryLocation:data.deliveryLocation||'Engineering',objective:data.objective||'',configuration:data.configuration||`${product.partNumber}-${product.revision}`,bomRef:data.bomRef||`BOM-${product.partNumber}-${data.productRevision||product.revision}`,materialOwnership:source,materialSupply:source==='Engineering supplied'?{owner:data.materialSupplyOwner||this.state.identity.name,expectedDate:data.materialSupplyDate||'',reference:data.materialSupplyReference||''}:null,specialHandling:data.specialHandling||'Standard ESD',specialCharacteristics:data.specialCharacteristics||[],productSafety:!!data.productSafety,characterisation:data.characterisation||[],testRequirements:[],status:'DRAFT REQUEST',currentGate:'DRAFT REQUEST',risk:'Low',owner:'Unassigned',createdAt:P.now(),submittedAt:null,routeId:`ROUTE-${Date.now()}`,controlPlanId:null,costEstimate:0,costActual:null,changeHistory:[],triage:null};
  this.state.requests.unshift(req);P.ensureMaterialRequirements(this.state,req);P.ensureTestRequirements(this.state,req);P.ensureApprovalRecords(this.state,req);
  const steps=P.getDefaultRoute(product.id).map((pid,i)=>{const proc=this.state.processes.find(p=>p.id===pid);return {id:P.uid('STEP'),order:i+1,processId:pid,name:proc?.name||pid,processRevision:proc?.revision||'A',type:'standard',owner:'Unassigned',planned:null,status:'Proposed',readiness:'pending',parallelGroup:null,optional:false};});
  this.state.routes.push({id:req.routeId,requestId:req.id,revision:'A',steps,reworkLoops:[],proposed:true,confirmed:false});P.audit(this.state,'Request created','Request',req.id,'—','DRAFT REQUEST',req.objective);return req;
 }
 submit(id){const r=this.get(id);if(!r)throw new Error('Request not found');const missing=[];['title','productId','quantity','requiredDate','objective'].forEach(k=>{if(!r[k])missing.push(k)});if(missing.length)throw new Error(`Cannot submit: missing ${missing.join(', ')}`);P.ensureMaterialRequirements(this.state,r);P.ensureTestRequirements(this.state,r);P.ensureApprovalRecords(this.state,r);const prev=r.status;r.status=r.currentGate='SUBMITTED';r.submittedAt=P.now();r.owner=this.state.users.find(u=>u.role==='lab_planner')?.name||'Lab Planner';this.state.actions.unshift({id:P.uid('ACT'),requestId:r.id,category:'Needs feasibility input',title:'Assess material supply and process/test fit before scheduling',why:'A requested delivery date is not meaningful until the exact BOM supply route and the required build/test methods are understood.',impact:'AUTO-PLAN remains unavailable until these feasibility inputs are defined.',owner:r.owner,due:r.requiredDate,severity:'warn',resolve:'materials'});P.audit(this.state,'Request submitted','Request',r.id,prev,r.status,'Required engineering fields complete; feasibility assessment starts');return r;}
 get(id){return this.state.requests.find(r=>r.id===id);}
}
class ProcessService{
 constructor(state){this.state=state;}
 fitAssessment(process,need){const rows=[];const comp=process.compatibility||{};rows.push(['Equipment capability',need.equipmentCapability?process.equipmentCapability===need.equipmentCapability:true]);rows.push(['Material',need.material?(!comp.materials||comp.materials.includes(need.material)):true]);rows.push(['Thickness',need.thickness?(!comp.thickness||need.thickness>=Math.min(...comp.thickness)&&need.thickness<=Math.max(...comp.thickness)):true]);rows.push(['Geometry',need.geometry?(!comp.geometry||comp.geometry.includes(need.geometry)):true]);rows.push(['Leak requirement',need.leakRequirement?!!comp.leakRequirement:true]);const misses=rows.filter(r=>!r[1]).length;return {rows,conclusion:misses===0?'EXISTING RELEASED PROCESS':misses<=2?'MODIFIED PROCESS REQUIRED':'NEW PROCESS REQUIRED'};}
 releaseDevelopment(devId){const dev=this.state.processDevelopments.find(d=>d.id===devId);if(!dev)throw new Error('Development not found');const required=['need','plan','trial','parameters','risk','measurement','capability','controlPlan','workInstruction','approval'];const missing=required.filter(k=>!dev.gates[k]);if(missing.length)throw new Error(`Cannot release: incomplete ${missing.join(', ')}`);dev.status='RELEASED';dev.gates.release=true;const id=`PROC-${String(this.state.processes.length+1).padStart(3,'0')}`;this.state.processes.push({id,name:dev.name,family:'Developed',revision:'A',status:'Released',owner:dev.owner,description:'Released from controlled prototype process development.',setupTime:30,cycleTime:20,basis:'Unit',equipmentCapability:'Configured during development',competency:'COMP-01',params:[],requiredEvidence:['Traveller record'],revisionHistory:[{rev:'A',status:'Released',date:P.todayISO(),note:`Released from ${dev.id}`}],approvals:[{role:'Process Engineer',person:dev.owner,date:P.todayISO()}]});P.audit(this.state,'Process released','Process Development',dev.id,'Under development','Released','Development gates satisfied');return id;}
}
class ControlPlanService{
 constructor(state){this.state=state;}
 approve(id){const cp=this.state.controlPlans.find(c=>c.id===id);if(!cp)throw new Error('Control Plan not found');if(!P.can(this.state.identity.role,'controlplan:approve'))throw new Error('Current role is not authorised to approve Control Plans. Use an independent Approver / Reviewer or authorised Quality approver.');if(this.state.settings.separationOfDuties&&cp.owner===this.state.identity.name){const independent=this.state.users.find(u=>u.role==='approver'&&u.name!==cp.owner);throw new Error(`Separation of duties prevents self-approval. ${independent?independent.name+' · Approver / Reviewer is eligible for this demo.':'Switch to an independent authorised approver.'}`);}const invalid=(cp.characteristics||[]).filter(c=>c.classification&&!P.controlCharacteristicReady(c));if(invalid.length)throw new Error(`Control Plan definition incomplete: ${invalid.map(c=>c.id).join(', ')} still needs a specification (target or limits), method/gauge, reaction plan and evidence.`);const prev=cp.status;cp.status='Approved';cp.approvedBy=this.state.identity.name;cp.approvedAt=P.now();P.audit(this.state,'Control Plan approved','Control Plan',id,prev,'Approved','Independent review complete');}
 revise(id){const cp=this.state.controlPlans.find(c=>c.id===id);if(!cp)throw new Error('Control Plan not found');const clone=P.deepClone(cp);clone.id=P.uid('CP');clone.revision=String.fromCharCode(cp.revision.charCodeAt(0)+1);clone.status='Draft';clone.approvedBy=null;clone.approvedAt=null;clone.supersedes=cp.id;cp.status='Superseded';this.state.controlPlans.push(clone);P.audit(this.state,'Control Plan revision created','Control Plan',clone.id,cp.revision,clone.revision,`Supersedes ${cp.id}`);return clone;}
}
class ReadinessService{
 constructor(state){this.state=state;}
 evaluate(requestId){
  const r=this.state.requests.find(x=>x.id===requestId);if(!r)return {checks:[],issues:[{name:'Request',owner:'Lab Planner',action:'Open a valid request',why:'The request does not exist.',evidence:'Valid request record.'}],ready:false};P.ensureMaterialRequirements(this.state,r);P.ensureTestRequirements(this.state,r);P.ensureApprovalRecords(this.state,r);
  const route=this.state.routes.find(x=>x.requestId===requestId),cp=this.state.controlPlans.find(x=>x.id===r.controlPlanId),issues=[],independentApprover=this.state.users.find(u=>u.role==='approver'&&(!cp||u.name!==cp.owner)),mat=P.materialPlanningAssessment(this.state,r),testReqs=r.testRequirements||[];
  const routeConfirmed=!!(route&&route.steps?.length&&route.confirmed===true),processesReleased=!!(route&&route.steps?.length&&route.steps.every(s=>{if(s.type==='standard'){const p=this.state.processes.find(x=>x.id===s.processId);return p?.status==='Released'&&p.revision===s.processRevision;}const dev=this.state.processDevelopments.find(d=>d.requestId===requestId&&(d.libraryCandidate===s.processId||String(d.name).includes(s.name)));return dev?.status==='RELEASED';}));
  const testsReleased=testReqs.every(tr=>tr.standardTestId?this.state.standardTests?.some(t=>t.id===tr.standardTestId&&t.status==='Released'):tr.developmentReleased===true);
  const cpDefinitionReady=!!(cp&&cp.characteristics?.length&&cp.characteristics.every(c=>!c.classification||P.controlCharacteristicReady(c))),bookings=(this.state.bookings||[]).filter(b=>b.requestId===requestId),executionBookings=bookings.filter(b=>['process','test'].includes(b.taskType));
  const equipmentReady=!!(executionBookings.length&&executionBookings.every(b=>{const e=this.state.equipment.find(x=>x.id===b.equipmentId);return e&&e.calibrationStatus==='Valid';}));
  const peopleReady=!!(bookings.length&&bookings.every(b=>{const person=this.state.staff.find(x=>x.id===b.staffId);return person&&person.available&&(!b.skillId||person.competencies.includes(b.skillId));}));
  const readinessApprovals=this.state.approvals.filter(a=>a.requestId===requestId&&a.stage==='readiness'&&!['Product Safety','Build Readiness'].includes(a.type));
  const checks=[
   ['Product definition',!!r.productId,'Engineering Requester','Complete product/configuration definition'],
   ['BOM / configuration',!!r.configuration&&!!r.bomRef,'Engineering Requester','Add controlled configuration and BOM reference'],
   ['Material physically ready',mat.buildReady,'Lab Planner',mat.buildReady?'Verify exact issued lots':'Receive/issue the exact required BOM lots before build start'],
   ['Committed timing plan',r.triage?.status==='Committed','Lab Planner','Complete feasibility inputs, run AUTO-PLAN and commit the forecast'],
   ['Process route confirmed',routeConfirmed,'Process Engineer','Review and confirm the actual build route'],
   ['Processes released',processesReleased,'Process Engineer','Complete and release every new/modified process used by the build'],
   ['Required test methods released',testsReleased,'Process Engineer / Metrology','Use released standard tests or complete/release required test development'],
   ['PFMEA / risk reviewed',!this.state.pfmea.some(x=>x.requestId===requestId&&x.status==='Open high risk'),'Process Engineer','Close high-risk process risk or add controlled disposition'],
   ['Control Plan approved',!!(cp&&cp.status==='Approved'&&cpDefinitionReady),cp&&cp.status!=='Approved'?(independentApprover?`${independentApprover.name} · Approver / Reviewer`:'Independent approver'):'Quality Engineer','Complete Control Plan definition and independent approval'],
   ['Equipment / calibration',equipmentReady,'Lab Planner / Metrology','Use the committed resource plan with valid capable calibrated equipment'],
   ['Qualified people',peopleReady,'Lab Planner','Use the committed plan with people qualified for the required process/test skills'],
   ['Product safety approval',!r.productSafety||this.state.approvals.some(a=>a.requestId===requestId&&a.type==='Product Safety'&&a.status==='Approved'),'Product Safety Representative','Complete the configured product-safety review'],
   ['Customer-specific readiness gates',readinessApprovals.every(a=>a.status==='Approved'),'Configured approver','Complete applicable customer-profile readiness approvals']
  ];
  checks.forEach(([name,ok,owner,action])=>{if(!ok)issues.push({name,owner,action,why:`${name} is required for controlled prototype-build readiness and traceability.`,evidence:`Objective evidence that ${name.toLowerCase()} is complete, current and linked to this request.`});});return {checks,issues,ready:issues.length===0};
 }
 override(requestId,scope,reason,riskImpact,tempPermanent,approvalRequired){if(!P.can(this.state.identity.role,'override:approve')&&!P.can(this.state.identity.role,'*'))throw new Error('Current role cannot authorise this override.');if(!reason||!riskImpact)throw new Error('Override requires reason and risk/impact.');const r=this.state.requests.find(x=>x.id===requestId);r.overrides=r.overrides||[];const o={id:P.uid('OVR'),scope,reason,riskImpact,tempPermanent,approvalRequired,person:this.state.identity.name,role:this.state.identity.role,timestamp:P.now()};r.overrides.push(o);P.audit(this.state,'Controlled override approved','Request',requestId,'Blocked',`Override: ${scope}`,reason);return o;}
}
function nextWorkStart(date){const d=new Date(date);while(d.getDay()===0||d.getDay()===6)d.setDate(d.getDate()+1);if(d.getHours()<8)d.setHours(8,0,0,0);if(d.getHours()>=17){d.setDate(d.getDate()+1);d.setHours(8,0,0,0);return nextWorkStart(d);}return d;}
function addWorkHours(start,hours){let d=nextWorkStart(start),left=hours;while(left>0){const end=new Date(d);end.setHours(17,0,0,0);const avail=(end-d)/3600000;if(left<=avail){d=new Date(d.getTime()+left*3600000);left=0;}else{left-=avail;d=new Date(end);d.setDate(d.getDate()+1);d.setHours(8,0,0,0);d=nextWorkStart(d);}}return d;}
function overlaps(aStart,aEnd,bStart,bEnd){return new Date(aStart)<new Date(bEnd)&&new Date(aEnd)>new Date(bStart);}
class LearningService{
 insights(state,productId){const h=(state.buildHistory||[]).filter(x=>x.productId===productId),avg=a=>a.length?a.reduce((s,x)=>s+Number(x||0),0)/a.length:null,counts={};h.flatMap(x=>x.issues||[]).forEach(x=>counts[x]=(counts[x]||0)+1);const issues=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,4);return {builds:h.length,firstPassYield:avg(h.map(x=>x.firstPassYield)),scrapRate:avg(h.map(x=>x.scrapRate)),reworkHours:avg(h.map(x=>x.reworkHours)),issues,lessons:h.flatMap(x=>x.lessons||[]).slice(-5)};}
 estimateProcess(state,r,proc){const std=Math.max(.25,(Number(proc.setupTime||0)+Number(proc.cycleTime||0)*(proc.basis==='Batch'?1:Number(r.quantity||1)))/60),hist=(state.buildHistory||[]).filter(h=>h.productId===r.productId).map(h=>{const x=(h.stepActuals||[]).find(s=>s.processId===proc.id);return x?Number(x.durationHours)*Number(r.quantity||1)/Math.max(1,Number(h.quantity||1)):null;}).filter(Number.isFinite),med=P.median(hist);if(med===null)return {hours:Number(std.toFixed(2)),basis:`Standard ${proc.id} Rev ${proc.revision}`,samples:0};const w=hist.length>=3?.75:.55,hours=med*w+std*(1-w);return {hours:Number(hours.toFixed(2)),basis:`Same-product history median n=${hist.length} + standard`,samples:hist.length};}
 estimateTest(state,r,test){const std=Math.max(.25,(Number(test.setupTime||0)+Number(test.cycleTime||0)*(test.basis==='Batch'?1:Number(r.quantity||1)))/60),hist=(state.buildHistory||[]).filter(h=>h.productId===r.productId).map(h=>{const x=(h.testActuals||[]).find(s=>s.testId===test.id);return x?Number(x.durationHours)*Number(r.quantity||1)/Math.max(1,Number(h.quantity||1)):null;}).filter(Number.isFinite),med=P.median(hist);if(med===null)return {hours:Number(std.toFixed(2)),basis:`Standard ${test.id} Rev ${test.revision}`,samples:0};const w=hist.length>=3?.75:.55,hours=med*w+std*(1-w);return {hours:Number(hours.toFixed(2)),basis:`Same-product history median n=${hist.length} + standard test`,samples:hist.length};}
 captureBuild(state,requestId){const r=state.requests.find(x=>x.id===requestId);if(!r||state.buildHistory?.some(h=>h.requestId===requestId))return;state.buildHistory=state.buildHistory||[];const route=state.routes.find(x=>x.requestId===requestId),serials=state.serials.filter(s=>s.requestId===requestId),devs=state.deviations.filter(d=>d.requestId===requestId),stepActuals=(route?.steps||[]).filter(s=>s.completedAt).map(s=>({processId:s.processId,durationHours:Number(s.actualDurationHours||0)||null})).filter(x=>x.durationHours),accepted=serials.filter(s=>!['Hold','Scrapped'].includes(s.status)).length,fpy=serials.length?accepted/serials.length:1,scrap=serials.length?serials.filter(s=>s.status==='Scrapped').length/serials.length:0,lessons=state.lessons.filter(l=>l.requestId===requestId).map(l=>l.recommendation||l.observation);state.buildHistory.push({id:P.uid('HIST'),requestId,productId:r.productId,quantity:r.quantity,completedAt:P.todayISO(),firstPassYield:fpy,scrapRate:scrap,reworkHours:devs.filter(d=>/rework/i.test(d.disposition||'')).length*1.5,issues:devs.map(d=>d.measurement||d.type),lessons,stepActuals,testActuals:[]});}
}
class PlannerService{
 autoPlan(state,requestId){
  const r=state.requests.find(x=>x.id===requestId);if(!r)throw new Error('Request not found');P.ensurePlanningModel(state);const mat=P.materialPlanningAssessment(state,r),procAssess=P.processPlanningAssessment(state,r);if(!mat.planningReady)throw new Error(`AUTO-PLAN needs material feasibility first: ${mat.issues.join(' ')}`);if(!procAssess.ready)throw new Error(`AUTO-PLAN needs process/test definition first: ${procAssess.issues.join(' ')}`);const route=procAssess.route,learning=new LearningService();
  state.bookings=state.bookings||[];state.bookings=state.bookings.filter(b=>b.requestId!==requestId||b.locked);const bookings=state.bookings,changes=[],riskNotes=[];let startBase=new Date(Date.now()+30*60000);if(mat.earliestDate){const m=new Date(`${mat.earliestDate}T08:00:00`);if(m>startBase)startBase=m;}let cursor=nextWorkStart(startBase),effort=0;
  const resourceBusy=(id,start,end)=>bookings.some(b=>(b.requestId!==requestId||b.locked)&&(b.resourceId===id||b.equipmentId===id||b.staffId===id)&&overlaps(start,end,b.start,b.end||new Date(new Date(b.start).getTime()+Number(b.durationHours||1)*3600000)));
  const place=(task,duration,equipmentCapability,skillId,basis,status='Planned',taskType='process')=>{const eqCandidates=equipmentCapability?state.equipment.filter(e=>e.capability===equipmentCapability&&e.calibrationStatus==='Valid'):[],people=state.staff.filter(x=>x.available&&(!skillId||x.competencies.includes(skillId)));if(equipmentCapability&&!eqCandidates.length)throw new Error(`No valid calibrated equipment has capability “${equipmentCapability}” for ${task.name}.`);if(!people.length)throw new Error(`No available person has required skill ${skillId||'for '+task.name}.`);const equipment=equipmentCapability?eqCandidates[0]:null,person=people[0];let attempts=0,start,end;do{start=nextWorkStart(cursor);end=addWorkHours(start,duration);if((!equipment||!resourceBusy(equipment.id,start,end))&&!resourceBusy(person.id,start,end))break;cursor=new Date(start.getTime()+60*60000);attempts++;}while(attempts<240);if(attempts>=240)throw new Error(`No conflict-free slot found for ${task.name}.`);const booking={id:P.uid('BOOK'),requestId,stepId:task.id,stepName:task.name,equipmentId:equipment?.id||null,staffId:person.id,skillId:skillId||null,start:start.toISOString(),end:end.toISOString(),durationHours:Number(duration.toFixed(2)),locked:false,risk:status!=='Planned',status,taskType,estimateBasis:basis,description:`${r.id} · ${task.name}`};bookings.push(booking);changes.push({step:task.name,equipment:equipment?.name||'—',person:person.name,start:booking.start,durationHours:booking.durationHours,basis});cursor=end;effort+=duration;return booking;};
  for(const s of route.steps){const proc=state.processes.find(p=>p.id===s.processId);if(s.type!=='standard'){const dev=state.processDevelopments.find(d=>d.requestId===requestId&&(d.libraryCandidate===s.processId||String(d.name).includes(s.name)));const devHours=Number(dev?.planningEstimateHours);place({id:`DEV-${s.id}`,name:`Develop / validate ${s.name}`},devHours,null,'COMP-02',`Process Engineer estimate from ${dev?.id||'development plan'}`,'Provisional','development');riskNotes.push(`${s.name}: includes ${devHours} h controlled development before execution.`);}const est=learning.estimateProcess(state,r,proc);const b=place(s,est.hours,proc.equipmentCapability,proc.competency,est.basis,s.type==='standard'?'Planned':'Provisional','process');s.planned=b.start;s.owner=state.staff.find(x=>x.id===b.staffId)?.name||'Unassigned';s.equipmentId=b.equipmentId;}
  for(const tr of r.testRequirements||[]){if(tr.standardTestId){const test=state.standardTests.find(x=>x.id===tr.standardTestId),est=learning.estimateTest(state,r,test);place({id:tr.id,name:`Test · ${tr.name}`},est.hours,test.equipmentCapability,test.competency,est.basis,'Planned','test');}else{place({id:`DEV-${tr.id}`,name:`Develop test · ${tr.name}`},Number(tr.developmentEstimateHours),null,'COMP-03',`Test-development estimate defined by ${tr.owner}`,'Provisional','development');place({id:tr.id,name:`Provisional test · ${tr.name}`},Number(tr.executionEstimateHours),tr.equipmentCapability,tr.competency,'Process Engineer provisional test execution estimate','Provisional','test');riskNotes.push(`${tr.name}: test method development/release remains a build-readiness gate.`);}}
  const finish=cursor,forecast=addWorkHours(finish,4);r.forecastDate=forecast.toISOString().slice(0,10);const slack=P.daysBetween(r.forecastDate,r.requiredDate),ins=learning.insights(state,r.productId);r.risk=slack<0?'High':slack<=2?'Medium':'Low';r.owner=r.owner&&r.owner!=='Unassigned'?r.owner:(state.users.find(u=>u.role==='lab_planner')?.name||'Lab Planner');r.triage={status:'Provisional',assessedAt:P.now(),plannedStart:changes[0]?.start||null,plannedFinish:finish.toISOString(),forecastDate:r.forecastDate,slackDays:slack,effortHours:Number(effort.toFixed(1)),feasibleByRequiredDate:slack>=0,routeBasis:'Confirmed process route + defined test requirements',materialBasis:mat.summary,historyBuilds:ins.builds,riskNotes};P.audit(state,'Auto-plan generated','Request',requestId,'No committed schedule',r.forecastDate,`Confirmed route/tests; ${changes.length} bookings / ${r.triage.effortHours} h; history n=${ins.builds}`);return changes;
 }
}
class QualityService{
 constructor(state){this.state=state;}
 evaluateMeasurement(m){if(m.value===null||m.value===undefined)return true;return (m.lsl===null||m.lsl===undefined||m.value>=m.lsl)&&(m.usl===null||m.usl===undefined||m.value<=m.usl);}
 closeDeviation(id){const d=this.state.deviations.find(x=>x.id===id);if(!d)throw new Error('Deviation not found');if((d.actions||[]).some(a=>a.mandatory&&!a.closed))throw new Error('Cannot close: mandatory actions remain open.');if(!d.disposition||d.disposition==='Pending')throw new Error('Cannot close: disposition is not complete.');const prev=d.status;d.status='CLOSED';d.releaseHold=false;P.audit(this.state,'Deviation closed','Deviation',id,prev,'CLOSED',d.disposition);}
 releaseRequest(requestId){const r=this.state.requests.find(x=>x.id===requestId);P.ensureApprovalRecords(this.state,r);const holds=this.state.deviations.filter(d=>d.requestId===requestId&&d.releaseHold&&d.status!=='CLOSED');if(holds.length)throw new Error(`Cannot release: ${holds.length} unresolved release hold(s).`);const fails=this.state.measurements.filter(m=>m.requestId===requestId&&!m.pass);if(fails.length&&!this.state.deviations.some(d=>d.requestId===requestId&&d.status==='CLOSED'))throw new Error('Cannot release: failed measurement lacks closed disposition.');const cp=this.state.controlPlans.find(c=>c.id===r.controlPlanId);if(!cp||cp.status!=='Approved')throw new Error('Cannot release: Control Plan is not independently approved.');const pending=this.state.approvals.filter(a=>a.requestId===requestId&&a.status!=='Approved');if(pending.length)throw new Error(`Cannot release: pending approval(s): ${pending.map(a=>a.type).join(', ')}.`);const prev=r.status;r.status=r.currentGate='RELEASED';this.state.serials.filter(s=>s.requestId===requestId&&s.status!=='Hold'&&s.status!=='Scrapped').forEach(s=>s.releaseState='Released');P.audit(this.state,'Build released','Request',requestId,prev,'RELEASED','Release review satisfied');return r;}
}
class SerialService{constructor(state){this.state=state;}generate(requestId,count){const r=this.state.requests.find(x=>x.id===requestId);const existing=this.state.serials.filter(s=>s.requestId===requestId).length;const lots=this.state.allocations.filter(a=>a.requestId===requestId&&a.status==='Issued'&&a.requirementId).map(a=>a.lot);const out=[];for(let i=1;i<=count;i++){const serial=`${r.id}-${String(existing+i).padStart(3,'0')}`;if(this.state.serials.some(s=>s.serial===serial))throw new Error(`Duplicate serial ${serial}`);const obj={id:P.uid('SER'),serial,requestId:r.id,productId:r.productId,configuration:r.configuration,status:'Active',materials:P.deepClone(lots),processHistory:[],releaseState:'Not released',delivery:null};this.state.serials.push(obj);out.push(obj);}P.audit(this.state,'Serials generated','Request',requestId,existing,existing+count,`${count} serials`);return out;}}
class ReportService{constructor(state){this.state=state;}build(requestId,approved=false){const r=this.state.requests.find(x=>x.id===requestId);const serials=this.state.serials.filter(s=>s.requestId===requestId);const meas=this.state.measurements.filter(m=>m.requestId===requestId);const dev=this.state.deviations.filter(d=>d.requestId===requestId);return {r,serials,meas,dev,approved,generatedAt:P.now(),approver:approved?this.state.identity.name:null};}}
P.RequestService=RequestService;P.ProcessService=ProcessService;P.ControlPlanService=ControlPlanService;P.ReadinessService=ReadinessService;P.LearningService=LearningService;P.PlannerService=PlannerService;P.LocalPlannerService=PlannerService;P.QualityService=QualityService;P.SerialService=SerialService;P.ReportService=ReportService;
})();
