(function(){
'use strict'; const P=window.ProtoLab;
class RequestService{
 constructor(state){this.state=state;}
 create(data){const n=42+this.state.requests.length; const id=`P26-${String(n).padStart(4,'0')}`; const product=this.state.products.find(p=>p.id===data.productId)||this.state.products[0]; const req={id,title:data.title||'New prototype request',requester:this.state.identity.name,engineeringTeam:data.engineeringTeam||'Advanced Engineering',customerId:data.customerId||'CUST-INTERNAL',programme:data.programme||'Internal',vehicleProgramme:data.vehicleProgramme||'',productId:product.id,productFamily:product.family,productRevision:data.productRevision||product.revision,hardwareRevision:data.hardwareRevision||product.hw,softwareRevision:data.softwareRevision||product.sw,maturity:data.maturity||'A-sample',purpose:data.purpose||'Design learning',quantity:Number(data.quantity||1),requiredDate:data.requiredDate,forecastDate:data.requiredDate,priority:data.priority||'Normal',deliveryLocation:data.deliveryLocation||'Engineering',objective:data.objective||'',configuration:data.configuration||`${product.partNumber}-${product.revision}`,bomRef:data.bomRef||'',materialOwnership:data.materialOwnership||'Engineering supplied',specialHandling:data.specialHandling||'Standard ESD',specialCharacteristics:data.specialCharacteristics||[],productSafety:!!data.productSafety,characterisation:data.characterisation||[],status:'DRAFT REQUEST',currentGate:'DRAFT REQUEST',risk:'Low',owner:'Unassigned',createdAt:P.now(),submittedAt:null,routeId:`ROUTE-${Date.now()}`,controlPlanId:null,costEstimate:0,costActual:null,changeHistory:[]}; this.state.requests.unshift(req);this.state.routes.push({id:req.routeId,requestId:req.id,revision:'A',steps:[],reworkLoops:[]});P.audit(this.state,'Request created','Request',req.id,'—','DRAFT REQUEST',req.objective);return req; }
 submit(id){const r=this.get(id); if(!r)throw new Error('Request not found'); const missing=[];['title','productId','quantity','requiredDate','objective'].forEach(k=>{if(!r[k])missing.push(k)});if(missing.length)throw new Error(`Cannot submit: missing ${missing.join(', ')}`);const prev=r.status;r.status=r.currentGate='SUBMITTED';r.submittedAt=P.now();r.owner='Mila Jansen';this.state.actions.unshift({id:P.uid('ACT'),requestId:r.id,category:'Needs lab action',title:'New request requires triage',why:'Engineering submitted a new prototype build request.',impact:'Forecast and feasibility remain provisional until lab triage.',owner:'Mila Jansen',due:r.requiredDate,severity:'warn',resolve:'overview'});P.audit(this.state,'Request submitted','Request',r.id,prev,r.status,'Required fields complete');return r; }
 get(id){return this.state.requests.find(r=>r.id===id);}
}
class ProcessService{
 constructor(state){this.state=state;}
 fitAssessment(process,need){const rows=[];const comp=process.compatibility||{};rows.push(['Equipment capability',need.equipmentCapability?process.equipmentCapability===need.equipmentCapability:true]);rows.push(['Material',need.material?(!comp.materials||comp.materials.includes(need.material)):true]);rows.push(['Thickness',need.thickness?(!comp.thickness||need.thickness>=Math.min(...comp.thickness)&&need.thickness<=Math.max(...comp.thickness)):true]);rows.push(['Geometry',need.geometry?(!comp.geometry||comp.geometry.includes(need.geometry)):true]);rows.push(['Leak requirement',need.leakRequirement?!!comp.leakRequirement:true]);const misses=rows.filter(r=>!r[1]).length;return {rows,conclusion:misses===0?'EXISTING RELEASED PROCESS':misses<=2?'MODIFIED PROCESS REQUIRED':'NEW PROCESS REQUIRED'};}
 releaseDevelopment(devId){const dev=this.state.processDevelopments.find(d=>d.id===devId);if(!dev)throw new Error('Development not found');const required=['need','plan','trial','parameters','risk','measurement','capability','controlPlan','workInstruction','approval'];const missing=required.filter(k=>!dev.gates[k]);if(missing.length)throw new Error(`Cannot release: incomplete ${missing.join(', ')}`);dev.status='RELEASED';dev.gates.release=true;const id=`PROC-${String(this.state.processes.length+1).padStart(3,'0')}`;this.state.processes.push({id,name:dev.name,family:'Developed',revision:'A',status:'Released',owner:dev.owner,description:'Released from controlled prototype process development.',setupTime:30,cycleTime:20,basis:'Unit',equipmentCapability:'Configured during development',competency:'COMP-01',params:[],requiredEvidence:['Traveller record'],revisionHistory:[{rev:'A',status:'Released',date:P.todayISO(),note:`Released from ${dev.id}`}],approvals:[{role:'Process Engineer',person:dev.owner,date:P.todayISO()}]});P.audit(this.state,'Process released','Process Development',dev.id,'Under development','Released','Development gates satisfied');return id;}
}
class ControlPlanService{
 constructor(state){this.state=state;}
 approve(id){const cp=this.state.controlPlans.find(c=>c.id===id);if(!cp)throw new Error('Control Plan not found');if(!P.can(this.state.identity.role,'controlplan:approve'))throw new Error('Current role is not authorised to approve Control Plans. Use an independent Approver / Reviewer or authorised Quality approver.');if(this.state.settings.separationOfDuties&&cp.owner===this.state.identity.name){const independent=this.state.users.find(u=>u.role==='approver'&&u.name!==cp.owner);throw new Error(`Separation of duties prevents self-approval. ${independent?independent.name+' · Approver / Reviewer is eligible for this demo.':'Switch to an independent authorised approver.'}`);} const invalid=cp.characteristics.filter(c=>c.classification&&(!c.method||!c.reactionPlan||(c.target===null||c.target===undefined||c.target==='')||c.target==='Define target'));if(invalid.length)throw new Error('Control Plan definition incomplete: every special characteristic requires a defined specification/target, measurement method and reaction plan before approval.');const prev=cp.status;cp.status='Approved';cp.approvedBy=this.state.identity.name;cp.approvedAt=P.now();P.audit(this.state,'Control Plan approved','Control Plan',id,prev,'Approved','Independent review complete');}
 revise(id){const cp=this.state.controlPlans.find(c=>c.id===id);if(!cp)throw new Error('Control Plan not found');const clone=P.deepClone(cp);clone.id=P.uid('CP');clone.revision=String.fromCharCode(cp.revision.charCodeAt(0)+1);clone.status='Draft';clone.approvedBy=null;clone.approvedAt=null;clone.supersedes=cp.id;cp.status='Superseded';this.state.controlPlans.push(clone);P.audit(this.state,'Control Plan revision created','Control Plan',clone.id,cp.revision,clone.revision,`Supersedes ${cp.id}`);return clone;}
}
class ReadinessService{
 constructor(state){this.state=state;}
 evaluate(requestId){const r=this.state.requests.find(x=>x.id===requestId);const route=this.state.routes.find(x=>x.requestId===requestId);const cp=this.state.controlPlans.find(x=>x.id===r.controlPlanId);const alloc=this.state.allocations.filter(a=>a.requestId===requestId);const issues=[];const independentApprover=this.state.users.find(u=>u.role==='approver'&&(!cp||u.name!==cp.owner));
 const checks=[
  ['Product definition',!!r.productId,'Engineering Requester','Complete product/configuration definition'],['BOM / configuration',!!r.configuration,'Engineering Requester','Add controlled configuration/BOM reference'],['Material available',alloc.length>0&&alloc.every(a=>a.status==='Issued'),'Lab Planner','Allocate all required material lots'],['Process route',route&&route.steps.length>0,'Process Engineer','Define process route'],['Processes released',route&&route.steps.every(s=>s.type==='standard'||s.status==='Complete'),'Process Engineer','Complete and release new/modified process'],['PFMEA / risk reviewed',!this.state.pfmea.some(x=>x.requestId===requestId&&x.status==='Open high risk'),'Process Engineer','Close high-risk process risk or add controlled disposition'],['Control Plan approved',cp&&cp.status==='Approved',cp&&cp.status!=='Approved'?(independentApprover?`${independentApprover.name} · Approver / Reviewer`:'Independent approver'):'Quality Engineer','Complete independent Control Plan review and approval'],['Work instructions ready',route&&route.steps.every(s=>s.processRevision),'Process Engineer','Assign released process/work instruction revision'],['Equipment available',!this.state.actions.some(a=>a.requestId===requestId&&/equipment|calibration/i.test(a.title)),'Lab Planner / Metrology','Resolve equipment capability or schedule alternative'],['Equipment calibration',!this.state.actions.some(a=>a.requestId===requestId&&/calibration/i.test(a.title)),'Metrology','Calibrate resource or select valid alternative'],['Operators competent',true,'Lab Planner','Assign qualified operator'],['Special characteristics',!(r.specialCharacteristics?.length)&&true || (cp&&cp.characteristics.some(c=>c.classification&&c.method)),'Quality Engineer','Create suitable Control Plan control for each special characteristic'],['Required measurements',cp&&cp.characteristics.length>0,'Quality Engineer','Define required measurements'],['Product safety approval',!r.productSafety||this.state.approvals.some(a=>a.requestId===requestId&&a.type==='Product Safety'&&a.status==='Approved'),'Product Safety Representative','Complete product-safety review'],['Customer-specific gates',true,'Quality Engineer','Complete configured customer gates']
 ];
 checks.forEach(([name,ok,owner,action])=>{if(!ok)issues.push({name,owner,action,why:`${name} is required to establish controlled build readiness and traceability.`,evidence:`Evidence that ${name.toLowerCase()} is complete and current.`});}); return {checks,issues,ready:issues.length===0}; }
 override(requestId,scope,reason,riskImpact,tempPermanent,approvalRequired){if(!P.can(this.state.identity.role,'override:approve')&&!P.can(this.state.identity.role,'*'))throw new Error('Current role cannot authorise this override.');if(!reason||!riskImpact)throw new Error('Override requires reason and risk/impact.');const r=this.state.requests.find(x=>x.id===requestId);r.overrides=r.overrides||[];const o={id:P.uid('OVR'),scope,reason,riskImpact,tempPermanent,approvalRequired,person:this.state.identity.name,role:this.state.identity.role,timestamp:P.now()};r.overrides.push(o);P.audit(this.state,'Controlled override approved','Request',requestId,'Blocked',`Override: ${scope}`,reason);return o;}
}
class PlannerService{autoPlan(state,requestId){const r=state.requests.find(x=>x.id===requestId);const route=state.routes.find(x=>x.requestId===requestId);if(!r||!route)throw new Error('Request/route not found');let day=0,hour=8;const changes=[];route.steps.forEach((s,idx)=>{const proc=state.processes.find(p=>p.id===s.processId);let candidates=state.equipment.filter(e=>!proc||e.capability===proc.equipmentCapability||idx%3===0).filter(e=>e.calibrationStatus==='Valid');if(!candidates.length)candidates=state.equipment.filter(e=>e.calibrationStatus==='Valid');const chosen=candidates.find(e=>e.status==='Available')||candidates[0];const people=state.staff.filter(x=>x.available&&(!proc||x.competencies.includes(proc.competency)));const person=people[0]||state.staff.find(x=>x.available);if(!chosen||!person)throw new Error(`No feasible qualified/capable resource for ${s.name}`);const start=new Date();start.setDate(start.getDate()+day);start.setHours(hour,0,0,0);s.planned=start.toISOString();s.owner=person.name;s.equipmentId=chosen.id;changes.push({step:s.name,equipment:chosen.name,person:person.name,start:s.planned});hour+=2;if(hour>16){day++;hour=8;}});r.forecastDate=new Date(Date.now()+(day+1)*86400000).toISOString().slice(0,10);P.audit(state,'Auto-plan generated','Request',requestId,'Existing schedule',r.forecastDate,'Planner searched valid equipment and qualified available staff');return changes;}}
class QualityService{
 constructor(state){this.state=state;}
 evaluateMeasurement(m){if(m.value===null||m.value===undefined)return true;return (m.lsl===null||m.lsl===undefined||m.value>=m.lsl)&&(m.usl===null||m.usl===undefined||m.value<=m.usl);}
 closeDeviation(id){const d=this.state.deviations.find(x=>x.id===id);if(!d)throw new Error('Deviation not found');if((d.actions||[]).some(a=>a.mandatory&&!a.closed))throw new Error('Cannot close: mandatory actions remain open.');if(!d.disposition||d.disposition==='Pending')throw new Error('Cannot close: disposition is not complete.');const prev=d.status;d.status='CLOSED';d.releaseHold=false;P.audit(this.state,'Deviation closed','Deviation',id,prev,'CLOSED',d.disposition);}
 releaseRequest(requestId){const r=this.state.requests.find(x=>x.id===requestId);const holds=this.state.deviations.filter(d=>d.requestId===requestId&&d.releaseHold&&d.status!=='CLOSED');if(holds.length)throw new Error(`Cannot release: ${holds.length} unresolved release hold(s).`);const fails=this.state.measurements.filter(m=>m.requestId===requestId&&!m.pass);if(fails.length&&!this.state.deviations.some(d=>d.requestId===requestId&&d.status==='CLOSED'))throw new Error('Cannot release: failed measurement lacks closed disposition.');const prev=r.status;r.status=r.currentGate='RELEASED';P.audit(this.state,'Build released','Request',requestId,prev,'RELEASED','Release review satisfied');return r;}
}
class SerialService{constructor(state){this.state=state;} generate(requestId,count){const r=this.state.requests.find(x=>x.id===requestId);const existing=this.state.serials.filter(s=>s.requestId===requestId).length;const out=[];for(let i=1;i<=count;i++){const serial=`${r.id}-${String(existing+i).padStart(3,'0')}`;if(this.state.serials.some(s=>s.serial===serial))throw new Error(`Duplicate serial ${serial}`);const obj={id:P.uid('SER'),serial,requestId:r.id,productId:r.productId,configuration:r.configuration,status:'Active',materials:[],processHistory:[],releaseState:'Not released',delivery:null};this.state.serials.push(obj);out.push(obj);}P.audit(this.state,'Serials generated','Request',requestId,existing,existing+count,`${count} serials`);return out;}}
class ReportService{constructor(state){this.state=state;} build(requestId,approved=false){const r=this.state.requests.find(x=>x.id===requestId);const serials=this.state.serials.filter(s=>s.requestId===requestId);const meas=this.state.measurements.filter(m=>m.requestId===requestId);const dev=this.state.deviations.filter(d=>d.requestId===requestId);return {r,serials,meas,dev,approved,generatedAt:P.now(),approver:approved?this.state.identity.name:null};}}
P.RequestService=RequestService;P.ProcessService=ProcessService;P.ControlPlanService=ControlPlanService;P.ReadinessService=ReadinessService;P.PlannerService=PlannerService;P.LocalPlannerService=PlannerService;P.QualityService=QualityService;P.SerialService=SerialService;P.ReportService=ReportService;
})();
