from pathlib import Path
import json, subprocess, sys
ROOT=Path(__file__).resolve().parent
checks=[]
def check(name,cond,detail=''):
    checks.append((name,bool(cond),detail)); print(('PASS' if cond else 'FAIL')+f' | {name}'+(f' | {detail}' if detail else ''))
def txt(n): return (ROOT/n).read_text(encoding='utf-8')
core,app,svc,idx,sw=[txt(x) for x in ['core.js','app.js','services.js','index.html','service-worker.js']]
check('Version is REV 1.0.93',"ProtoLab.VERSION = '1.0.93-poc'" in core and 'REV 1.0.93' in idx)
check('Main assets cache-busted to 1.0.93',idx.count('?v=1.0.93')>=5)
check('Service-worker reset identity updated','LabOS 1.0.93 cache reset worker' in sw)
check('CP approval invalidation engine exists','invalidateControlPlanApproval' in core and 'approvalInvalidatedAt' in core)
check('CP stale sign-off rows are superseded',"a.status='Superseded'" in core and "a.supersededReason=reason" in core)
check('All CP mutation flows reset approval',app.count('P.invalidateControlPlanApproval(App.state,cp')>=4,str(app.count('P.invalidateControlPlanApproval(App.state,cp')))
check('Sticky sign-off names final Quality action','Quality approve Control Plan' in app and 'Final CP approval is incomplete' in app)
check('Sticky next action blocks rather than fake-continue','Blocked · waiting for Quality Engineering' in app and 'v1093-governance-blocked' in app)
check('Visible CP approval path added','CONTROL PLAN APPROVAL PATH' in app and 'Approval status before resource planning' in app)
check('Planner has explicit controlled horizon','planningHorizonDays||180' in svc and 'planningRecoveryDays||90' in svc and 'planningHorizonEnd' in svc)
check('Planner jumps across blocking intervals','blockingEnds' in svc and 'nextSearchPoint' in svc)
check('Planner rejects multi-year fake feasible result','instead of presenting a multi-year future date as “best feasible”' in svc)
for js in ['core.js','demo-data.js','repository.js','services.js','app.js','service-worker.js']:
    r=subprocess.run(['node','--check',str(ROOT/js)],capture_output=True,text=True)
    check(f'JavaScript syntax: {js}',r.returncode==0,(r.stderr.strip() or 'OK')[:180])
# Behaviour file is generated by the actual runtime regression script used for this release.
try:
    b=json.loads((ROOT/'VERIFICATION_BEHAVIOR_v1.0.93.json').read_text())
    check('Runtime behaviour regression',b.get('passed')==b.get('total')==10,json.dumps(b,separators=(',',':'))[:1400])
except Exception as e: check('Runtime behaviour regression',False,str(e))
try:
    before=json.loads((ROOT/'ROOT_CAUSE_REPRO_BEFORE_v1.0.93.json').read_text()); after=json.loads((ROOT/'ROOT_CAUSE_REPRO_AFTER_v1.0.93.json').read_text())
    check('Root cause reproduced on 1.0.92',before.get('forecast','')[:4]=='2029' and before.get('daysLate',0)>900,json.dumps(before,separators=(',',':')))
    check('Root cause fixed on 1.0.93',after.get('blocked') and after.get('code')=='CAPACITY_UNRESOLVABLE' and after.get('unchangedBookings') and after.get('ms',9999)<1000,json.dumps(after,separators=(',',':')))
except Exception as e: check('Root-cause before/after evidence',False,str(e))
r=subprocess.run([sys.executable,str(ROOT/'verification-browser-v193.py')],capture_output=True,text=True,timeout=120)
check('Chromium CP governance UX',r.returncode==0,(r.stdout.strip()[-1800:] if r.stdout else r.stderr.strip()[-1800:]))
failed=[x for x in checks if not x[1]]
result='\n'.join(('PASS' if ok else 'FAIL')+f' | {name}'+(f' | {detail}' if detail else '') for name,ok,detail in checks)+f"\n\nSUMMARY | {len(checks)-len(failed)}/{len(checks)} passed | {len(failed)} failed\n"
(ROOT/'VERIFICATION_RESULTS_v1.0.93.txt').write_text(result,encoding='utf-8')
print(f'\nSUMMARY | {len(checks)-len(failed)}/{len(checks)} passed | {len(failed)} failed')
sys.exit(1 if failed else 0)
