const fs=require('fs'),vm=require('vm'),path=require('path');
const root=__dirname; const ctx={console,Date,Math,Intl,setTimeout,clearTimeout};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['core.js','demo-data.js','services.js']) vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
const P=ctx.ProtoLab; let pass=0,fail=0; const rows=[];
function test(name,fn){try{fn();rows.push(['PASS',name]);pass++;}catch(e){rows.push(['FAIL',name,e.message]);fail++;}}
function assert(x,msg='assertion failed'){if(!x)throw new Error(msg)}
let state=P.createDemoState();
test('Demo state contains 15 prototype requests',()=>assert(state.requests.length===15));
test('Demo state contains 25+ process definitions',()=>assert(state.processes.length>=25));
test('Demo state contains 40+ serialized units',()=>assert(state.serials.length>=40,`got ${state.serials.length}`));
test('Serial numbers are unique',()=>assert(new Set(state.serials.map(s=>s.serial)).size===state.serials.length));
test('Initial seeded state passes implemented invariants',()=>{const e=P.validateInvariants(state);assert(e.length===0,e.join('; '))});
test('Request creation remains Draft and adds audit',()=>{const before=state.auditTrail.length;const r=new P.RequestService(state).create({title:'Verification request',productId:'PRD-001',quantity:2,requiredDate:'2026-12-01',objective:'Verification',engineeringTeam:'ADAS Sensors'});assert(r.status==='DRAFT REQUEST');assert(state.auditTrail.length===before+1)});
test('Request submission requires mandatory evidence fields',()=>{const rs=new P.RequestService(state);const r=state.requests[0];const old=r.objective;r.objective='';let threw=false;try{rs.submit(r.id)}catch(e){threw=true}r.objective=old;assert(threw)});
test('AUTO-PLAN assigns equipment and staff and preserves route order',()=>{const r=state.requests.find(x=>x.id==='P26-0042');const route=state.routes.find(x=>x.requestId===r.id);const orders=route.steps.map(s=>s.order).join(',');new P.PlannerService().autoPlan(state,r.id);assert(route.steps.every(s=>s.owner&&s.equipmentId));assert(route.steps.map(s=>s.order).join(',')===orders)});
test('Readiness identifies seeded blocker scenario',()=>{const r=state.requests[7];const rr=new P.ReadinessService(state).evaluate(r.id);assert(!rr.ready);assert(rr.issues.length>0)});
test('Controlled override rejects unauthorised role',()=>{state.identity={name:'Liam Smit',role:'technician'};let threw=false;try{new P.ReadinessService(state).override(state.requests[7].id,'Gate','reason','risk','Temporary',true)}catch(e){threw=true}assert(threw)});
test('Control Plan approved revision cannot be silently revised in place',()=>{state.identity={name:'Amina Kuiper',role:'administrator'};const cp=state.controlPlans.find(c=>c.status==='Approved');const oldId=cp.id,oldRev=cp.revision;const next=new P.ControlPlanService(state).revise(cp.id);assert(cp.status==='Superseded');assert(next.id!==oldId);assert(next.revision!==oldRev);assert(next.status==='Draft')});
test('Serial generation creates unique traceable serials',()=>{const r=state.requests[0];const before=state.serials.length;const out=new P.SerialService(state).generate(r.id,2);assert(state.serials.length===before+2);assert(new Set(out.map(x=>x.serial)).size===2)});
test('Quality release is blocked by unresolved release hold',()=>{state.identity={name:'Sofia Bakker',role:'quality'};const r=state.requests.find(x=>x.id==='P26-0050');let threw=false;try{new P.QualityService(state).releaseRequest(r.id)}catch(e){threw=/release hold/i.test(e.message)}assert(threw)});
test('Deviation cannot close while mandatory action remains open',()=>{const d=state.deviations.find(x=>x.status!=='CLOSED');d.disposition='Rework';let threw=false;try{new P.QualityService(state).closeDeviation(d.id)}catch(e){threw=true}assert(threw)});
test('Measurement limit evaluation detects fail',()=>{const q=new P.QualityService(state);assert(q.evaluateMeasurement({value:10,lsl:0,usl:5})===false)});
test('Process fit assessment distinguishes released vs adaptation',()=>{const p=state.processes.find(x=>x.id==='PROC-006');const svc=new P.ProcessService(state);const a=svc.fitAssessment(p,{material:'Stainless 304',thickness:.8,geometry:'flat',leakRequirement:true});const b=svc.fitAssessment(p,{material:'Stainless 304',thickness:.8,geometry:'complex',leakRequirement:true});assert(a.conclusion==='EXISTING RELEASED PROCESS');assert(b.conclusion==='MODIFIED PROCESS REQUIRED')});

test('Planner never assigns equipment with invalid calibration',()=>{const r=state.requests.find(x=>x.id==='P26-0042');const route=state.routes.find(x=>x.requestId===r.id);new P.PlannerService().autoPlan(state,r.id);assert(route.steps.every(s=>state.equipment.find(e=>e.id===s.equipmentId).calibrationStatus==='Valid'))});
test('Planner substitutes available qualified staff where preferred person is unavailable',()=>{const r=state.requests.find(x=>x.id==='P26-0047');const route=state.routes.find(x=>x.requestId===r.id);new P.PlannerService().autoPlan(state,r.id);assert(route.steps.every(s=>{const st=state.staff.find(x=>x.name===s.owner);return st&&st.available}))});
test('Process development cannot release with incomplete gates',()=>{const dev=state.processDevelopments.find(d=>d.id==='DEV-001');let threw=false;try{new P.ProcessService(state).releaseDevelopment(dev.id)}catch(e){threw=true}assert(threw)});
test('Completed process development releases reusable process revision',()=>{const local=P.createDemoState();local.identity={name:'Noah Visser',role:'process_engineer'};const dev=local.processDevelopments.find(d=>d.id==='DEV-001');Object.keys(dev.gates).forEach(k=>{if(k!=='release')dev.gates[k]=true});const before=local.processes.length;const id=new P.ProcessService(local).releaseDevelopment(dev.id);assert(local.processes.length===before+1);assert(local.processes.find(p=>p.id===id)?.status==='Released');assert(dev.gates.release===true)});
test('Control Plan separation of duties prevents self-approval',()=>{const local=P.createDemoState();const cp=local.controlPlans.find(c=>c.status==='Review requested');local.identity={name:cp.owner,role:'quality'};let threw=false;try{new P.ControlPlanService(local).approve(cp.id)}catch(e){threw=/self-approval|separation/i.test(e.message)}assert(threw)});
test('Independent Control Plan approval records person and timestamp',()=>{const local=P.createDemoState();const cp=local.controlPlans.find(c=>c.status==='Review requested');local.identity={name:'Nora Dekker',role:'approver'};new P.ControlPlanService(local).approve(cp.id);assert(cp.status==='Approved');assert(cp.approvedBy==='Nora Dekker');assert(cp.approvedAt)});
test('Approver / Reviewer has explicit Control Plan approval permission',()=>assert(P.can('approver','controlplan:approve')));
test('Control Plan service rejects a role without approval authority',()=>{const local=P.createDemoState();const cp=local.controlPlans.find(c=>c.status==='Review requested');local.identity={name:'Liam Smit',role:'technician'};let threw=false;try{new P.ControlPlanService(local).approve(cp.id)}catch(e){threw=/not authorised/i.test(e.message)}assert(threw)});

test('Rework seed preserves original process history and explicit loop',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0052');const route=local.routes.find(x=>x.requestId===r.id);const ser=local.serials.find(x=>x.requestId===r.id&&x.status==='Reworked');assert(route.reworkLoops.length>0);assert(ser.processHistory.length>0)});
test('Failed objective measurement exists with quality hold linkage',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0050');assert(local.measurements.some(m=>m.requestId===r.id&&!m.pass));assert(local.deviations.some(d=>d.requestId===r.id&&d.releaseHold))});
test('Delivered serial retains delivery reference',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0055');const ss=local.serials.filter(s=>s.requestId===r.id);assert(ss.length>0);assert(ss.every(s=>s.delivery&&s.delivery.reference))});
test('Report service assembles serial, measurement and deviation evidence',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0050');const rep=new P.ReportService(local).build(r.id,false);assert(rep.r.id===r.id);assert(rep.serials.length>0);assert(rep.meas.length>0);assert(rep.dev.length>0);assert(rep.approved===false)});
test('Auditor has view permission but no execution permission',()=>{assert(P.can('auditor','request:view'));assert(!P.can('auditor','execution:run'))});
test('Administrator wildcard permission allows configuration actions',()=>assert(P.can('administrator','any:future:permission')));

test('Demo reset seed is a fresh deep copy',()=>{const a=P.createDemoState(),b=P.createDemoState();a.requests[0].title='mutated';assert(b.requests[0].title!=='mutated')});
test('Seeded approved Control Plans use independent approver evidence',()=>{const local=P.createDemoState();assert(local.controlPlans.filter(c=>c.status==='Approved').every(c=>c.approvedBy&&c.approvedBy!==c.owner))});


test('New request receives exact BOM material requirements and a proposed standard route',()=>{const local=P.createDemoState();local.identity={name:'Eva de Vries',role:'engineering_requester'};const r=new P.RequestService(local).create({title:'New exact-BOM request',productId:'PRD-008',quantity:3,requiredDate:'2026-12-01',objective:'Verification',engineeringTeam:'Advanced Engineering',configuration:'PSC-X2-P3',bomRef:'BOM-PSC-X2-P3'});assert(r.materialRequirements.length===3);assert(r.materialRequirements.every(x=>x.partNumber&&x.revision&&x.requiredQty===3));const route=local.routes.find(x=>x.requestId===r.id);assert(route&&route.proposed===true&&route.confirmed===false&&route.steps.length>0)});
test('Arbitrary material allocation cannot satisfy an exact BOM requirement',()=>{const local=P.createDemoState();const r=local.requests[0];P.ensureMaterialRequirements(local,r);local.allocations=local.allocations.filter(a=>a.requestId!==r.id);const wrong=local.materials.find(m=>!r.materialRequirements.some(q=>q.partNumber===m.partNumber&&q.revision===m.revision));local.allocations.push({id:'WRONG',requestId:r.id,materialId:wrong.id,lot:wrong.lot,qty:999,status:'Issued'});const rr=new P.ReadinessService(local).evaluate(r.id);const material=rr.checks.find(x=>x[0]==='Material ready for intended build');assert(material&&material[1]===false)});
test('Exact part/revision allocations satisfy material readiness',()=>{const local=P.createDemoState();const r=local.requests[0];P.ensureMaterialRequirements(local,r);local.allocations=local.allocations.filter(a=>a.requestId!==r.id);for(const req of r.materialRequirements){const m=local.materials.find(x=>x.partNumber===req.partNumber&&x.revision===req.revision&&x.status==='Available');local.allocations.push({id:P.uid('A'),requestId:r.id,requirementId:req.id,materialId:m.id,lot:m.lot,qty:req.requiredQty,status:'Issued'});}const rr=new P.ReadinessService(local).evaluate(r.id);const material=rr.checks.find(x=>x[0]==='Material ready for intended build');assert(material&&material[1]===true)});
test('AUTO-PLAN creates visible step bookings and a timing triage result',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0042');local.bookings=local.bookings.filter(b=>b.requestId!==r.id);const changes=new P.PlannerService().autoPlan(local,r.id);const bookings=local.bookings.filter(b=>b.requestId===r.id);assert(changes.length>0);assert(bookings.length===changes.length);assert(bookings.every(b=>b.stepName&&b.start&&b.end&&b.staffId));assert(r.triage&&r.triage.forecastDate&&typeof r.triage.slackDays==='number'&&r.triage.effortHours>0)});
test('AUTO-PLAN respects locked bookings on the same request',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0042'),route=local.routes.find(x=>x.requestId===r.id),proc=local.processes.find(x=>x.id===route.steps[0].processId),eq=local.equipment.find(x=>x.capability===proc.equipmentCapability&&x.calibrationStatus==='Valid'),person=local.staff.find(x=>x.available&&x.competencies.includes(proc.competency));const start=new Date(Date.now()+30*60000);const end=new Date(start.getTime()+8*3600000);local.bookings.push({id:'LOCK',requestId:r.id,resourceId:eq.id,equipmentId:eq.id,staffId:person.id,start:start.toISOString(),end:end.toISOString(),durationHours:8,locked:true,status:'Locked'});new P.PlannerService().autoPlan(local,r.id);const generated=local.bookings.filter(b=>b.requestId===r.id&&!b.locked);assert(generated.length>0);assert(!generated.some(b=>b.equipmentId===eq.id&&new Date(b.start)<end&&new Date(b.end)>start))});
test('Limit-only special characteristic can pass Control Plan definition',()=>{const local=P.createDemoState();const cp=local.controlPlans.find(c=>c.status==='Review requested');const c=cp.characteristics.find(x=>x.classification);c.target='';c.lsl=1;c.usl=3;c.method='Leak test';c.equipment='EQ-003';c.sampleSize='100%';c.frequency='Each unit';c.reactionPlan='Hold affected serial; notify Quality; disposition before release.';c.evidence='Digital traveller result';assert(P.controlCharacteristicReady(c));local.identity={name:'Nora Dekker',role:'approver'};new P.ControlPlanService(local).approve(cp.id);assert(cp.status==='Approved')});
test('Product-safety request automatically gets a concrete pending approval record',()=>{const local=P.createDemoState();local.identity={name:'Eva de Vries',role:'engineering_requester'};const r=new P.RequestService(local).create({title:'Safety build',productId:'PRD-001',quantity:2,requiredDate:'2026-12-01',objective:'Safety check',engineeringTeam:'ADAS Sensors',customerId:'CUST-OEMA',configuration:'BPS-3200-D',bomRef:'BOM-BPS-3200-D',productSafety:true});const a=local.approvals.find(x=>x.requestId===r.id&&x.type==='Product Safety');assert(a&&a.status==='Pending'&&a.role==='Product Safety Representative'&&a.person)});


test('Only Engineering supplied and Lab supplied material routes are supported',()=>{assert(P.normaliseMaterialSource('Lab stock')==='Lab supplied');assert(P.normaliseMaterialSource('External supplier')==='Engineering supplied');const local=P.createDemoState();assert(local.requests.every(r=>['Engineering supplied','Lab supplied'].includes(r.materialOwnership)))});
test('Lab supplied material must be exact-reserved before AUTO-PLAN eligibility',()=>{const local=P.createDemoState();local.identity={name:'Eva de Vries',role:'engineering_requester'};const r=new P.RequestService(local).create({title:'Lab stock verification',productId:'PRD-001',quantity:2,requiredDate:'2026-12-01',objective:'Check planning prerequisite',engineeringTeam:'ADAS Sensors',materialOwnership:'Lab supplied',characterisation:['Functional verification']});new P.RequestService(local).submit(r.id);const route=local.routes.find(x=>x.requestId===r.id);route.confirmed=true;assert(P.materialPlanningAssessment(local,r).planningReady===false);for(const req of r.materialRequirements){const m=local.materials.find(x=>x.partNumber===req.partNumber&&x.revision===req.revision&&x.quantity>=req.requiredQty);local.allocations.push({id:P.uid('A'),requestId:r.id,requirementId:req.id,materialId:m.id,lot:m.lot,qty:req.requiredQty,status:'Reserved'});m.quantity-=req.requiredQty;}assert(P.materialPlanningAssessment(local,r).planningReady===true)});
test('Engineering supplied material uses promised arrival as planning input but not Build Readiness',()=>{const local=P.createDemoState();local.identity={name:'Eva de Vries',role:'engineering_requester'};const r=new P.RequestService(local).create({title:'Engineering supply verification',productId:'PRD-001',quantity:2,requiredDate:'2026-12-01',objective:'Check supply promise',engineeringTeam:'ADAS Sensors',materialOwnership:'Engineering supplied',materialSupplyOwner:'Eva de Vries',materialSupplyDate:'2026-11-20',characterisation:['Functional verification']});const a=P.materialPlanningAssessment(local,r);assert(a.planningReady&&a.earliestDate==='2026-11-20'&&!a.buildReady)});
test('AUTO-PLAN can create a provisional best-feasible preview before route/test definition is complete',()=>{const local=P.createDemoState();local.identity={name:'Eva de Vries',role:'engineering_requester'};const r=new P.RequestService(local).create({title:'Flow verification',productId:'PRD-001',quantity:2,requiredDate:'2026-12-01',objective:'Check flow',engineeringTeam:'ADAS Sensors',materialOwnership:'Engineering supplied',materialSupplyOwner:'Eva de Vries',materialSupplyDate:'2026-11-20',characterisation:['Functional verification']});const changes=new P.PlannerService().autoPlan(local,r.id);assert(changes.length>0);assert(r.triage&&/Provisional|Best/.test(r.triage.planQuality));assert((r.triage.riskNotes||[]).some(x=>/Process\/test definition is incomplete/i.test(x)))});
test('Standard tests and competency master data are present and used by planning',()=>{const local=P.createDemoState();assert(local.standardTests.length>=8);assert(local.competencies.length>=8);const r=local.requests.find(x=>x.id==='P26-0042');const changes=new P.PlannerService().autoPlan(local,r.id);const bs=local.bookings.filter(b=>b.requestId===r.id);assert(bs.some(b=>b.taskType==='test'));assert(bs.filter(b=>b.taskType==='test').every(b=>b.skillId&&b.staffId&&b.estimateBasis))});
test('Historical same-product builds refine estimates',()=>{const local=P.createDemoState(),r=local.requests.find(x=>x.id==='P26-0042'),proc=local.processes.find(p=>p.id===local.routes.find(x=>x.requestId===r.id).steps[0].processId),est=new P.LearningService().estimateProcess(local,r,proc);assert(est.samples>=3);assert(/history/i.test(est.basis))});
test('Closing a build captures learning record once',()=>{const local=P.createDemoState(),r=local.requests.find(x=>x.id==='P26-0055');r.status='DELIVERED';const before=local.buildHistory.length;new P.LearningService().captureBuild(local,r.id);new P.LearningService().captureBuild(local,r.id);assert(local.buildHistory.length===before+1);assert(local.buildHistory.some(h=>h.requestId===r.id))});


console.log(rows.map(r=>r.join(' | ')).join('\n'));console.log(`\nRESULT: ${pass} passed, ${fail} failed`);process.exitCode=fail?1:0;
