const fs=require('fs'),vm=require('vm'),path=require('path');
const root=__dirname; const ctx={console,Date,Math,Intl,setTimeout,clearTimeout};ctx.window=ctx;vm.createContext(ctx);
for(const f of ['core.js','demo-data.js','services.js']) vm.runInContext(fs.readFileSync(path.join(root,f),'utf8'),ctx,{filename:f});
const P=ctx.ProtoLab; let pass=0,fail=0; const rows=[];
function test(name,fn){try{fn();rows.push(['PASS',name]);pass++;}catch(e){rows.push(['FAIL',name,e.message]);fail++;}}
function assert(x,msg='assertion failed'){if(!x)throw new Error(msg)}
let state=P.createDemoState();
test('Demo state contains 15 prototype requests',()=>assert(state.requests.length===15));
test('Demo state contains 25+ process definitions',()=>assert(state.processes.length>=25));
test('Demo state contains 40+ serialized units',()=>assert(state.serials.length>=40,`got ${state.serials.length}`));
test('Serial numbers are unique',()=>assert(new Set(state.serials.map(s=>s.serial)).size===state.serials.length));
test('Initial seeded state passes implemented invariants',()=>{const e=P.validateInvariants(state);assert(e.length===0,e.join('; '))});
test('Request creation remains Draft and adds audit',()=>{const before=state.auditTrail.length;const r=new P.RequestService(state).create({title:'Verification request',productId:'PRD-001',quantity:2,requiredDate:'2026-12-01',objective:'Verification',engineeringTeam:'ADAS Sensors'});assert(r.status==='DRAFT REQUEST');assert(state.auditTrail.length===before+1)});
test('Request submission requires mandatory evidence fields',()=>{const rs=new P.RequestService(state);const r=state.requests[0];const old=r.objective;r.objective='';let threw=false;try{rs.submit(r.id)}catch(e){threw=true}r.objective=old;assert(threw)});
test('AUTO-PLAN assigns equipment and staff and preserves route order',()=>{const r=state.requests[0];const route=state.routes.find(x=>x.requestId===r.id);const orders=route.steps.map(s=>s.order).join(',');new P.PlannerService().autoPlan(state,r.id);assert(route.steps.every(s=>s.owner&&s.equipmentId));assert(route.steps.map(s=>s.order).join(',')===orders)});
test('Readiness identifies seeded blocker scenario',()=>{const r=state.requests[7];const rr=new P.ReadinessService(state).evaluate(r.id);assert(!rr.ready);assert(rr.issues.length>0)});
test('Controlled override rejects unauthorised role',()=>{state.identity={name:'Liam Smit',role:'technician'};let threw=false;try{new P.ReadinessService(state).override(state.requests[7].id,'Gate','reason','risk','Temporary',true)}catch(e){threw=true}assert(threw)});
test('Control Plan approved revision cannot be silently revised in place',()=>{state.identity={name:'Amina Kuiper',role:'administrator'};const cp=state.controlPlans.find(c=>c.status==='Approved');const oldId=cp.id,oldRev=cp.revision;const next=new P.ControlPlanService(state).revise(cp.id);assert(cp.status==='Superseded');assert(next.id!==oldId);assert(next.revision!==oldRev);assert(next.status==='Draft')});
test('Serial generation creates unique traceable serials',()=>{const r=state.requests[0];const before=state.serials.length;const out=new P.SerialService(state).generate(r.id,2);assert(state.serials.length===before+2);assert(new Set(out.map(x=>x.serial)).size===2)});
test('Quality release is blocked by unresolved release hold',()=>{state.identity={name:'Sofia Bakker',role:'quality'};const r=state.requests.find(x=>x.id==='P26-0050');let threw=false;try{new P.QualityService(state).releaseRequest(r.id)}catch(e){threw=/release hold/i.test(e.message)}assert(threw)});
test('Deviation cannot close while mandatory action remains open',()=>{const d=state.deviations.find(x=>x.status!=='CLOSED');d.disposition='Rework';let threw=false;try{new P.QualityService(state).closeDeviation(d.id)}catch(e){threw=true}assert(threw)});
test('Measurement limit evaluation detects fail',()=>{const q=new P.QualityService(state);assert(q.evaluateMeasurement({value:10,lsl:0,usl:5})===false)});
test('Process fit assessment distinguishes released vs adaptation',()=>{const p=state.processes.find(x=>x.id==='PROC-006');const svc=new P.ProcessService(state);const a=svc.fitAssessment(p,{material:'Stainless 304',thickness:.8,geometry:'flat',leakRequirement:true});const b=svc.fitAssessment(p,{material:'Stainless 304',thickness:.8,geometry:'complex',leakRequirement:true});assert(a.conclusion==='EXISTING RELEASED PROCESS');assert(b.conclusion==='MODIFIED PROCESS REQUIRED')});

test('Planner never assigns equipment with invalid calibration',()=>{const r=state.requests.find(x=>x.id==='P26-0042');const route=state.routes.find(x=>x.requestId===r.id);new P.PlannerService().autoPlan(state,r.id);assert(route.steps.every(s=>state.equipment.find(e=>e.id===s.equipmentId).calibrationStatus==='Valid'))});
test('Planner substitutes available qualified staff where preferred person is unavailable',()=>{const r=state.requests.find(x=>x.id==='P26-0047');const route=state.routes.find(x=>x.requestId===r.id);new P.PlannerService().autoPlan(state,r.id);assert(route.steps.every(s=>{const st=state.staff.find(x=>x.name===s.owner);return st&&st.available}))});
test('Process development cannot release with incomplete gates',()=>{const dev=state.processDevelopments.find(d=>d.id==='DEV-001');let threw=false;try{new P.ProcessService(state).releaseDevelopment(dev.id)}catch(e){threw=true}assert(threw)});
test('Completed process development releases reusable process revision',()=>{const local=P.createDemoState();local.identity={name:'Noah Visser',role:'process_engineer'};const dev=local.processDevelopments.find(d=>d.id==='DEV-001');Object.keys(dev.gates).forEach(k=>{if(k!=='release')dev.gates[k]=true});const before=local.processes.length;const id=new P.ProcessService(local).releaseDevelopment(dev.id);assert(local.processes.length===before+1);assert(local.processes.find(p=>p.id===id)?.status==='Released');assert(dev.gates.release===true)});
test('Control Plan separation of duties prevents self-approval',()=>{const local=P.createDemoState();const cp=local.controlPlans.find(c=>c.status==='Review requested');local.identity={name:cp.owner,role:'quality'};let threw=false;try{new P.ControlPlanService(local).approve(cp.id)}catch(e){threw=/self-approval|separation/i.test(e.message)}assert(threw)});
test('Independent Control Plan approval records person and timestamp',()=>{const local=P.createDemoState();const cp=local.controlPlans.find(c=>c.status==='Review requested');local.identity={name:'Nora Dekker',role:'approver'};new P.ControlPlanService(local).approve(cp.id);assert(cp.status==='Approved');assert(cp.approvedBy==='Nora Dekker');assert(cp.approvedAt)});
test('Rework seed preserves original process history and explicit loop',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0052');const route=local.routes.find(x=>x.requestId===r.id);const ser=local.serials.find(x=>x.requestId===r.id&&x.status==='Reworked');assert(route.reworkLoops.length>0);assert(ser.processHistory.length>0)});
test('Failed objective measurement exists with quality hold linkage',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0050');assert(local.measurements.some(m=>m.requestId===r.id&&!m.pass));assert(local.deviations.some(d=>d.requestId===r.id&&d.releaseHold))});
test('Delivered serial retains delivery reference',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0055');const ss=local.serials.filter(s=>s.requestId===r.id);assert(ss.length>0);assert(ss.every(s=>s.delivery&&s.delivery.reference))});
test('Report service assembles serial, measurement and deviation evidence',()=>{const local=P.createDemoState();const r=local.requests.find(x=>x.id==='P26-0050');const rep=new P.ReportService(local).build(r.id,false);assert(rep.r.id===r.id);assert(rep.serials.length>0);assert(rep.meas.length>0);assert(rep.dev.length>0);assert(rep.approved===false)});
test('Auditor has view permission but no execution permission',()=>{assert(P.can('auditor','request:view'));assert(!P.can('auditor','execution:run'))});
test('Administrator wildcard permission allows configuration actions',()=>assert(P.can('administrator','any:future:permission')));

console.log(rows.map(r=>r.join(' | ')).join('\n'));console.log(`\nRESULT: ${pass} passed, ${fail} failed`);process.exitCode=fail?1:0;
