#!/usr/bin/env python3
from pathlib import Path
import json,re,subprocess,sys,zipfile
ROOT=Path(__file__).resolve().parent
checks=[]
def check(name,cond,detail=''):
    checks.append((name,bool(cond),str(detail)));print(('PASS' if cond else 'FAIL')+' | '+name+(f' | {detail}' if detail else ''));return bool(cond)
def text(n):return (ROOT/n).read_text(encoding='utf-8',errors='replace')
core=text('core.js');demo=text('demo-data.js');services=text('services.js');app=text('app.js');styles=text('styles.css');index=text('index.html');sw=text('service-worker.js')
check('Core version is REV 1.0.96',"ProtoLab.VERSION = '1.0.96-poc'" in core)
check('HTML badge is REV 1.0.96','REV 1.0.96' in index)
for f in ['styles.css','core.js','demo-data.js','repository.js','services.js','app.js']:check(f'Cache bust updated: {f}',f'{f}?v=1.0.96' in index)
check('Service-worker reset is REV 1.0.96','1.0.96' in sw)
for f in ['core.js','demo-data.js','repository.js','services.js','app.js','service-worker.js']:
    p=subprocess.run(['node','--check',str(ROOT/f)],capture_output=True,text=True);check(f'JavaScript syntax: {f}',p.returncode==0,(p.stderr or '').strip())
# Universal timeline architecture
check('Universal semantic timeline renderer exists','V1096_TIMELINE_SPANS' in app and 'v1096TimelineRange' in app and 'v1096TimelineAxis' in app)
check('Horizon picker removed from active render','html.replace(/<label class="compact-select">Horizon<select id="planWeeks">' in app)
check('Universal zoom order and semantics encoded',all(x in app for x in ['data-v1096-timeline-zoom="in"','>−</button>','data-v1096-timeline-zoom="fit"','>Fit</button>','data-v1096-timeline-zoom="out"','>+</button>']))
check('Minus reduces date span and plus increases date span',"if(action==='in'){const smaller" in app and "else{const larger" in app)
check('Fit is data-derived from selected plans','v1096FitRange(opts)' in app and "state.mode==='fit'" in app)
check('Calendar uses grouped month + ISO week-year + date rows','timeline-month-row-v1096' in app and 'timeline-week-row-v1096' in app and 'timeline-day-row-v1096' in app and 'isoWeekPartsV1094' in app)
check('Month format includes year',"{month:'short',year:'numeric'}" in app)
check('ISO week-year format includes CW and year','`CW ${String(p.week).padStart' in app)
check('Universal board is full-width grid','grid-template-columns:minmax(145px,190px) minmax(0,1fr)!important' in styles and 'width:100%!important' in styles)
check('Timeline scrolling is disabled in favor of semantic span zoom','timeline-scroll-v1096' in styles and 'overflow:hidden!important' in styles)
check('Sticky build planner uses universal timeline',"planningSwimlane({view:'build',requestId:r.id,includePotential:false,context:'sticky'" in app)
check('Legacy generic width zoom disabled','v1078ApplyGenericSwimZoom=function(){}' in app and 'v1078PrepareBuildZoom=function(){}' in app)
check('Legacy grouped-axis mutator disabled','v1094GroupedCalendarAxis=function(){}' in app)
# Master planner / filter population
check('All active builds populate portfolio lanes before booking events','for(const r of active)' in app and 'addLane(r.id' in app)
check('Unplanned active builds get explicit schedule-unresolved state','Schedule unresolved · use guided AUTO-PLAN recovery' in app)
check('Health filters feed visible build IDs','visibleIds=new Set(healthRows.map' in app and "healthKey=App.filters.planHealth||'all'" in app)
check('Six health tiles retained',all(tok in app for tok in ["tile('all','All'","tile('onTime','On time'","tile('late','Late builds'","tile('lateDays','Total days late'","tile('movement','Commitment movement'","tile('unplanned','Unplanned'"]))
# Single planner engine architecture
check('One PlanningEngine facade exists','P.PlanningEngineV1096={' in services)
check('AUTO aliases route into V1096 engine','P.buildAutoPlanTiersV1094=P.buildAutoPlanTiersV1096' in services and 'P.buildEscalationPlanV1094=P.buildEscalationPlanV1096' in services)
check('Manual plan routes through same PlannerService.autoPlan','manualPlan(state,requestId' in services and 'new PlannerService().autoPlan(next,requestId)' in services)
check('Manual constraints are validated by same resource/sequence kernel','planningConstraintsV1096' in services and 'MANUAL_CONSTRAINT_INVALID' in services)
check('Protected planner isolates failed build transactions','Protected planning isolates a failed build transactionally' in services and 'plannerSafeRequestAttemptV1096' in services)
check('Selectable tiers must be complete','c?.ok&&c.complete&&targetOk(c)' in services)
check('Red tier requires whole-lab improvement plus a worsened project','red.metrics.score<reference' in services and 'red.worsened.length>0' in services)
check('Escalation is target-first and replans remaining portfolio','targetAttempt=plannerSafeRequestAttemptV1096(base,targetRequestId' in services and 'remaining=open.filter' in services and 'for(const orderMode of this.orderModes)' in services)
check('Final integrity audits remain hard gates','plannerIntegrityV1096' in services and 'P.validateInvariants' in services and 'P.planningIntegrityAudit' in services)
check('Canonical task model remains source for planning','P.planningTasksForRequest' in services and 'P.planningTaskCoverage' in services)
check('Capacity search remains bounded','planningHorizonEnd' in services and "e.code='CAPACITY_UNRESOLVABLE'" in services)
check('Raw multi-year legacy error is absent','no conflict-free slot exists within the controlled planning horizon' not in services+app)
# Guided recovery
check('Guided recovery has root-cause workflow','ONE PLANNING ENGINE · GUIDED RECOVERY' in app and 'Root cause isolated' in app and 'Same solver recalculates end-to-end' in app)
check('Guided recovery offers operational actions','Add / borrow capacity' in app and 'Manual plan · same solver' in app and 'Escalation mode' in app)
check('AUTO PLAN isolates blockers and keeps portfolio planning','Blocked builds do not stop the rest of the portfolio' in app)
# Provider-neutral authority retained
check('Provider-neutral project teams retained','identityProvider' in core and 'externalPrincipalId' in core and 'approvalRights' in core and 'roleBindings' in core)
# Browser/adversarial suite
bp=ROOT/'VERIFICATION_BROWSER_v1.0.96.json';check('REV 1.0.96 browser verification exists',bp.exists())
if bp.exists():
    b=json.loads(bp.read_text())
    check('Browser: no horizon input',b.get('horizonInput')==0)
    check('Browser: no legacy zoom controls',b.get('legacyGenericZoom')==0 and b.get('legacyStickyZoom')==0)
    check('Browser: toolbar order is minus / Fit / plus',b.get('toolbarButtons')==['−','Fit','+'])
    fw=b.get('fullWidth') or {};check('Browser: main swimlane has no horizontal overflow',fw.get('scrollWidth',9)<=fw.get('scrollClient',0)+2 and fw.get('boardWidth',9)<=fw.get('parent',0)+2,fw)
    z=b.get('zoomSemantics') or {};check('Browser: minus zooms in, plus zooms out, Fit restores',z.get('minus2',99)<z.get('minus1',99)<z.get('fit',0) and z.get('plus',0)>z.get('minus2',99) and abs(z.get('fitRestored',0)-z.get('fit',99))<.01,z)
    check('Browser: grouped header has valid month-year labels',all(re.match(r'^[A-Z]{3} 20\d{2}$',x) for x in b.get('calendarMonths') or []) and bool(b.get('calendarMonths')))
    check('Browser: grouped header has valid ISO CW-year labels',all(re.match(r'^CW \d{2} · 20\d{2}$',x) for x in b.get('calendarWeeks') or []) and bool(b.get('calendarWeeks')))
    check('Browser: daily detail row appears at day-scale',int(b.get('calendarDayCount') or 0)>0 and b.get('calendarAxisRows')==3)
    check('Browser: ISO year boundary is correct',b.get('isoBoundary')=={'year':2026,'week':53},b.get('isoBoundary'))
    filters=b.get('filters') or {};check('Browser: all six tiles filter the swimlane population',len(filters)==6 and all(v.get('tile') and v.get('active')==k and v.get('actual')==v.get('expected') for k,v in filters.items()),filters)
    uv=b.get('unplannedCommittedVisible') or {};check('Browser: active committed unplanned build remains visible',uv.get('visible') is True and uv.get('unresolved') is True,uv)
    other=b.get('otherTimelineContexts') or {};check('Browser: build page and sticky menu share universal timeline',other.get('buildUniversal')==1 and other.get('stickyUniversal')==1 and other.get('buildToolbar')==['−','Fit','+'] and other.get('stickyToolbar')==['−','Fit','+'],other)
    ca=b.get('canonicalAlignment') or {};check('Browser: canonical tasks align with manual/sticky/process UI',all(ca.get(k) is True for k in ['manualIdsEqual','stickyNamesEqual','flowTestsPresent','hasFinal']),ca)
    ae=b.get('autoEngine') or {};check('Browser: AUTO PLAN returns complete selectable candidate',ae.get('recommended') in {'green','yellow','red'} and ae.get('allSelectableComplete') is True and ae.get('redRule') is True,ae)
    check('Browser: AUTO PLAN portfolio benchmark under 8 s',float(ae.get('elapsed') or 99999)<8000,ae.get('elapsed'))
    fi=b.get('failureIsolation') or {};check('Browser: protected planner isolates one failed build and continues',fi.get('ok') and fi.get('partial') and fi.get('blocked',0)>=1 and fi.get('planned',0)>=1 and fi.get('victimBlocked') and fi.get('liveUnchanged'),fi)
    mu=b.get('manualUnified') or {};check('Browser: manual constraints use unified solver with zero conflicts',mu.get('ok') and mu.get('coverage') and mu.get('manualMarked') and mu.get('collisions')==0 and mu.get('readiness')==0,mu)
    ex=b.get('escalation') or {};check('Browser: escalation produces valid target-first recovered portfolio',ex.get('ok') and ex.get('invariants')==0 and ex.get('collisions')==0 and ex.get('readiness')==0 and ex.get('after'),ex)
    check('Browser: escalation benchmark under 8 s',float(ex.get('elapsed') or 99999)<8000,ex.get('elapsed'))
    hg=b.get('horizonGuard') or {};check('Browser: extreme-horizon guard does not invent remote plan or mutate live data',hg.get('recommended') is None and not hg.get('eligible') and hg.get('rawRemote') is False and hg.get('unchanged') is True,hg)
    actions=b.get('guidedRecoveryActions') or [];check('Browser: blocked plan presents guided actions, not Close-only',len(actions)>2 and 'Manual plan · same solver' in actions and 'Escalation mode' in actions,actions)
    check('Browser: live AUTO PLAN modal is actionable',b.get('autoModalTierCount')==3 and any(('Review' in x or 'Resolve blocker' in x) for x in b.get('autoModalActions') or []),b.get('autoModalActions'))
    check('Browser: zero page errors',not b.get('pageErrors'),b.get('pageErrors'))
shot=ROOT/'REV1096_UNIVERSAL_TIMELINE_PROOF.png';check('Universal timeline visual proof exists',shot.exists() and shot.stat().st_size>10000,shot.stat().st_size if shot.exists() else 0)
passed=sum(1 for _,ok,_ in checks if ok);failed=len(checks)-passed
(ROOT/'VERIFICATION_RESULTS_v1.0.96.txt').write_text('\n'.join([f'LabOS REV 1.0.96 verification',f'Passed: {passed}',f'Failed: {failed}',f'Total: {len(checks)}','']+[f'{"PASS" if ok else "FAIL"} | {n}'+(f' | {d}' if d else '') for n,ok,d in checks])+'\n',encoding='utf-8')
print(f'\nSUMMARY {passed}/{len(checks)} passed; {failed} failed')
sys.exit(0 if failed==0 else 1)
